### ISSUE TITLE
terceros

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#1]
@fauno 

por qué el (mal) plural?

```
t.string "direccions"
```

y además, se puede guardar un tercero sin ningún dato. Y no hiciste la fábrica para los tests.

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> @fauno 
> 
> por qué el (mal) plural?
> 
> ```
> t.string "direccions"
> ```

no sé por qué lo pluralizó si yo le dije que sea direccion

> y además, se puede guardar un tercero sin ningún dato.

oh noes

> Y no hiciste la fábrica para los tests.

boohoo >:)

## 

:{

**Comment by mauriciopasquier** [comment]
Ah, lo cierra sólo si se mergea en master. Clever, github, clever
