### ISSUE TITLE
que pasa si se borra un cheque no pagado/cobrado

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#100]
deberiamos rollbackear los movimientos?

**Comment by mauriciopasquier** [comment]
si borrás el movimiento desaparece de todos lados, no? no entiendou

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> si borrás el movimiento desaparece de todos lados, no? no entiendou

si el cheque borra sus movimientos decis

## 

http://endefensadelsl.org

**Comment by mauriciopasquier** [comment]
On Tue, Apr 01, 2014 at 03:20:24PM -0700, fauno wrote:

> Mauricio Pasquier Juan notifications@github.com writes:
> 
> > si borrás el movimiento desaparece de todos lados, no? no entiendou
> 
> si el cheque borra sus movimientos decis

claro

##

**Comment by mauriciopasquier** [comment]
Entonces, lo que pasa, es que el cheque desaparece junto con sus movimientos.
