### ISSUE TITLE
selector de adjuntos renderiza mal nombres largos

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#104]
ver http://www.enmotoneta.com.ar/pasties/problema-en-autocomplete.png

**Comment by fauno** [comment]
bueno no se ve la captura, pero no es una limitacion del navegador?

**Comment by m4tu5** [comment]
nueva captura en http://hq.duvium.com/pasties/problema-en-autocomplete.png

**Comment by fauno** [comment]
se perdieron las dos capturas... estas hablando del selector de retenciones? donde mas hay adjuntos? 

![adjuntos](https://cloud.githubusercontent.com/assets/468204/4340208/b4f614bc-402b-11e4-891c-ab0956dcc5a2.png)

**Comment by m4tu5** [comment]
si, es acá ... pasaba cuando en lugar de reporte.pdf tenes un nombre mucho mas largo ... pero podemos dejarlo así de momento y pasar el issue a v1.1

**Comment by sudoaza** [comment]
![captura de pantalla - 240914 - 23 01 20](https://cloud.githubusercontent.com/assets/555365/4398521/e9986e06-4457-11e4-93c6-9fcce94f33ba.png)

Para,, hay un tag para esto

**Comment by mauriciopasquier** [comment]
jaja
