### ISSUE TITLE
no se pueden ordenar recibos por importe

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#121]
el importe ya no es un campo de la tabla de recibos y no se puede ordenar el listado como se venia haciendo por ser importe ahora un metodo y no un objeto

**Comment by sudoaza** [comment]
Esto lo vi al mergear, algunas cosas las pude fixear pero si otras quedaron mal y no pude resolver que era rapidamente.

**Comment by mauriciopasquier** [comment]
mmm... podríamos reagregarlo como cálculo que se actualiza al guardar el recibo..

**Comment by m4tu5** [comment]
tal vez ahora encontramos una forma mas amistosa de hacerlo?
solo puede cambiar el monto cuando se agregan o quitan movimientos (y de momento solo se agregan) ... ya no se puede editar el monto a mano, asi que tal vez con simplemente crear el campo y meter el total al crear el recibo estemos.

**Comment by mauriciopasquier** [comment]
On Fri, Apr 04, 2014 at 06:29:39PM -0700, m4tu5 wrote:

> tal vez ahora encontramos una forma mas amistosa de hacerlo?
> solo puede cambiar el monto cuando se agregan o quitan movimientos (y de
> momento solo se agregan) ... ya no se puede editar el monto a mano, asi que
> tal vez con simplemente crear el campo y meter el total al crear el recibo
> estemos.

mmmmm.. puede ser, puede ser

##

**Comment by fauno** [comment]
ya lo resolvi eh
