### ISSUE TITLE
Causas para movimientos

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#123]
Hasta ahora sólo hay causas para los movimentos que son un pago. Surgen algunas cuestiones:
- Nos interesa diferenciar la causa de un pago por transferencia con la de una transferencia interna?
- Nos interesa diferenciar la causa de un pago en efectivo de la de un cobro en efectivo?

Ya se me ocurrirán otras, pero piensen causas para todo lo que genere movimientos

**Comment by mauriciopasquier** [comment]
@m4tu5 también se me ocurre: se puede hacer transferencias entre cajas de efectivo? Las causas siguen siendo transferencias?

**Comment by m4tu5** [comment]
no nos interesa diferenciar causas de un pago por transferencia, ni transferencias internas, ni las de pagos cobros.

si pensamos en las 'causas' como el soporte documental para el flujo de fondos, la causa de un movimiento en efectivo seria el fajo de billetes, o en su defecto, los numeros de serie de los billetes. de las transferencias las causas serían los comprobantes de transferencias, o los numeros de transaccion que entregue el banco.

nada de esto es interesante. el cheque si, porque es una moneda que emiten ellos mismos, entonces tienen que tener controlada la emisión para no desmadrarse.

las retenciones, sus PDF, tienen valor de cambio porque en la practica un tercero te lo acepta por su valor declarado, como si fuese dinero.

**Comment by m4tu5** [comment]
las transferencias entre cajas, igual ... no nos interesa la causa ... si nos interesa saber que en cierta fecha, una cantidad de dinero (en una o otra forma) salio de una caja y entro en otra ... esta información nos la nuestro amigo, el recibo interno ... que es lo que nos interesa listar en las vistas de 'Transferencias' y 'Cambios de Moneda'

**Comment by mauriciopasquier** [comment]
Está bien matus, pero no quiero que haya movimientos sin causa. Tenemos Efectivo (billetes), Transferencia (id de operación), ahora Cambio (?).., Retencion, Cheque..

**Comment by m4tu5** [comment]
Cambio y Transferencias de Cajas, para mi, son nombres que se les de a los recibos internos que agrupan movimientos de efectivo o transferencias bancarias. No son nuevas causas, en el sentido de que lo que esta cambiando de moneda o yendo de un lugar a otro es efectivo o dinero bancarizado ... si es confuso usar las mismas causas de Efectivo/Transferencia para estas operaciones porque fuese a ser confuso, entonces creamos unas nuevas

**Comment by mauriciopasquier** [comment]
No se si es confuso, sólo pensé que podíamos tener más especificidad en los movimientos. Si no hace falta, seguimos con Efectivo y Transferencia. Consulta:
- Se puede hacer una transferencia entre una caja de efectivo y una cuenta? Cómo se causifican esos movimientos?

**Comment by m4tu5** [comment]
Si se puede transferir desde una caja a una cuenta bancaria y viceversa
No se como se causifica ... queres hacer una causa general que sea 'movimientos internos' o algo parecido que nos sirva para cubrir tanto los movimientos entre cajas como los cambios de moneda?

**Comment by mauriciopasquier** [comment]
Operacion ?

**Comment by m4tu5** [comment]
'operacion' como nueva causa? si, me parece bien.

**Comment by mauriciopasquier** [comment]
ok
