### ISSUE TITLE
Movimientos Sobrepasan el saldo

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#125]
- Crear factura de cobro por 1000 ARS
- Crear recibo
- Añadir cobro en efectivo por 1000 ARS
- Error: Movimientos Sobrepasan el saldo
- Saldo informado: 0 ARS
- Importa informat: 1000 ARS
- En la base:
  *\* Factura
  *\* Recibo
  *\* Ningun movimiento

sin embargo pude cobrar la misma factura en dos cobros en efectivo de 500 ARS

**Comment by fauno** [comment]
además se crean unos recibos vacíos a los que después no se les asocian movimientos

**Comment by fauno** [comment]
parece que es solo cuando creo el movimiento desde la creacion de recibo, si edito uno anda bien

**Comment by m4tu5** [comment]
el recibo vacio creo que es una jugarreta de @mauriciopasquier para poder almacenar los medios de pago que se van creando, en un recibo nuevo que aun no existe.

**Comment by mauriciopasquier** [comment]
Les tengo dicho, les tengo dicho! Los cobros no están andando todavía

**Comment by fauno** [comment]
entonces ya se arreglo?

**Comment by mauriciopasquier** [comment]
vemos cuando arregle #135

**Comment by mauriciopasquier** [comment]
ah, no se si tenía algo que ver.. me perdieron tantos issues y problemas falsos
