### ISSUE TITLE
Estados para las retenciones

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#134]
Los 3 que hablamos con @m4tu5 (no me acuerdo, pero están en el código)

**Comment by m4tu5** [comment]
- emitida
- aplicada
- pagada

el truco con estos es que pueden coexistir.
- la retención siempre se 'emite' primero
- luego en algún momento se 'aplica' y pasa a formar parte de un recibo de pago
- en otro momento diferente, a los 7 o 10 dias de haberse emitodo, vence y hay que 'pagarla'

**Comment by mauriciopasquier** [comment]
una misma cosa no puede estar en dos estados simultaneamente!

```
                        usar
                  /---------------
         usar     v     pagar     \
emitida -----> aplicada ------> pagada
    |             |    pagar      ^^
    |    pagar    \--------------/ |
    \-----------------------------/
```

está faltando algo?

**Comment by m4tu5** [comment]
tal vez si pueda estar en dos ... o tenemos que agregar un estado mas para las retenciones que esten aplicada&pagada

estados posibles:
- emitida
- aplicada (implica emitida)
- pagada (implica emitida)
- aplicada y pagada (implica emitida)

**Comment by mauriciopasquier** [comment]
On Sun, Apr 06, 2014 at 10:28:33AM -0700, m4tu5 wrote:

> tal vez si pueda estar en dos ... o tenemos que agregar un estado mas para las retenciones que esten aplicada&pagada
> 
> estados posibles:
> - emitida
> - aplicada (implica emitida)
> - pagada (implica emitida)
> - aplicada y pagada (implica emitida)

liquidada! (o ajusticiada :P)

##

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> > - aplicada y pagada (implica emitida)
> 
> liquidada! (o ajusticiada :P)

faunizada?

## 

http://librevpn.org.ar

**Comment by mauriciopasquier** [comment]
Le voy a poner `cerrada` y chau

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> Le voy a poner `cerrada` y chau

yo pago mis impuestos!!

## 

http://vqfe4xmhxzi7w2uv.onion
