### ISSUE TITLE
listar cajas con saldo 0 en selector y permitir depositar

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#138]
en los medios de pago de efectivo no se listan las cajas con saldo 0, con lo que no se puede depositar ningún pago para empezar a llenarla.

para el pago con transferencia, la cuenta si aparece en el selector, pero no se ejecuta el deposito.

**Comment by m4tu5** [comment]
se tiene que poder emitir cheques propios en todo momento, y esa chequera va a tener siempre saldo negativo.

**Comment by mauriciopasquier** [comment]
On Sun, Apr 06, 2014 at 01:46:35AM -0700, m4tu5 wrote:

> en los medios de pago de efectivo no se listan las cajas con saldo 0, con lo
> que no se puede depositar ningún pago para empezar a llenarla.
> 
> para el pago con transferencia, la cuenta si aparece en el selector, pero no
> se ejecuta el deposito.

unifico que no salgan las cuentas... esto es pagos no cobros, no podés
depositar.

Por cierto, aparte de cambiar y transferir, para cada caja, podemos hacer un
"depositar tanto" arbitrario (ya está hecho en caja, es sólo agregar un método
en Operación y hacer la vista). Te va?

##

**Comment by m4tu5** [comment]
era tarde y ya no escribia bien :)

para pagos, se tiene que poder emitir un cheque propio sin importar el saldo de la chequera, que insisto, va a ser siempre negativo o cero ... esto mismo pasará con las chequeras de retenciones

el resto, efectivo, banco, cheques de 3ro esta bien no mostrarlos si no tienen saldo

para cobro, hay que mostrar todas las cuentas disponibles (y correctamente asociadas por tipo de factura, etc.) sin importar el saldo que tengan

**Comment by mauriciopasquier** [comment]
On Sun, Apr 06, 2014 at 09:33:31AM -0700, m4tu5 wrote:

> era tarde y ya no escribia bien :)
> 
> para pagos, se tiene que poder emitir un cheque propio sin importar el saldo

ok, reviso esto

> de la chequera, que insisto, va a ser siempre negativo o cero ... esto mismo
> pasará con las chequeras de retenciones

chequera de retención? eso es interno, según el tipo.. el usuario nunca lo
elige.

> el resto, efectivo, banco, cheques de 3ro esta bien no mostrarlos si no
> tienen saldo
> 
> para cobro, hay que mostrar todas las cuentas disponibles (y correctamente
> asociadas por tipo de factura, etc.) sin importar el saldo que tengan

"La comida va aquí" - Claaaro que sí!

##

**Comment by mauriciopasquier** [comment]
ya está en develop :sheep:

**Comment by mauriciopasquier** [comment]
Cierro, si hace falta desde la gui depositar y extraer sin facturas armemos otro issue

**Comment by m4tu5** [comment]
On 04/06/2014 09:21 PM, Mauricio Pasquier Juan wrote:

> Cierro, si hace falta desde la gui depositar y extraer sin facturas
> armemos otro issue

no, no vamos a dejar que depositen ni extraigan sin facturas ... mejor
crean tipos de facturas nuevos para hacer estas movidas

**Comment by mauriciopasquier** [comment]
On Sun, Apr 06, 2014 at 05:45:36PM -0700, m4tu5 wrote:

> On 04/06/2014 09:21 PM, Mauricio Pasquier Juan wrote:
> 
> > Cierro, si hace falta desde la gui depositar y extraer sin facturas
> > armemos otro issue
> 
> no, no vamos a dejar que depositen ni extraigan sin facturas ... mejor
> crean tipos de facturas nuevos para hacer estas movidas

o sea que no pueden arrancar el sistema diciendo "tengo tanto en la caja"?

##

**Comment by m4tu5** [comment]
On 04/06/2014 09:49 PM, Mauricio Pasquier Juan wrote:

> o sea que no pueden arrancar el sistema diciendo "tengo tanto en la caja"?
> 
> si, pero no asi a manopla ... se crea un tercero que sea 'Socios CP' y
> con eso se hace una factura de cobro por el saldo que tenga la caja al
> momento de arrancar, y que ya que estamos le ponemos 'Saldos Iniciales'
> en la descripcion
> :)

o al menos eso esoty creyendo que voy a hacer mañana
