### ISSUE TITLE
no permitir crear un recibo si no tiene movimientos asociados

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#139]
ahora se pueden crear y guardar recibos, que no tienen movimientos asociados, y por ende saldo cero.

hay que tener cuidado si se bloquea el saldo == 0 porque los recibos internos todos tienen justamente eso, saldo = 0

**Comment by mauriciopasquier** [comment]
Por cómo está el código ahora, se crea primero el recibo y después se le agrega el pago. Habría que rearmar esta lógica... está medio complicado hoy

**Comment by m4tu5** [comment]
ok, no es para hoy ... yo creo que podemos agregar un chequeo al submitir un recibo para cambio o creacion que cuente los movimientos asociados, y si fuese igual a 0, entonces que borre el recibo

**Comment by mauriciopasquier** [comment]
Lo que digo es que el funcionamiento actual depende de que el recibo se pueda guardar sin movimientos. Pero es interno.. tal vez se pueda validar a mano dentro del controlador, si mandás un recibo sin causas.

**Comment by mauriciopasquier** [comment]
Alguien quiere hacer esto?

```
Tal vez se pueda validar a mano dentro del controlador, si mandás un recibo sin causas.
```

O sea si la causa es nula o no es válida, creo que le podemos agregar un error al recibo, así a mano y después (el año que viene) rehacer la lógica

**Comment by sudoaza** [comment]
Arreglado en el merge de la fe.
