### ISSUE TITLE
falta boton para crear transferencias y cambios de moneda

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#147]
lo podemos poner en el listado de cajas o dentro de la vista de la caja ... creo que @mauriciopasquier dijo que preparo el formulario para que no pregunta la caja de origen ... si fuese el caso, habrá que meter el botón adentro de la vista detallada

**Comment by mauriciopasquier** [comment]
o en el index para cada caja:

```
cambiar_caja_path(caja)
transferir_caja_path(caja)
```

**Comment by m4tu5** [comment]
solucionado en #163
