### ISSUE TITLE
retenciones - no guarda tipo al crearse, pero si al editar

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#150]
tampoco creo ningun movimiento, y por endo en las cajas de retenciones no se descontó nada.

**Comment by mauriciopasquier** [comment]
te referís a la situacion? al cargarla? le estás pasando bien los params?

**Comment by mauriciopasquier** [comment]
Era eso:

```
Unpermitted parameters: situacion
```

agregá la situación en el retencion_params

**Comment by m4tu5** [comment]
ya esta agregada desde hace un tiempo, y por eso creo que cambia el valor cuando la editas ... yo habia luchado con este issue antes.

no se porque, no toma bien la situacion del selector en la retencion nueva ... tendra que ver con como se pasa la situacion al nuevo registro?

**Comment by mauriciopasquier** [comment]
qué manera de ignorar lo que digo eh.. ahí lo arreglé

**Comment by m4tu5** [comment]
pero ya esta en el controlador dentro de retencion_params ... no te estoy ignorando :p

**Comment by mauriciopasquier** [comment]
On Sun, Apr 06, 2014 at 07:36:06PM -0700, m4tu5 wrote:

> pero ya esta en el controlador dentro de retencion_params ... no te estoy ignorando :p

no estaba.. ahora lo puse. Mirá el pull

##
