### ISSUE TITLE
retenciones y cuentas -- flujo de dineros

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#152]
me parece que hay algunos errores en el modelo
- al emitir una retención no se descuenta de la caja Retenciones (que es lo que debería pasar, dejando a la caja de retenciones con saldo negativo)
- al pagar la retencion, se debe transferir dinero de una caja/banco a la cuenta de retenciones, lo que implica 2 movimientos
  -1- quita el dinero de la caja o banco emisor, disminuyendo su saldo
  -2- deposita el dinero en la cuenta de retenciones, volviendo el saldo a 0. 
  esto tampoco parece estar pasando bien.

**Comment by mauriciopasquier** [comment]
1) sólo pasa cuando se aplica en el pago
2) sí está pasando con el método retención.pagar, aunque no se cómo es desde la gui

**Comment by m4tu5** [comment]
-ojo con eso, al crear la retencion, aunque no este aplicada, hay que bajar el saldo en la caja de retenciones, sin importar si esta aplicada o no, la deuda con el gobierno la tenes por haberla emitido.
-al aplicarla, no pasa nada en cuestion de movimiento de saldos
-al pagarla ya sabemos.

**Comment by mauriciopasquier** [comment]
Tengo dos soluciones posibles:

1) crear el movimiento de extracción al momento de crear la retención y dejarlo sin recibo (hay que dejar de validar que haya recibos en los movimientos)
2) crear el recibo para la factura y que aparezca en la lista de recibos, con importe = monto de la retención. Tendrán que recordar usarlo la próxima vez, porque creo que no hay nada que nos permita marcar un recibo como "lo creé pero no se lo hemos dado a nadie"

**Comment by mauriciopasquier** [comment]
Se me ocurre una tercera linda:

3) como la 1 pero dejando un recibo interno hasta que se use como pago, momento en el cual se reemplaza por el definitivo.

**Comment by m4tu5** [comment]
yo voy por la 3-bis ... creas un recibo de una nueva situacion ... 'temporal'
cuando apretas nuevo recibo en una factura, si tiene un recibo 'temporal' te lo edita y al guardar el recibo pasa la retencion a aplicada ... si no hay recibo temporal, se crea uno nuevo

**Comment by mauriciopasquier** [comment]
On Sun, Apr 06, 2014 at 09:08:57PM -0700, m4tu5 wrote:

> yo voy por la 3-bis ... creas un recibo de una nueva situacion ... 'temporal'
> cuando apretas nuevo recibo en una factura, si tiene un recibo 'temporal' te lo edita y al guardar el recibo pasa la retencion a aplicada ... si no hay recibo temporal, se crea uno nuevo

ok, más simple

##
