### ISSUE TITLE
medios de pago borran la fecha del recibo nuevo al agregarse

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#154]
al agregar un nuevo medio de pago a un recibo, este se recarga y pierde la fecha que se haya seleccionado (sungo que esto pasa porque el recibo no esta guardado aun).

**Comment by fauno** [comment]
si es tanto bardo esto por que no sacamos que se pueden crear pagos sin un recibo ya creado y ya

**Comment by m4tu5** [comment]
say what ???? no entendi nada ... el tema es en un recibo nuevo. se selecciona la fecha, se agrega un medio de pago (efectivo, por ej), al confirmar el pago en efectivo, se recarga el recibo y pierde la fecha
tal vez podamos forzar a que el recibo se grabe antes de que se agregue un nuevo medio de pago?

**Comment by mauriciopasquier** [comment]
che, soy yo o hay 2 issues por problema?

**Comment by mauriciopasquier** [comment]
> tal vez podamos forzar a que el recibo se grabe antes de que se agregue un nuevo medio de pago?

es exactamente lo que pasa:

```
def create
  ...
  if @recibo.save && @recibo.pagar_con(@causa)

def update
  ...
  if @recibo.update(recibo_params) && @recibo.pagar_con(@causa)
```

**Comment by m4tu5** [comment]
mira, acabo de probar otra vez y fue bien ... no se ...ignoralo
