### ISSUE TITLE
al crear cheque propio, no se guarda el banco

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#155]

**Comment by mauriciopasquier** [comment]
-1, esto está mal y está hecho en el modelo bien

**Comment by m4tu5** [comment]
fauno, no es el banco de la chequera, que se crea automaticamente y no tiene banco asignado, sino el banco de la caja(banco) que elijas cuando emitis el cheque

**Comment by fauno** [comment]
y se setea o no al final

**Comment by mauriciopasquier** [comment]
@m4tu5 admitió haber estado probando con una cuenta sin banco..
