### ISSUE TITLE
algunos temas con los cobros

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#167]
Factura en ARS
- permite cobrar en USD, pero no realiza bien la matematica de los depósitos. tendría que haber cobrado una deuda en ARS con billetes de USD, y termine con todas las cajas de USD en 0 y con movimientos que no correspondian en ARS ... revisar bien esto.

Factura en USD
- no me permite cobrar de ninguna forma en USD, da error de moneda.
- permite digitar un cheque de terceros, asi como una transferencia bancaria, en una factura en USD ... ninguna de estas formas de pago es viable en este caso.

**Comment by mauriciopasquier** [comment]
Lo de las monedas es de nuevo por el js de fauno :(

Subo una rama fix-cobros para que me lleguen los params que necesito y que @fauno arregle el js sin cambiar los params.

**Comment by mauriciopasquier** [comment]
Para debuggear, en el controlador de recibos, causa_params tiene que tener:

monto, monto_moneda (que son los que elegimos) y monto_aceptado_moneda que SIEMPRE va a ser el mismo que la factura

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> Lo de las monedas es de nuevo por el js de fauno :(
> 
> Subo una rama fix-cobros para que me lleguen los params que necesito y
> que @fauno arregle el js sin cambiar los params.

el js no toca la moneda, solo el importe y eso ya lo arregle

## 

.oÓ)

**Comment by mauriciopasquier** [comment]
On Mon, Apr 07, 2014 at 04:54:54AM -0700, fauno wrote:

> Mauricio Pasquier Juan notifications@github.com writes:
> 
> > Lo de las monedas es de nuevo por el js de fauno :(
> > 
> > Subo una rama fix-cobros para que me lleguen los params que necesito y
> > que @fauno arregle el js sin cambiar los params.
> 
> el js no toca la moneda, solo el importe y eso ya lo arregle

sigue habiendo cosas que disparan con el cambio aceptado, y además habías
pueso el `nombre` en el select.. fijate porque antes andaba y es que no le
están llegando los campos

##

**Comment by fauno** [comment]
ahi cambié el id que busca el js, pero el resto me anda joya

**Comment by mauriciopasquier** [comment]
joya también acá, ya mergeé
