### ISSUE TITLE
ramas que podar

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#169]
quedan estas sin issue ni pull relacionado:

```
remotes/origin/feature/saldo-general
remotes/origin/feature/selector_de_cajas
remotes/origin/feature/validacion-factura
```

**Comment by fauno** [comment]
saldo-general es mia pero me parece que la adoptó @m4tu5?
selector_de_cajas es tuya
validacion-factura es cuando aza le agregó tercero a factura

**Comment by mauriciopasquier** [comment]
On Mon, Apr 07, 2014 at 06:23:57AM -0700, fauno wrote:

> selector_de_cajas es tuya

borrada

##

**Comment by m4tu5** [comment]
en saldo-general no estoy haciendo nada

validacion-factura, la borraria tambien ya que a aza le habíamos pedido que se ocupe de lo del 3ro en facturas (que ya esta hecho) y la factura ya valida los campos minimos requeridos

**Comment by mauriciopasquier** [comment]
Sólo quedaba feature/saldo-general y no tenía commits, la borré.
