### ISSUE TITLE
pago de facturas en otra moneda

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#171]
estamos cruzando los signos en estas operaciones, si cobramos una factura en ARS por 20.000 con USD 2.000, sucede lo siguiente,

1) se crea un movimiento Efectivo por + 20.000 ARS en la caja, vinculado al recibo de cobro
2) se crean 2 movimientos Operacion, uno por +20.000 ARS y otro por - 2.000 ARS en la caja

esto nos deja, la caja con ARS 20.000 + 20.000 - 2.000 = 38.000 y USD 0, cuando en realidad tendríamos que tener ARS 20.000 - 20.000 = 0 y USD 2.000

el paso 2) es el que esta fallando, por un lado, los signos están cruzados y los 20.000 deberían salir y los 2.000 entrar (al reves que ahora), y por otro, los 2.000 son USD y los esta tomando como ARS

**Comment by m4tu5** [comment]
si la factura es en USD y deseamos ingresar el cobro en ARS, el problema es solo el de los signos de los movimientos de la operación de cambio de moneda, ya que las monedas las gestiona bien.

creo que lo que pasa, es que está considerando siempre que el Monto Equivalente es en ARS, cuando en realidad esta en @factura.moneda, que puede ser ARS u otra.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> estamos cruzando los signos en estas operaciones, si pagamos una
> factura en ARS por 20.000 con USD 2.000, sucede lo siguiente,
> 
> 1) se crea un movimiento Efectivo por + 20.000 ARS en la caja,
> vinculado al recibo de cobro 2) se crean 2 movimientos Operacion, uno
> por +20.000 ARS y otro por - 2.000 ARS en la caja
> 
> esto nos deja, la caja con ARS 20.000 + 20.000 - 2.000 = 38.000 y USD
> 0, cuando en realidad tendríamos que tener ARS 20.000 - 20.000 = 0 y
> USD 2.000
> 
> el paso 2) es el que esta fallando, por un lado, los signos están
> cruzados y los 20.000 deberían salir y los 2.000 entrar (al reves que
> ahora), y por otro, los 2.000 son USD y los esta tomando como ARS

estas en develop?

## 

 D

**Comment by mauriciopasquier** [comment]
On Mon, Apr 07, 2014 at 06:58:50AM -0700, m4tu5 wrote:

> estamos cruzando los signos en estas operaciones, si pagamos una factura en ARS por 20.000 con USD 2.000, sucede lo siguiente,
> 
> 1) se crea un movimiento Efectivo por + 20.000 ARS en la caja, vinculado al recibo de cobro
> 2) se crean 2 movimientos Operacion, uno por +20.000 ARS y otro por - 2.000 ARS en la caja

acá quisiste decir "y otro por - 2.000 USD" o realmente se están creando en
ARS?

> esto nos deja, la caja con ARS 20.000 + 20.000 - 2.000 = 38.000 y USD 0, cuando en realidad tendríamos que tener ARS 20.000 - 20.000 = 0 y USD 2.000
> 
> el paso 2) es el que esta fallando, por un lado, los signos están cruzados y los 20.000 deberían salir y los 2.000 entrar (al reves que ahora), y por otro, los 2.000 son USD y los esta tomando como ARS

a ver:

  si la factura es en pesos
  y pagamos 20.000 pesos con 2.000 dólares
    necesitamos convertir 2.000 dólares a 20.000 pesos
      esto es un cambio de moneda como los demás
    queda una salida de 2.000 dólares y una entrada de 20.000 pesos en la caja
  ahora que tenemos esos 20.000 pesos, pagamos con eso el recibo/factura

entonces: en el paso 2 los signos no están cruzados, están bien (como yo
entiendo la operatoria). No entiendo por qué decís que los 2.000 entran, si los
cambio a pesos para pagar una factura en pesos. Están saliendo, como en
cualquier cambio.

##

**Comment by m4tu5** [comment]
si, estoy en develop

esta mal escrito el issue, es cobro y no pago ... y los signos estan cruzados, mirenlo sino.

voy a ver que pasa con los pagos ... tal vez en ese escenariofuncione bien ... ahora reporto

**Comment by mauriciopasquier** [comment]
te digo que no están cruzados en tu descripción :|

o sea no estamos de acuerdo con cómo funciona el sistema..

**Comment by m4tu5** [comment]
si que estamos de acuerdo en como funciona el sistema mpj, se esta ingresando mal el cambio de moneda (con signos cruzados) ... y cuando queremos pagar USD con ARS, además, no se identifica bien la moneda que realmente se recibe (USD) y se asume ARS

**Comment by m4tu5** [comment]
ahi edite la descripcion del problema para especificar que hablo de cobros y no pagos ... perdon por el typo

**Comment by m4tu5** [comment]
captura de pantalla
http://archivos.hackcoop.com.ar/public.php?service=files&t=729diuo84z2n9kjbgi1raiiolfki8mc2
