### ISSUE TITLE
cobros -- flujo de dineros

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#172]
1. problemas al pagar en otra moneda, ver #171 
2. permite ingresar pagos en USD de tipo transferencia bancaria, y empieza a acumular USD en las cuentas. Esto no debería ser posible, ya que las cuentas operan solo en ARS

**Comment by mauriciopasquier** [comment]
No da encarar 2. ahora, lo vemos después

**Comment by fauno** [comment]
que onda con este?

**Comment by mauriciopasquier** [comment]
Estaba haciendo los tests para el cobro y me acordé de esto y de que @m4tu5 decía que se estaba haciendo al revés el depósito. Para asegurarnos, esto es lo que pasa actualmente:
1. tengo un recibo que quiero cobrar (100 pesos)
2. me ofrecen 30 dólares y los acepto porque me conviene
3. selecciono una caja donde guardar los 30 dólares
4. en esa caja cambio 100 pesos por 30 dólares (o sea extraigo 100 pesos y deposito 30 dólares)
5. uso esos 100 pesos que extraje y los asocio al recibo en pesos como si hubiera recibido 100 pesos
6. deposito 100 pesos en la misma caja (-100 + 100 = 0)
7. al final, tengo un recibo pagado en pesos y 20 dólares en la caja

Según entiendo esto está bien. El problema de este issue es que este comportamiento está bien para las cajas (de efectivo) pero no para las cuentas (de banco). No quiero ser pesado, pero se acuerdan que al principio había un modelo para cajas y otro para cuentas?

**Comment by fauno** [comment]
te encanutaste 10usd!!!

y despues en la factura queda saldo - 100 pesos?

**Comment by mauriciopasquier** [comment]
claro, si cobraste un recibo de 100 pesos

**Comment by m4tu5** [comment]
me confundo en los pasos 5 / 6 y no se si entiendo lo que se propone.
como yo lo entiendo, hay un solo paso, 5&6, que consiste en agregar el cobro en efectivo de 100 pesos en el recibo de cobro, lo que genera un movimiento de entra de 100 pesos en la caja (que es la misma de la cual salieron antes los 100 pesos para cambiarse por 30 usd)

esto, hace el juego de que entran 100 pesos por el cobro, salen 100 pesos para el cambio y entran 30usd como resultado del cambio

**Comment by mauriciopasquier** [comment]
@m4tu5 sí, eso. El paso 5 es agregar el cobro al recibo nomás. El 6 sería concretar el cobro con un depósito. Van juntos pero están programados por separado (?)

**Comment by mauriciopasquier** [comment]
O sea, el orden que yo escribí es como está programado, pero el resultado es el mismo

**Comment by m4tu5** [comment]
no me entero del todo, o tal vez sea semantica, no se.

el paso 5 habla de asociar los 100 pesos que salieron de la caja para ser cambiados por 30USD con el 'recibo en pesos' ... y aca es donde me pierdo

para mi, los 100 pesos que _salen_ de la caja para ser cambiados por los 30 USD solo se asocian con el _recibo interno_ de cambio de moneda

hay otro movimiento de 100 pesos que _entran_ a la caja que se asocia con el _recibo de cobro_, que compensa la salida anterior de 100 pesos y deja el saldo en pesos de la caja inalterado

**Comment by mauriciopasquier** [comment]
está bien @m4tu5, son otros 100 pesos pero son iguales
