### ISSUE TITLE
selector de cheques de 3ro/retenciones muestra causas ya usadas para pagar

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#174]
si uso un cheque de 3ros en un recibo, su estado debe cambiar a 'pasamanos' y ya no debe aparecer como una opción de pago en el selector de cheques.

esto no solo pasa durante la creación de un recibo, sino que al crear un segundo recibo, el cheque que se uso en el primero sigue estando disponible ... algun problema con el cambio de estado?

lo mismo pasa con las retenciones ya aplicadas, se siguen listando y se sigue puediendo usarlas para pagar

**Comment by fauno** [comment]
taria bueno saber la url asi no me tengo que poner a buscar
