### ISSUE TITLE
cheque/show muestra el banco en el campo beneficiario y no muestra nada en banco

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#175]

**Comment by fauno** [comment]
ahi va

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lainventoria/cp/issues/175

no solo eso sino que metieon mano en las rutas y no anda nada ahora

## 

http://hackcoop.com.ar

**Comment by fauno** [comment]
el problema es que la caja no tiene banco y el cheque propio si o si adopta ese

**Comment by mauriciopasquier** [comment]
On Mon, Apr 07, 2014 at 08:31:30AM -0700, fauno wrote:

> el problema es que la caja no tiene banco y el cheque propio si o si adopta ese

la caja tiene que tener banco, hay que validar eso... ahh, la creamos
automáticamente :P

##

**Comment by m4tu5** [comment]
con respecto a las rutas, ya lo hablamos, yo hice unos cambios que cagaron algo que no se suponia y es cuestion de mover un end para arriba en config/routes para volver todo a la normalidad

con respecto a la creación automatica de la caja, si, se crea sin banco que hay que acordarse de especificar a mano

**Comment by fauno** [comment]
le puse un placeholder

**Comment by m4tu5** [comment]
creo que el problema no pasa por ahi, sino que se esta guardando mal el cheque, porque aparece el nombre del banco en Beneficiario y en banco no aparece nada ... cuando banco si hay ... sera que se estan cruzando los parametros al crear el cheque en medios_de_pago?

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> creo que el problema no pasa por ahi, sino que se esta guardando mal
> el cheque, porque aparece el nombre del banco en Beneficiario y en
> banco no aparece nada ... cuando banco si hay ... sera que se estan
> cruzando los parametros al crear el cheque en medios_de_pago?

estas mirando cheque/show o recibo/edit?

## 

http://partidopirata.com.ar

**Comment by fauno** [comment]
acabo de emitir un cheque desde un recibo y el nombre del banco se puso bien

**Comment by m4tu5** [comment]
es en cheque/show

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> es en cheque/show

aca sale bien che

## 

http://endefensadelsl.org

**Comment by m4tu5** [comment]
aca no ... agrego un cheque de 3ros desde un pago, y cuando lo voy a ver, muestra el banco que ingrese en el lugar de Beneficiario, y en el lugar de banco, tu placeholder

Por la consola veo que el cheque esta mal generado, ya que se guarda el nombre del banco en el campo beneficiario, no se guarda el beneficiario que ingresé en ningun sitio y en el campo banco no se guarda nada.
