### ISSUE TITLE
Convertir Factura.saldo en atributo

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#18]
Vamos a tener que empezar a filtrar por saldo para saber cuáles facturas ya están canceladas y si mantenemos el saldo como un método mostrar una lista de facturas se va a convertir en F^2 consultas.

Mejor guardarlo como atributo no?  Se calcularía cada vez que se inserta o actualiza un recibo.

**Comment by mauriciopasquier** [comment]
On Thu, Feb 06, 2014 at 04:42:31AM -0800, fauno wrote:

> Vamos a tener que empezar a filtrar por saldo para saber cuáles facturas ya están canceladas y si mantenemos el saldo como un método mostrar una lista de facturas se va a convertir en F^2 consultas.
> 
> Mejor guardarlo como atributo no?  Se calcularía cada vez que se inserta o actualiza un recibo.

o usamos una máquina de estado con un estado "cancelada"

##

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> o usamos una máquina de estado con un estado "cancelada"

pero está bueno saber rápidamente el saldo, por ejemplo para saber
cuanto se adeuda globalmente

## 

http://selfdandi.com.ar

**Comment by mauriciopasquier** [comment]
en todo caso lo agregaría cuando haga falta

**Comment by fauno** [comment]
lo estaba necesitando @m4tu5 para las vistas :B

## 

http://partidopirata.com.ar

**Comment by mauriciopasquier** [comment]
On Sat, Feb 08, 2014 at 01:20:27PM -0800, fauno wrote:

> lo estaba necesitando @m4tu5 para las vistas :B

no, no vi que estuviera necesitando convertirlo en un atributo. Sigo pensando
que es más útil una máquina de estados

##

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> On Sat, Feb 08, 2014 at 01:20:27PM -0800, fauno wrote:
> 
> > lo estaba necesitando @m4tu5 para las vistas :B
> 
> no, no vi que estuviera necesitando convertirlo en un atributo. Sigo pensando
> que es más útil una máquina de estados

pero el saldo total lo vamos a necesitar, por que voy a programar dos
veces...  quiero una segunda opinion!!

## 

http://partidopirata.com.ar

**Comment by mauriciopasquier** [comment]
A ver. No hace falta que programes dos veces. La primera no programás y listo.

> Vamos a tener que empezar a filtrar por saldo para saber cuáles facturas ya están canceladas

para eso lo mejor es máquina de estados, además te sirve para otras cosas y no tenés que acordarte vos de cancelarla ni de sacar cuentas de saldo para ver si está cancelada.

> y si mantenemos el saldo como un método mostrar una lista de facturas se va a convertir en F^2 consultas.

eager loading, y listo. No sobreprogramemos si no hace falta!

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> A ver. No hace falta que programes dos veces. La primera no programás
> y listo.

@m4tu5 me pidió listar las facturas sin cancelar asi que si necesito
saber qué programo.

> > Vamos a tener que empezar a filtrar por saldo para saber cuáles
> > facturas ya están canceladas
> 
> para eso lo mejor es máquina de estados, además te sirve para otras
> cosas y no tenés que acordarte vos de cancelarla ni de sacar cuentas
> de saldo para ver si está cancelada.

es lo mismo que guardar el valor del saldo (0 == cancelada) y de yapa
poder saber el saldo total sin esfuerzo extra (es un sum(saldo) en sql)

> > y si mantenemos el saldo como un método mostrar una lista de facturas
> > se va a convertir en F^2 consultas.
> 
> eager loading, y listo. No sobreprogramemos si no hace falta!

no es sobreprogramar si es para ahorrarme laburo luego

## 

}(:=

**Comment by mauriciopasquier** [comment]
do what you want 'cause a pirate is free?

**Comment by m4tu5** [comment]
no se lo que es una 'maquina de estados' para poder diferenciar entre una opcion y la otra.

lo que si les digo es que el saldo, o mas bien si una factura esta totalmente pagada/cobrada o no, es algo que se va a usar todo el tiempo, con lo que estaria bien si no tenemos que recalcular el saldo de cada factura cada vez que se pida un listado ya que con el tiempo esto se va a volver pesado y se va a recalcular lo mismo 1000 veces
