### ISSUE TITLE
cp.lainventoria.com.ar

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#181]
No permite crear facturas, no se que esta fallando. No da mensajes de error detallados.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> No permite crear facturas, no se que esta fallando. No da mensajes de
> error detallados.

aca me anduvo...

http://cp.lainventoria.com.ar/obras/1/facturas/pagos

## 

P)

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> No permite crear facturas, no se que esta fallando. No da mensajes de error detallados.

me sale esto en el log

F, [2014-04-07T18:59:48.110334 #1761] FATAL -- : 
ArgumentError (argument out of range):
  app/controllers/facturas_controller.rb:46:in `create'

pero creé la factura con los mismos params sin drama

http://cp.lainventoria.com.ar/obras/1/facturas/cobros

## 

http://wiki.hackcoop.com.ar

**Comment by m4tu5** [comment]
en este momento se pueden crear facturas, cierro
