### ISSUE TITLE
aceptar un cheque de 3ros para el pago de varias facturas

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#187]
a veces, un 3ro paga muchas facturas (o el pendiente de una y la siguiente) con un solo cheque

**Comment by fauno** [comment]
y que onda generamos varios subcheques?

**Comment by m4tu5** [comment]
era o bien eso o bien asociar al cheque a varias facturas diferenciando de alguna forma cuanto del monto del cheque se aplica a cada una.

podria ser algo como:
1. se aplica un cheque de 3ro al pago de una factura existente
2. si el monto del cheque es mayor al saldo de la factura, el sistema pregunta a que otra factura se desea aplicar el saldo del cheque (para lo que habría que presentar un desplegable con las facturas abiertas)
3. una vez seleccionada la segunda factura, se crea un recibo de pago para esta factura por el monto menor entre el saldo del cheque y el saldo de la factura
4. si el saldo del cheque excede al saldo de la segunda factura, entonce volver al punto 2
5. se sale del loop cuando el saldo del cheque de 3ro sea 0

**Comment by m4tu5** [comment]
era o bien eso o bien asociar al cheque a varias facturas diferenciando de alguna forma cuanto del monto del cheque se aplica a cada una.

podria ser algo como:
1. se aplica un cheque de 3ro al pago de una factura existente
2. si el monto del cheque es mayor al saldo de la factura, el sistema pregunta a que otra factura se desea aplicar el saldo del cheque (para lo que habría que presentar un desplegable con las facturas abiertas)
3. una vez seleccionada la segunda factura, se crea un recibo de pago para esta factura por el monto menor entre el saldo del cheque y el saldo de la factura
4. si el saldo del cheque excede al saldo de la segunda factura, entonce volver al punto 2
5. se sale del loop cuando el saldo del cheque de 3ro sea 0

**Comment by fauno** [comment]
pero el tercero tiene que ser siempre igual a menos que puedas romper el cheque real en cachitos :P

**Comment by m4tu5** [comment]
me parece que confundis el tercero con el 'beneficiario' del cheque, ese es el que esta en la causa cheque.

el tercero para el sistema es quien nos da y quien recibe el cheque

**Comment by sudoaza** [comment]
me parece que algo generico para agrupar movimientos va a ser necesario a futuro. 

un cheque podria depositarse en una cuenta y de esa hacer todos los pagos, relacionar todos esos movimientos al cheque y si rebota damos marcha atras a todos esos pagos.
