### ISSUE TITLE
Semantica

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#192]
Cambios a texto por defecto
- 'Caja de Ahorro'  --> 'Cta. Corriente'
- 'X' por 'B', en descriptivos de cajas y cuentas para facturas que no validen
- 'Chequera' --> 'Chequera de 3ros'

**Comment by mauriciopasquier** [comment]
Aprovechamos para armarlo como configuración de deployment?

**Comment by m4tu5** [comment]
Estoy mirando esto, y ya tenemos el modelo desdoblado ... las cajas se diferencian unas de otra por situacion, que puede ser efectivo, banco o chequera ... lo que llamamos tipo en realidad es el nombre y no se esta usando para establecer vínculos ni en la lógica

**Comment by mauriciopasquier** [comment]
On Thu, Sep 18, 2014 at 07:37:08AM -0700, m4tu5 wrote:

> Estoy mirando esto, y ya tenemos el modelo desdoblado ... las cajas se
> diferencian unas de otra por situacion, que puede ser efectivo, banco o
> chequera ... lo que llamamos tipo en realidad es el nombre y no se esta
> usando para establecer vínculos ni en la lógica

ahh, buenísimo

##

**Comment by m4tu5** [comment]
/me se recuerda a si mismo que "nada es tan simple como parece inicialmente"
