### ISSUE TITLE
Desde chequera pierde caja en url al ir a cheque

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#195]
Desde chequera pierde caja en url al ir a cheque

**Comment by sudoaza** [comment]
@m4tu5 tenes los pasos para reproducir esto?

**Comment by m4tu5** [comment]
1. ir a 'Cajas y Bancos' --> 'Cajas y Cuentas'
2. seleccionar una chequera de las listadas (con saldo != 0 para que tenga cheques)
   
   esto nos lleva a la vista detallada de la chequera (URL de tipo `/cajas/#`)
3. clickear en un movimiento (link Cheque) para ver el detalle del cheque
   
   _aca es donde pierde `/cajas/#` de la URL_ 
4. clickear en boton 'Ver Chequera' nos muestra todos los cheques de la obra de todos los tipos, en lugar de mostrarnos solo los cheques de la caja elegida inicialmente.

**Comment by m4tu5** [comment]
creo que lo que lo que pasa es que esta complicada la navegación
- por un lado, podemos acceder a `obras/#/cheques/` para poder listar todos los cheques de una obra juntos
- por otro accedemos a `/obras/#/cajas/#/cheques` que nos lista los cheques de una chequera especifica

cuando vemos un cheque, siempre se muestra como `/obras/#/cajas/#/cheques/#` ... con lo que si queremos que el boton 'Ver Chequera' vuelva a la vista desde la que se accedió al cheque, vamos a tener que registrar algún tipo de parametro o similar ... ideas?

**Comment by mauriciopasquier** [comment]
'Ver chequera' o 'Volver'? No entiendo por qué 'Ver chequera' te llevaría a `obras/#/cheques`

**Comment by m4tu5** [comment]
creo que lo que hay que hacer es eliminar la ruta `obras/#/cheques`y forzar a que solo puedan verse los cheques a traves de su chequera, o sea `obras/#/cajas/#/cheque`

**Comment by sudoaza** [comment]
Tuve que pagar una factura con un cheque de tercero (oh my god) pero logre reproducirlo :P

**Comment by sudoaza** [comment]
@m4tu5 pregunta /cheques/# se usaria para editar/mostrar un cheque o nunca? lo mismo con /obras/#/cheques/# 

Si no se usan esas path nunca (osea todos los cheques van a tener obra y caja) los saco.

**Comment by sudoaza** [comment]
Tambien, ¿conviene usar la obra de la "causa" o de la "caja"?

**Comment by mauriciopasquier** [comment]
On Mon, Jun 02, 2014 at 04:37:06PM -0700, aza wrote:

> Tambien, ¿conviene usar la obra de la "causa" o de la "caja"?

`@obra` no está cargado siempre?

##

**Comment by sudoaza** [comment]
no sep...
en todos lados x lo que veo esta cheque.chequera.obra 
asi q estoy yendo con movimiento.caja.obra
