### ISSUE TITLE
Desde cheque Ver Chequera no funciona bien

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#196]
Desde cgeqye Ver Chequera no funciona bien

**Comment by sudoaza** [comment]
Arreglado. Ahora te lleva al listado de cheques segun la situacion propio/tercero.

**Comment by m4tu5** [comment]
Algunos de estos errores se dan solo cuando hay obra seleccionada en el filtro de la barra superior ... o cuando no hay nada seleccionado en este filtro ... lo que quiero decir es que para cerrar el issue, mejor probar los 2 escenarios (o mejor aun, escribir los tests correspondientes)

**Comment by mauriciopasquier** [comment]
+1 a escribir los tests

**Comment by sudoaza** [comment]
lo probe a mano y anda en las 2 situaciones (ya no es como decia en el comentario anterior sino que te lleva a la chequera en si)

No se como hacer los tests, creo que desde los test del controlador no seria... seria en test de integracion?

**Comment by sudoaza** [comment]
Esto esta mergeado faltan los tests.

**Comment by mauriciopasquier** [comment]
Lo reabriste para cerrarlo con los tests?

**Comment by sudoaza** [comment]
sip pero no se hacerlo el test xq no tengo ningun ejemplo, seria un test de integracion no?

tengo que entrar al sitio e ir a un cheque y luego seleccionar una obra e ir a un cheque, no es ni de modelo ni de controlador oh gran mpj

**Comment by sudoaza** [comment]
que haga los test magoya!
