### ISSUE TITLE
Funcionamiento retenciones???

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#198]
Funcionamiento retenciones??? per @m4tu5

**Comment by m4tu5** [comment]
hola, de que se trata esta pregunta?

**Comment by sudoaza** [comment]
no se, puede ser que estuviera en el papelito que me pasaste.

**Comment by fauno** [comment]
la cerramos?

**Comment by mauriciopasquier** [comment]
@m4tu5 funcionan o no funcionan como deberían?

**Comment by m4tu5** [comment]
esto esta cubierto en #281 #282 y #283
