### ISSUE TITLE
[UF] Cada obra tiene varias Unidades Funcionales

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#199]
que son las unidades vendibles a los clientes

**Comment by fauno** [comment]
le pongo tag gui a las cosas que se hacen desde la gui

**Comment by sudoaza** [comment]
Esta gran parte del GUI

Falta:
- Revisar bien como vemos las Unidades Funcionales en el SHOW de Obra
- Cambiar el campo Tipo por un select de entre los validos
- Validar Tipo y crear el test.

**Comment by sudoaza** [comment]
hecho todo salvo el show de obra que le falta un toque.
