### ISSUE TITLE
recibos

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#2]
@fauno esto es para distinguir si es nuestro o ajeno?

```
t.boolean  "emitido"
t.boolean  "recibido"
```

es posible que sea emitido y recibido a la vez??

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> @fauno esto es para distinguir si es nuestro o ajeno?
> 
> ```
> t.boolean  "emitido"
> t.boolean  "recibido"
> ```
> 
> es posible que sea emitido y recibido a la vez??

no, pero no entiendo por qué enum no está soportado :|

## 

:{

**Comment by mauriciopasquier** [comment]
y eso hace que dos booleans sean mejor que un string de tipo? O incluso subclases y STI, si van a tener diferente comportamiento según qué tipo sean, es lo mejor.

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> y eso hace que dos booleans sean mejor que un string de tipo? O
> incluso subclases y STI, si van a tener diferente comportamiento según
> qué tipo sean, es lo mejor.

es mejor porque sino no tendrías nada de qué quejarte :D

## 

}(:=

**Comment by fauno** [comment]
Nicolás Reynolds fauno@endefensadelsl.org writes:

> Mauricio Pasquier Juan notifications@github.com writes:
> 
> > y eso hace que dos booleans sean mejor que un string de tipo? O
> > incluso subclases y STI, si van a tener diferente comportamiento según
> > qué tipo sean, es lo mejor.
> 
> es mejor porque sino no tendrías nada de qué quejarte :D

lo puedo hacer con una validación?

http://guides.rubyonrails.org/active_record_validations.html#inclusion

## 

 D

**Comment by mauriciopasquier** [comment]
tengo esto en otro proyecto:

```
class Formato < ActiveRecord::Base
  TIPOS = [ 'Abierto', 'Cerrado' ]
  validates_inclusion_of :tipo, in: TIPOS
end
```

Así los tipos se pueden reutilizar en selects and stuff

**Comment by mauriciopasquier** [comment]
PD: Hay enums en rails 4.1 pero me da la sensación que esto es mucho más buscable, no miré la implementación todavía

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> tengo esto en otro proyecto:
> 
> ```
> class Formato < ActiveRecord::Base
>   TIPOS = [ 'Abierto', 'Cerrado' ]
>   validates_inclusion_of :tipo, in: TIPOS
> end
> ```
> 
> Así los tipos se pueden reutilizar en selects and stuff

fijate si te gusta feature/fix-booleans

## 

 D

**Comment by fauno** [comment]
Nicolás Reynolds fauno@endefensadelsl.org writes:

> Mauricio Pasquier Juan notifications@github.com writes:
> 
> > tengo esto en otro proyecto:
> > 
> > ```
> > class Formato < ActiveRecord::Base
> >   TIPOS = [ 'Abierto', 'Cerrado' ]
> >   validates_inclusion_of :tipo, in: TIPOS
> > end
> > ```
> > 
> > Así los tipos se pueden reutilizar en selects and stuff
> 
> fijate si te gusta feature/fix-booleans

no sé por qué no le puse (cobro pago)

## 

 D

**Comment by fauno** [comment]
Nicolás Reynolds fauno@endefensadelsl.org writes:

> Mauricio Pasquier Juan notifications@github.com writes:
> 
> > tengo esto en otro proyecto:
> > 
> > ```
> > class Formato < ActiveRecord::Base
> >   TIPOS = [ 'Abierto', 'Cerrado' ]
> >   validates_inclusion_of :tipo, in: TIPOS
> > end
> > ```
> > 
> > Así los tipos se pueden reutilizar en selects and stuff
> 
> fijate si te gusta feature/fix-booleans

pero la concha de dios se deshicieron tus cambios en schema :|

## 

 D

**Comment by m4tu5** [comment]
fauno, solucionaste finalmente issues #2 y #3 ... porque en el listado de issues siguen abiertos?

se cierran los issues al mergear o hay que cerrar a mano?

**Comment by mauriciopasquier** [comment]
Se pueden cerrar desde los mensajes de commit, pero no es automático. Lo lindo es que si se mencionan los issues salen acá en la página :)

Cierro los issues
