### ISSUE TITLE
[UF] hay diferentes tipos de UF

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#202]
departamento, cochera, baulera

**Comment by fauno** [comment]
da para una vista por tipo (o una animación del edificio vendiéndose!!) o con la descripcion basta?

**Comment by m4tu5** [comment]
uhm, estaría bien, en la vista, poder listarlas agrupadas por tipo ... tal vez llamando al mismo partial que hace la lista 3 veces, con diferentes parametros (esto esta implementado en la vista de cajas  para mostras cajas, cuentas y chequeras por separado usando un mismo partial)

**Comment by sudoaza** [comment]
tienen algun otro campo mas descriptivo ? 
me imagino los departamentos tendran pisos y letra, tiene algun "nombre" o "descripcion" ? 
Como lo distingo en un dropdown? 

lots of preguntas :)

ping @m4tu5

**Comment by fauno** [comment]
segun la administracion de mi edificio yo vivo en la unidad 57

**Comment by m4tu5** [comment]
@sudoaza , estaría bien tener un campo descriptivo para cada UF para poder poner el nombre coloquial ahí ... o sea, 9-D, 5-C, etc. ... si bien en el contrato legal creo que las UF se identifican como dice @fauno por numero, para la carga de UF en el CV estaría bien usar el nombre coloquial que es más fácil y descriptivo

**Comment by sudoaza** [comment]
esto esta falta la descripcion que esta en un enhacement x ahi
