### ISSUE TITLE
[UF] Las UF se venden a un Tercero mediante un Contrato de Venta

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#203]
El Tercero tiene que ser de tipo Cliente

**Comment by fauno** [comment]
es necesario distinguir entre proveedores y clientes? se puede actualizar dinámicamente que si un tercero proveedor compra una unidad funcional se convierte en cliente?

**Comment by m4tu5** [comment]
la unica razon para diferenciar unos de otros (clientes de proveedores) es para poder listarlos separadamente al rellenar facturas y contratos de venta

o sea, que el autocomplete solo muestre los valores encontrados dentro de la situacion que corresponda, pero no ambas.

para hacer lo que decís, habria que cambiar esto. 

prefiero dejarlo separado, me parece mas claro. 

El unico problema que se me ocurre es que cuando alguien, desde una nueva factura o contrato de venta, cree un nuevo tercero que no aparezca listado en el auto-complete, pero que ya exista en una situacion de tercero opuesta. acá saltaría error porque el cuit estaría repetido en Terceros, con lo que habría que contemplar en ese caso particular de pasar el tercero a situacion 'ambos' para poder usarlo en todos los formularios, en lugar de crearlo nuevo dado que ya existe

**Comment by mauriciopasquier** [comment]
> la unica razon para diferenciar unos de otros (clientes de proveedores) es para poder listarlos separadamente al rellenar facturas y contratos de venta

Posta es la única razón? Y para eso estamos complejizando tanto el modelo? Para mí, si es la única razón, no vale la pena la diferencia. Terceros para todos y todas! Total, cuando estás autocompletando, ya estás filtrando la mayoría de los datos que no te interesan

**Comment by m4tu5** [comment]
uhm, creo que si que es la unica razon, pero si creo que vale la pena diferenciar.

tal vez no para cp, que tiene pocas ventas por obra, pero para empresas con mayor numero de clientes o proveedores, que el listado sea conjunto (por mucho autocomplete que haiga) es medio bardo porque aparecen muchos resultados que por contexto no deberían aparecer y dan lugar a error humano (facturar a quien no corresponde)

prefiero dejarlo separado y meter un check que al crear un nuevo tercero en la factura/contrato, si el cuit ya existe en la tabla de 3ros, nos pregunte si le queremos cambiar el tipo al 3ro existente (o algo asi).
