### ISSUE TITLE
[UF] Los CV agrupan varias UF

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#204]
- Se realiza un único CV para todas las UF que compre el Tercero en un momento dado (o sea, es posible tener varias UF por CV)

**Comment by fauno** [comment]
el contrato es por obra o agrupa uf de varias?

**Comment by m4tu5** [comment]
Es un contrato por Obra.

La logica que soporta esto es que cada Obra es una Sociedad diferente, entonces, tiene que tener sus propios contratos.

**Comment by fauno** [comment]
ah, listo
