### ISSUE TITLE
[UF] Un Tercero puede tener varios CV

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#205]
Cuando ya se hizo un CV y el Tercero quiere comprar más UF se tienen que hacer nuevos CV

**Comment by fauno** [comment]
tiene relación con lo que pregunté en #204 ?

**Comment by m4tu5** [comment]
Esto no esta relacionado con #204 

En este caso, si el Tercero quiere comprar mas UF en la misma Obra, se hace un nuevo contrato en el que se fije un nuevo plan de pagos para las nuevas UF, así como un nuevo indice base, etc.
