### ISSUE TITLE
[CV] cada CV tiene un plan de pagos

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#208]
que consiste en un Pago Inicial y varias Cuotas

**Comment by fauno** [comment]
es un concepto o un modelo?

**Comment by m4tu5** [comment]
uhm ... Pago Inicial y Cuotas son lo mismo, el Pago Inicial no es más que la primera cuota del contrato que vence en el momento de crear el contrato ... no creo que ni valga la pena diferenciarla en la gui ... tal vez podamos ponerla como Cuota 0, ya que en la empresa siempre que hablan de cuotas y se refieren a ellas por numeros excluyen al Pago Inicial

No estoy seguro a que te referis con concepto. Para mi esto tiene olor a modelo ya que vas a tener que guardar en algun lado las diferentes cuotas, con sos valores, fechas, etc, y desupes necesitas poder operar sobre ellas para emitir facturas al vencimiento, o adelantadas, ver si estan pagadas, etc.

**Comment by fauno** [comment]
> No estoy seguro a que te referis con concepto. Para mi esto tiene olor
> a modelo ya que vas a tener que guardar en algun lado las diferentes
> cuotas, con sos valores, fechas, etc, y desupes necesitas poder operar
> sobre ellas para emitir facturas al vencimiento, o adelantadas, ver si
> estan pagadas, etc.

por eso, para mi

```
plan_de_pagos = ContratoDeVenta.find(X).cuotas
```

no haría falta un modelo más sino que el plan de pagos es la colección
de cuotas de un contrato de venta

## 

http://wiki.hackcoop.com.ar

**Comment by fauno** [comment]
lo que digo es que CV.cuotas = plan de pagos, cierro o hay alguna sutileza que me perdí?

**Comment by sudoaza** [comment]
closin
