### ISSUE TITLE
[CV] registra el Valor Base del Indice

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#210]
de #209

**Comment by fauno** [comment]
me imagino que es el valor del indice en el momento en que se crea el contrato de venta no?

**Comment by m4tu5** [comment]
uhm, seguramente si ... pero no estoy seguro de que podamos asumir el valor base solo mirando la fecha de contrato ... hasta que podamos confirmar esto, estaría bueno poder elegir a mano el valor base del indice, para lo cual, basta con elegir un mes de referencia para el indice (que puede o no ser el mismo que el del contrato).

**Comment by fauno** [comment]
ContratoDeVenta.indice tiene el indice base y de ahí se puede sacar el tipo de indice también, ver #204
