### ISSUE TITLE
Separar tipos de tercero en subclases

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#214]
Para modularizar. Cliente y Proveedor deberían heredar de Tercero, así en el módulo de ventas sólo tocamos clientes

**Comment by fauno** [comment]
ya estaba implementado esto?

**Comment by mauriciopasquier** [comment]
No, sólo preparé el terreno

**Comment by mauriciopasquier** [comment]
por si hace falta:

http://thibaultdenizet.com/tutorial/single-table-inheritance-with-rails-4-part-1/

**Comment by fauno** [comment]
y que pasa con un tercero que es cliente y proveedor? se cambia de clase?

**Comment by m4tu5** [comment]
habia un valor de situacion que es 'ambos'

**Comment by mauriciopasquier** [comment]
> y que pasa con un tercero que es cliente y proveedor? se cambia de clase?

yo lo manejaría por separado. Una entrada por cada rol

**Comment by m4tu5** [comment]
vos decis es cliente? si/no ... es proveedor? si/no ... funcionaria

**Comment by fauno** [comment]
no, dice duplicar el registro del tercero

**Comment by m4tu5** [comment]
-1 ... es poco práctico y hay que mantener dos datos iguales cada vez que algo cambie

**Comment by mauriciopasquier** [comment]
On Wed, Aug 20, 2014 at 11:16:20AM -0700, m4tu5 wrote:

> -1 ... es poco práctico y hay que mantener dos datos iguales cada vez que algo cambie

que algo cambie como qué? No estoy diciendo de duplicar datos en la práctica,
estoy diciendo que podemos tener un cliente con cuit 123 y un proveedor con
cuit 123.

poco práctico es meter 3 conceptos distintos en la misma clase y diferenciarlos con ifs

##

**Comment by m4tu5** [comment]
poco practico es retipear algo que ya tenes en el sistema.
si podemos 'chuparlo' de alguna forma, sería ideal (y ademas, similar a lo que existe hoy por hoy, lo que nos facilita la educacion del usuario final)
hoy la mayoria de los sistemas tienen un tercero y 2 campos boolean, uno para cada rol

estoy a favor de otras opciones que no requieran redigitar lo que ya existe

**Comment by mauriciopasquier** [comment]
On Wed, Aug 20, 2014 at 11:22:55AM -0700, m4tu5 wrote:

> poco practico es retipear algo que ya tenes en el sistema.
> si podemos 'chuparlo' de alguna forma, sería ideal (y ademas, similar a lo
> que existe hoy por hoy, lo que nos facilita la educacion del usuario final)

estamos programando.. cómo vas a tener que retipearlo? no estoy entendiendo

> hoy la mayoria de los sistemas tienen un tercero y 2 campos boolean, uno para
> cada rol
> 
> estoy a favor de otras opciones que no requieran redigitar lo que ya existe

???

##

**Comment by m4tu5** [comment]
yo tampoco

lo que digo es que para el usuario final, estaria bien no tener que ingresar un proveedor y un cliente que sean iguales.

que por ejemplo, en el caso de tener un proveedor que se vuelve cliente, poder aprovechar los datos que ya existan de ese tercero y haciendo un clic, ese proveedor ya se pueda usar como cliente.

**Comment by mauriciopasquier** [comment]
Estaríamos complicando mucho el código sólo para evitar que alguna vez haya que escribir dos veces el mismo cuit, con meses de diferencia? Además, simplificar el código no nos impide evitar que el usuario ingrese datos repetidos. Se puede hacer igual

**Comment by m4tu5** [comment]
Para hacerlo a prueba de usuario, el mismo tercero tiene que poder ser proveedor y cliente ... hacemos 2 subclases que podamos linkear?

**Comment by mauriciopasquier** [comment]
subclases es una opción
