### ISSUE TITLE
Las Cuotas tienen fecha de vencimiento

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#215]
cuando la cuota se vence el Tercero adeuda el monto

**Comment by fauno** [comment]
esto sería una vista de cuotas vencidas con un botón de pagar -> generar factura?

**Comment by m4tu5** [comment]
No estoy seguro.

La idea es que cuando la cuota se vence la factura se genere sola (una actividad recurrente debería chequear esto cada noche).

El botón de pagar -> Generar Factura es para cuando queres pagar una couta antes de su vencimiento (o sea, anticipadamente).

**Comment by fauno** [comment]
la fecha de vencimiento de una cuota coincide con el periodo de su indice? por ejemplo si la cuota se vence el 2014-07-01 el indice que se le aplica es el 2014-07-01 o habría un desfasaje?

**Comment by fauno** [comment]
#246 asume que si

**Comment by m4tu5** [comment]
si, en general si, y particularmente para las cuotas de ventas.

creo que para los contratos de obras alguno te pide el indice del mes cuando salga ... o sea que a la larga hay que variabilizar este tipo de entrada ... no se si un drop-down en el CV que permita elegir entre 'mes actual', 'mes anterior'

**Comment by fauno** [comment]
por ahora hay una magia que busca el indice del periodo que coincide con el vencimiento, se puede hacer un dropdown que especifica ese periodo

**Comment by m4tu5** [comment]
perdón, creo que acá respondí mal ... en general para las ventas se usa el indice del mes anterior ... o sea, para una couta que vence el 1-07-214 se usa el indice de 06-2014 ... esto se hace así porque es el que está disponible cuando la cuota se emite.

Los que SI usan el inidice del mismo mes en que se emite la factura son los contratos de construcción ... hormigon, movimiento de tierras, esas cosas ... que como son montos más altos hace más diferencia usar el indice del mes anterior o mes en curso

**Comment by sudoaza** [comment]
ok @m4tu5 pregunta, entonces puede ser algo de configuración usar el indice anterior para las cuotas? hay que agregarle un campo que modifique el usuario que sea usar este indice o el anterior? ya tengo la gui de contrato andando practicamente

**Comment by m4tu5** [comment]
si, idealmente sería algo de configuración como un dropdown en la creación del CV para poder elegir entre el indice del mes en curso o el del mes anterior.

los indices se publican a mes vencido (creo), con lo que el de Abril no sale hasta Mayo y por eso en general se usa el del mes anterior

**Comment by fauno** [comment]
ok cambio Cuota para que por defecto use el indice del mes anterior
