### ISSUE TITLE
Cuando la Cuota vence se genera una Factura

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#217]
el monto de la factura es la cuota que se actualiza según el indice

**Comment by fauno** [comment]
es una factura de cobro

**Comment by fauno** [comment]
o sea que la cuota emite su propia factura? ver #231 y #216

**Comment by fauno** [comment]
la cuota es con o sin iva? el importe total de la factura es el monto actualizado de la cuota + el iva del tercero o solo el monto actualizado?

**Comment by fauno** [comment]
el tipo y número de la factura de dónde sale? o sea se genera y después hay que retocarla?

**Comment by fauno** [comment]
tengo el issue lleno de preguntas

**Comment by m4tu5** [comment]
respondo las que puedo, alguna tengo que pedir clarificacion
- la couta emite su propia factura: si.
- couta es c/ o s/ iva: esto no lo se, tengo que preguntar. por el momento, pongamos el MA en el importe neto de la factura y dejemos el iva en 0
- total de la couta: sera, como siempre, la suma del neto + el iva. 
  como de momento el iva es 0 => total = monto neto = MA ... pero no se calcula sólo el total al crear la factura?
- tipo y numero: acá tenemos que inventarnos algo. dado que se pueden hacer ventas en negro (o al menos una parte de un depto) pongamos que el contrato tenga tambien un tipo, y que la factura se emita con el mismo tipo que el contrato (ej: si A, B, C es blanco, si es X entonces va en negro, como las facturas) ... el numero da lo mismo mientras no se repita con algo existente. pongamosle un contador a las facturas de la obra, por ejemplo ... o usa el ID del objeto ... que se pueda editar esta bien por si se emite algun papel oficial, pero de momento, ya se puede editar desde la factura.

**Comment by fauno** [comment]
entonces lo que acabo de mergear está joya salvo por el tipo de factura que generan las cuotas

**Comment by fauno** [comment]
ah todavia falta hacer que se venzan las facturas, @m4tu5 decía con un cron?

**Comment by mauriciopasquier** [comment]
On Fri, Jun 13, 2014 at 03:38:24PM -0700, fauno wrote:

> ah todavia falta hacer que se venzan las facturas, @m4tu5 decía con un cron?

https://github.com/javan/whenever

##

**Comment by fauno** [comment]
quedamos en hacer una tarea que busque todas las cuotas vencidas sin factura asociada y se las genere, tiene relacion con #230

**Comment by fauno** [comment]
se la paso a @mauriciopasquier

**Comment by fauno** [comment]
por sugerencia de @sudoaza estoy haciendo un metodo que genera todas las facturas.  lo estoy poniendo en Obra.generar_facturas_para_cuotas_vencidas para que recorra todos los contratos

**Comment by fauno** [comment]
ahi esta el metodo para usar en el cron

**Comment by mauriciopasquier** [comment]
por qué no el que ya estaba en cuotas? Dije en el chat antes de esto que pensaba usar `Cuota.vencidas.each blabla`.

**Comment by fauno** [comment]
no se puede hacer mejor al cargar el modelo? :P

**Comment by mauriciopasquier** [comment]
no :P 

Qué pasó con mi consulta?

**Comment by fauno** [comment]
que consulta?

**Comment by mauriciopasquier** [comment]
ésta:

> por qué no el que ya estaba en cuotas? Dije en el chat antes de esto que pensaba usar Cuota.vencidas.each blabla.

**Comment by mauriciopasquier** [comment]
↑

**Comment by fauno** [comment]
es lo que hace el metodo en obra

**Comment by mauriciopasquier** [comment]
On Sun, Aug 31, 2014 at 05:12:36PM -0700, fauno wrote:

> es lo que hace el metodo en obra

pero ya existía uno ferpectamente válido y sin necesidad de acceder a las obras

##

**Comment by fauno** [comment]
donde?

**Comment by mauriciopasquier** [comment]
en Cuota. No entiendo por qué tu método es mejor que `Cuota.vencidas.each(&:generar_factura)`

**Comment by fauno** [comment]
en que rama está eso?

**Comment by mauriciopasquier** [comment]
En develop

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> En develop

aca no veo nada pero si veo que no está el not(pago inicial)

## 

:O

**Comment by mauriciopasquier** [comment]
[Acá](https://github.com/lainventoria/cp/blob/develop/app/models/cuota.rb#L18) es develop.

No se qué cosa no ves.. Hay que buscar cuotas, no? Arrancás con ese modelo (`Cuota`). Hay que buscar las vencidas, hay un scope al respecto (`Cuota.vencidas`). Hay que generar la factura, hay un método que la genera (`Cuota.vencidas.each { |c| c.generar_factura }`). Es más, usaste ese método en tu otro método. Lo que yo pregunto es si hay alguna ventaja en buscar las cuotas a través de las obras y contratos, porque no la veo.

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> [Acá](https://github.com/lainventoria/cp/blob/develop/app/models/cuota.rb#L18)
> es develop.

pero yo la saque...

> No se qué cosa no ves.. Hay que buscar cuotas, no? Arrancás con ese
> modelo (`Cuota`). Hay que buscar las vencidas, hay un scope al
> respecto (`Cuota.vencidas`). Hay que generar la factura, hay un método
> que la genera (`Cuota.vencidas.each { |c| c.generar_factura }`). Es
> más, usaste ese método en tu otro método. Lo que yo pregunto es si hay
> alguna ventaja en buscar las cuotas a través de las obras y contratos,
> porque no la veo.

si, pero no veo el código que decís que escribiste para generar todas
las facturas de un saque.  podés borrar lo mío y crear
Cuota.generar_facturas y listo

## 

http://endefensadelsl.org

**Comment by mauriciopasquier** [comment]
> pero yo la saque...

y cuando decís "acá no lo veo" en dónde te estás fijando?

> si, pero no veo el código que decís que escribiste para generar todas las facturas de un saque. podés borrar lo mío y crear Cuota.generar_facturas y listo

nunca dije que hubiera escrito un método. Es más, estoy diciendo que no hace falta un método. `Clase.scope.enumerador` es más que suficiente. Y dado que era algo que me habían asignado, y estamos con esta discusión hace un mes y medio, quiero saber por qué haríamos un método específico en Cuota o peor aún, en Obra.

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> > pero yo la saque...
> 
> y cuando decís "acá no lo veo" en dónde te estás fijando?

mire mal :P

> > si, pero no veo el código que decís que escribiste para generar todas
> > las facturas de un saque. podés borrar lo mío y crear
> > Cuota.generar_facturas y listo
> 
> nunca dije que hubiera escrito un método. Es más, estoy diciendo que
> no hace falta un método. `Clase.scope.enumerador` es más que
> suficiente. Y dado que era algo que me habían asignado, y estamos con
> esta discusión hace un mes y medio, quiero saber por qué haríamos un
> método específico en Cuota o peor aún, en Obra.

a mi me lo asignó @sudoaza en irc :c

## 

:D
