### ISSUE TITLE
el pueblo quiere saber de que se trata

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#218]
necesitamos acceso ssh con llave para que @mauriciopasquier configure capistrano

**Comment by fauno** [comment]
se puede usar hackers.git para manipulear las llaves con un repo :D

**Comment by mauriciopasquier** [comment]
Acá está mi [llave](http://mauriciopasquier.com.ar/cosas/ssh.pub). Pasen las suyas también @sudoaza @fauno 

Me parece que eso de hackers.git es al pedo.. sólo hay que agregar nuestras llaves en el autorized_keys del usuario con el que corre la aplicación.

**Comment by fauno** [comment]
http://kiwwwi.com.ar/id_rsa.pub
http://kiwwwi.com.ar/id_rsa.pub.asc para comprobarla 

## 

:D

**Comment by m4tu5** [comment]
perdi acceso al server ... esta flotando en el esapcio ... tengo que pasar a ver que onda ... veremos como va la semana :)

**Comment by m4tu5** [comment]
ya esta listo el acceso para @fauno @mauriciopasquier
