### ISSUE TITLE
configurar capistrano

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#219]
necesita #218

**Comment by mauriciopasquier** [comment]
Che, estoy muy fuera de lo que ha estado pasando en cp pero cosas como esta o #217  que no requieren entender el negocio las puedo hacer. Tenemos acceso al server ya?

**Comment by m4tu5** [comment]
On 07/07/2014 02:49 PM, Mauricio Pasquier Juan wrote:

> Che, estoy muy fuera de lo que ha estado pasando en cp pero cosas como
> esta o #217 https://github.com/lainventoria/cp/issues/217 que no
> requieren entender el negocio las puedo hacer. Tenemos acceso al server ya?

ya tenemos acceso

fauno, mpj, ahora les paso los datos en otro correo

al resto, no tengo sus llaves

**Comment by mauriciopasquier** [comment]
http://github.com/sudoaza.keys

**Comment by sudoaza** [comment]
esas keys son viejas

**Comment by mauriciopasquier** [comment]
las 3? Qué usás para github?

**Comment by sudoaza** [comment]
password

**Comment by mauriciopasquier** [comment]
On Thu, Jul 10, 2014 at 12:03:24PM -0700, aza wrote:

> password

:|

bueno, ya las saqué

##

**Comment by mauriciopasquier** [comment]
@sudoaza sin llaves no hay deploy

**Comment by sudoaza** [comment]
Ya tnego llave es la que esta en mi perfil :P

**Comment by mauriciopasquier** [comment]
listo
