### ISSUE TITLE
manual de usuario

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#22]
como lo hacemos?

les parece hacer una nueva carpeta/repo, donde pongamos los manuales en markdown y despues usamos jekyll para servirlos

mpj, existe algo parecido a jekyll en rails que podamos usar para esto (asi nos ahorramos correr un segundo servidor).

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> como lo hacemos?
> 
> les parece hacer una nueva carpeta/repo, donde pongamos los manuales
> en markdown y despues usamos jekyll para servirlos
> 
> mpj, existe algo parecido a jekyll en rails que podamos usar para esto
> (asi nos ahorramos correr un segundo servidor).

alguien le da bola a eso?  unos globitos de ayuda no serian mejores?

## 

http://wiki.hackcoop.com.ar

**Comment by mauriciopasquier** [comment]
On Fri, Feb 14, 2014 at 11:27:09AM -0800, m4tu5 wrote:

> como lo hacemos?
> 
> les parece hacer una nueva carpeta/repo, donde pongamos los manuales en markdown y despues usamos jekyll para servirlos
> 
> mpj, existe algo parecido a jekyll en rails que podamos usar para esto (asi nos ahorramos correr un segundo servidor).

tengo esto en un controlador de otro proyecto

```
def cambios
  changelog = Kramdown::Document.new(
    File.open(Rails.root.join('CHANGELOG.mdwn')).read
  )
  render inline: changelog.to_html, layout: 'application'
end
```

básicamente agarra un markdown del proyecto (podría ser de `doc/manual`) y lo
rederiza con el layout de la aplicación

asique, si querés hacer markdown, metele que usarlo en cualquier lado es fácil

##
