### ISSUE TITLE
Fecha de vencimiento de las Facturas de Cobro

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#220]
la fecha de vencimiento de la factura de cobro = su fecha de emision = vencimiento de la cuota

**Comment by m4tu5** [comment]
No estoy seguro de que la factura venza el mismo dia que se emite ... en general hay un plazo de pago antes de que venza.

fecha emision factura = vencimiento cuota
fecha vencimiento factura = fecha emision factura + xx días

estoy pensando en que tal vez podemos agregar un campo al contrato que sea 'plazo de pago' y que se use como valor para las xx de arriba. por default el valor puede ser 10 dias ... y si despues vemos que es variable, lo agregamos al formulario de nuevo contrato para que pueda cambiarse

**Comment by mauriciopasquier** [comment]
Esto es por ponerse a implementar en los issues..

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> Esto es por ponerse a implementar en los issues..

eso es por ponerse a implementar en la doc!!

## 

 D

**Comment by mauriciopasquier** [comment]
On Thu, May 29, 2014 at 05:01:49AM -0700, fauno wrote:

> Mauricio Pasquier Juan notifications@github.com writes:
> 
> > Esto es por ponerse a implementar en los issues..
> 
> eso es por ponerse a implementar en la doc!!

+1

##

**Comment by fauno** [comment]
pero las facturas no tienen vencimiento, se emiten y se pagan con recibos. en el caso de las cuotas se emiten cuando la cuota vence

**Comment by fauno** [comment]
por ahora le mandamos 10 dias despues del vencimiento de la cuota
