### ISSUE TITLE
El Monto de la Cuota se puede ajustar manualmente

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#224]
Durante la creación del CV, cada cuota debe poder modificarse manualmente (ya sea fecha o monto) manteniendo siempre la restricción de que al crear el CV la suma del PI + Cuotas debe ser igual al monto del CV.

**Comment by sudoaza** [comment]
esto sigue asi ? tenemos que poder editar el monto de las cuotas al crear?

**Comment by fauno** [comment]
aza notifications@github.com writes:

> esto sigue asi ? tenemos que poder editar el monto de las cuotas al crear?

hay un metodo que divide el monto total por la cantidad de cuotas y las
crea, 

## 

:>

**Comment by sudoaza** [comment]
eso lo vi, lo q digo es, 
se pueden editar el monto de todas las cuotas a la hora de crearla? 
se pueden eliminar cuotas? 
se crea automaticamente y luego se editan? 

ping @m4tu5

**Comment by m4tu5** [comment]
al final del día, se tiene que poder armar cualquier plan de coutas que se quiera.

me parece que lo mas común es, un pago inicial medio grande, el resto en coutas iguales a pagar mensualmente.

pensando en como cargarlo, creo que mas que dividir el monto total por la cantidad de coutas, como dice @fauno, haría algo como en los pagos de los recibos donde se pueda agregar una couta individual (se indica fecha, monto) o una serie de coutas (se indica monto total, cantidad de coutas, fecha primera couta, periodicidad [mensual, bimensual, trimestral])

me parece que con esas dos formas de entrar coutas se puede armar todo sin complicarla demasiado.

mas que editar, borrar estaría bien ... con esta forma de cargar coutas, no podes equivocarte en mas de una o una serie ... editar me parece mas complejo.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> al final del día, se tiene que poder armar cualquier plan de coutas
> que se quiera.
> 
> me parece que lo mas común es, un pago inicial medio grande, el resto
> en coutas iguales a pagar mensualmente.

esto ya está cubierto por ContratoDeVenta.crear_cuotas(cantidad de cuotas)

> pensando en como cargarlo, creo que mas que dividir el monto total por
> la cantidad de coutas, como dice @fauno, haría algo como en los pagos
> de los recibos donde se pueda agregar una couta individual (se indica
> fecha, monto) o una serie de coutas (se indica monto total, cantidad
> de coutas, fecha primera couta, periodicidad [mensual, bimensual,
> trimestral])

no entiendo, no estás diciendo lo mismo de forma distinta? si las podés
generar automáticamente por qué nos vamos a complicar con la carga
manual?

## 

http://endefensadelsl.org

**Comment by sudoaza** [comment]
Ok, entonces solo tiene que ingresar el pago inicial, fecha de la primer cuota y periodicidad de la cuota? 
El resto se calcula solo.

Va? O se necesita mas control? 
Estoy con lo de agregar unidades funcionales al contrato y despues paso a esto!

**Comment by m4tu5** [comment]
Hagamos algos similar a lo que tenemos para agregar pagos/cobros a un recibo.
O sea, un botón que desplegue un menú con opciones. 
Creo que con estas 2 opciones de carga estamos:
- Cuota simple (couta inidividual, se ingresa monto y fecha)
- Cuotas multiples (varias coutas iguales, se ingresa fecha inicial, periodicidad, cantidad de cuotas y una de dos: monto de la cuota o monto total al dividir entre cuotas)

**Comment by sudoaza** [comment]
esto esta implementado en contrato-view
