### ISSUE TITLE
No se puede modificar el Plan de Pagos

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#225]
Una vez creado el CV, no se debe permitir modificar el Plan de Pagos o los Precios de Venta de las UFs

**Comment by fauno** [comment]
se podría poner un estado "firmado" o algo así en el contrato de venta para que la gui no muestre botón de edición?

**Comment by m4tu5** [comment]
me pregunto, al crear y editar las cuotas por primera vez, el contrato ya existe? ... porque de no existir en ese momento, solo se pueden editar las cuotas de un @contrato.is_new? (ya no me acuerdo como era), y listo, las cuotas de contratos existentes no se editan.

**Comment by fauno** [comment]
me parece que esto es una de las cosas que está implementando @sudoaza

**Comment by sudoaza** [comment]
las vistas de contrato les falta laburo, este seria el edit.
