### ISSUE TITLE
Montos asociados a las Cuotas

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#226]
Cada Cuota tiene 2 montos asociados
1. Monto Original (MO), que es el monto que consta en el CV
2. Monto Actualizado (MA), que es el monto que se adeuda y paga en un determinado momento del tiempo

**Comment by fauno** [comment]
el monto actualizado tiene sentido fuera del momento de creación de la factura?

**Comment by m4tu5** [comment]
si, mas que nada para saber la deuda que acumula un contrato,

esto puede ser util al querer pagar anticipadamente varias cuotas (deuda de un CV individual), como al revisar la situación financiera de una obra, comparando gastos futuros, con los ingresos pendientes de ser cobrados (deuda de todos los CVs de la obra).

**Comment by fauno** [comment]
esto ya esta implementado, solo faltaría hacer un reporte #232
