### ISSUE TITLE
Calculo del Monto Actualizado

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#227]
El MA se calcula en base al MO y al Valor Actual del Indice (I-VA) que se haya escogido en el CV MA = MO \* ( I-VA / I-VB )

**Comment by fauno** [comment]
aca esta lo que me preguntaba en #233 :P

**Comment by fauno** [comment]
o sea que para una cuota de $10.000 de diciembre para un contrato hecho en enero sobre el indice de costo de construcción el cálculo sería

10000 \* ( 1582.1 / 1247.2 ) = 12600

**Comment by m4tu5** [comment]
CooooooooorrrectoOoOo!!!!!!!!!!!!
