### ISSUE TITLE
El Valor Actual del Indice se calcula según el Indice especificado en el CV

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#228]
El I-VA se determinará según lo que se haya especificado en el CV. Generalmente se utiliza uno de los siguientes              
- Valor del Indice del mes anterior al de la fecha de la Factura de Cobro (caso más usual que asegura que el indice este disponible al vencimiento de la Cuota y emisión de la Factura de Cobro)
- Valor del Indice del mismo mes que el de la fecha de la Factura de Cobro (menos usual por no estar el indice siempre disponible al vencimiento de la Cuota y emisión de la Factura de Cobro)

**Comment by fauno** [comment]
el valor actual se calcula en otro lado que no sea la cuota al momento de pago?

**Comment by fauno** [comment]
este está para cerrar para mí

**Comment by m4tu5** [comment]
Estaría bien poder emitir un reporte sobre un CV que nos diga el valor actual de las cuotas por pagar ... esto, sin tener que emitir las facturas

El mismo reporte se podría hacer para todos los CV de una Obra

Pienso que a 2 años de haber vendido las unidades, los montos en los CV no sirven para nada y puede estar bien saber cuanta guita tenés por cobrar a valor de hoy para poder hacer planeamiento financiero.

**Comment by fauno** [comment]
lo puse en #232 me parece

**Comment by m4tu5** [comment]
sip, esta en #232

**Comment by fauno** [comment]
bueno esto ya esta implementadisimo
