### ISSUE TITLE
Que pasa si no hay Indice Actual

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#230]
En caso de no existir el I-VA, el sistema, idealmente, genera la Factura de Cobro utilizando el I-VA disponible más reciente y  avisa al usuario de la información faltante con un mensaje recurrente que no debe eliminarse hasta que el I-VA necesario se cargue en el sistema.

**Comment by fauno** [comment]
habíamos dicho hacer una factura borrador o abierta con un monto provisorio como para que se pueda cobrar algo hasta que aparezca el indice

**Comment by fauno** [comment]
qué bardo va a ser esto :P

**Comment by m4tu5** [comment]
te parece? le podemos buscar la vuelta, tal vez, sin que se complique demasiado. a ver si logro ser claro.
- tiene que haber algo que nos indique si una cuota esta bien facturada o no. intentaría poner este indicador en la cuota para no tocar el modelo de facturas. aunque no se si esto adhiere a las mejores prácticas de programación ... ping @mauriciopasquier 
- al momento de emitir la factura de una cuota, ya sea automatica o manualmente, tenemos que verificar que exista el valor del indice que se necesita. 
  - si existe, se emite la factura y se marca la cuota como 'final'
  - si no existe, se emite la factura con el ultimo valor del indice disponible anterior al que corresponda [0], se marca la cuota como 'temporal', y en el campo descripción de la factura se pone un mensaje en MAYUSCULAS que avise que se calculo la cuota con el valor del indice del mes XXX por no contar con el de YYY.

[0]: por disponible anterior me refiero a que si la factura debería calcularse usando el valor del indice de Marzo, podemos usar Enero o Febrero, pero no Abril y Mayo aunque existan.
- siempre que existan cuotas 'temporales' se tiene que  presentar el mensaje de error de que falta un valor del indice al acceder al listado de facturas por cobrar hasta que se cargue el indice(s) faltantes (estaría bien también poder avisar cual es el valor que falta, ej: Marzo 2014)
- por otro lado, cada vez que se cargue un nuevo indice, un bucle tiene que iterar sobre todas las cuotas 'temporales'
  - si el nuevo valor del indice es el que la cuota necesita, se edita el total de la factura y se marca la cuota como 'final' y actualiza la descripción de la factura para eliminar el mensaje del indice faltante
  - si el nuevo valor del indice es mejor que el utilizado (ej, es de Febrero para una cuota que necesita indice de Marzo y estaba calculada usando el de Enero[1]), se actualiza el monto de la factura, pero se deja la cuota marcada como 'temporal' y se actualiza la descripción de la factura para reflejar el nuevo indice utilizado
  - si el nuevo valor del indice es posterior al necesario, o mas lejano que el que se utilizo para el calculo temporal, no se nace nada con la factura, y se deja la cuota marcada como 'temporal'

[1]: pensando en como hacer esto sin tener que registrar el indice que se usó para la emisión temporal de una cuota, imagino que comparando el valor que la cuota necesita (Marzo 2014) con el ultimo valor existente (Enero 2014) con el nuevo valor ingresado (Febrero 2014) tiene que salir

como lo ves?

**Comment by fauno** [comment]
en qué casos no estaría disponible el índice cuando se tiene que hacer
la factura? es porque se retrasa el cac?

## 

.oÓ)

**Comment by m4tu5** [comment]
exacto ... o porque se retrasa la carga del indice, error humano que le dicen

**Comment by fauno** [comment]
estoy pensando lo siguiente, en lugar de tocar factura, cambiamos indice para que si no existe el indice necesario, se cree uno "temporal" copiando el del mes anterior, luego se chequea cuales cuotas se pagaron con indices temporales.  aunque esto requeriría guardar el indice del monto actualizado (que sería lo correcto por referencia) de la cuota

**Comment by m4tu5** [comment]
pero vas a dejar el monto de la factura flotante ... o sea, que se calcule cada vez que se abre en base al valor del indice ... esto no implicaría un cambio importante al modelo de facturas ... o vas a actualizar todas las facturas que estén linkeadas a un cierto inidice? como se haría el link, a través de la fecha de la factura?

no estoy seguro de entender bien esta alternativa

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> pero vas a dejar el monto de la factura flotante ... o sea, que se
> calcule cada vez que se abre en base al valor del indice ... esto no
> implicaría un cambio importante al modelo de facturas ... o vas a
> actualizar todas las facturas que estén linkeadas a un cierto inidice?
> como se haría el link, a través de la fecha de la factura?
> 
> no estoy seguro de entender bien esta alternativa

pero en todos los casos el monto de la factura era flotante no? cuando
esta el indice lo que tiene que pasar finalmente es que se actualiza el
monto de la cuota y la factura correspondiente, o no?

## 

:>

**Comment by m4tu5** [comment]
el monto de la cuota no se actualiza, ese queda fijo, es el valor base ... yo siempre asumí que el valor actual iba a estar solo en la factura.

el total de la factura si se calcula automáticamente, pero solo cuando se crea o modifica la factura, no cada vez que se abre

el monto neto y el iva, hasta donde entiendo, se tienen que ingresar y son valores que quedan como los haya puesto el usuario

la idea era que al emitir una factura que se origine en una couta, se calcula el ValorActual y se pone en ImporteNeto, ponemos IVA 0 y así el Total calculado es igual al Neto igual al ValorActual

yo decía de actualizar el valor del ImporteNeto cuando se actualice el indice, en base a un estado en la couta que distinga facturas definitivas de las temporales

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> el monto de la cuota no se actualiza, ese queda fijo, es el valor base
> ... yo siempre asumí que el valor actual iba a estar solo en la
> factura.
> 
> el total de la factura si se calcula automáticamente, pero solo cuando
> se crea o modifica la factura, no cada vez que se abre
> 
> el monto neto y el iva, hasta donde entiendo, se tienen que ingresar y
> son valores que quedan como los haya puesto el usuario
> 
> la idea era que al emitir una factura que se origine en una couta, se
> calcula el ValorActual y se pone en ImporteNeto, ponemos IVA 0 y así
> el Total calculado es igual al Neto igual al ValorActual
> 
> yo decía de actualizar el valor del ImporteNeto cuando se actualice el
> indice, en base a un estado en la couta que distinga facturas
> definitivas de las temporales

estamos diciendo lo mismo entonces.  lo que yo digo es lo siguiente

Cuota.indice_actual => no existe, se crea un indice copia del ultimo
indice disponible con estado "temporal" => se calcula el monto => se
genera la factura

cuando se actualiza el indice se saca el estado temporal y se recalcula
el monto de las facturas para todas las cuotas que usaron ese indice,
apareciendo como impagas (porque el saldo cambia).

## 

:>

**Comment by m4tu5** [comment]
On 06/23/2014 07:28 PM, fauno wrote:

> estamos diciendo lo mismo entonces. lo que yo digo es lo siguiente
> 
> Cuota.indice_actual => no existe, se crea un indice copia del ultimo
> indice disponible con estado "temporal" => se calcula el monto => se
> genera la factura

hasta aca. ok

> cuando se actualiza el indice se saca el estado temporal y se recalcula
> el monto de las facturas para todas las cuotas que usaron ese indice,
> apareciendo como impagas (porque el saldo cambia).

aca no se como haces el nexo entre indice temporal y facturas a
recalcular ... creo que no tienen vinculo directo y tampoco tengo claro
que la cuota se vincule al indice, porque este queda determinado por la
fecha de factura, no la de vencimiento de la cuota (para el caso de las
facturas emitidas anticipadas)

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> > cuando se actualiza el indice se saca el estado temporal y se recalcula
> > el monto de las facturas para todas las cuotas que usaron ese indice,
> > apareciendo como impagas (porque el saldo cambia).
> 
> aca no se como haces el nexo entre indice temporal y facturas a
> recalcular ... creo que no tienen vinculo directo y tampoco tengo claro
> que la cuota se vincule al indice, porque este queda determinado por la
> fecha de factura, no la de vencimiento de la cuota (para el caso de las
> facturas emitidas anticipadas)

por eso digo que el indice que se usó para calcular el monto actualizado
debería guardarse en la cuota también

## 

}(:=

**Comment by m4tu5** [comment]
el indice que se uso para calcular el monto actualizado 'temporal' me parece que no importa, lo importante es saber que hay que recalcularlo cuando se cargue un nuevo indice. 

al cargar el nuevo indice, se re-calculan los montos actualizados de las cuotas con estado temporal, usando el mejor indice disponible, para lo que se usa el valor base (en cuota), el indice base (en contrato), y el mejor indice disponible ... si se corresponde con el de la fecha de la cuota (o del mes anterior) se pasa la cuota a 'final', sino, se deja en 'temporal'

**Comment by fauno** [comment]
entonces lo que son temporales son las cuotas?

**Comment by m4tu5** [comment]
para mi, lo que es temporal, es el monto total de la factura, que esta relacionada a la cuota.

otra forma de verlo es que la cuota fue emitida con un monto 'temporal', entonces sería la cuota la que esta facturada 'temporalmente'

como la relacion cuota-factura es 1-a-1, podemos poner el estado 'temporal' en cualquiera de ambas y da lo mismo. yo voto por ponerlo en la cuota para dejar tranquilo el modelo de facturas

**Comment by fauno** [comment]
lo que hablamos hoy:

-[ ] si no existe el indice  
[ ] se crea uno temporal con el valor del indice anterior que si existe
[ ] se guarda el indice usado  
[ ] cuando se especifica verdadero en el indice
[ ] recorre todas las cuotas que usan este indice
[ ] y actualiza el monto de la factura si la tienen

**Comment by fauno** [comment]
haciendo esto me surgió una duda, si vamos a guardar el indice en la cuota de todas formas, el monto actualizado debería usar siempre el mejor indice disponible o si ya fue calculado usar ese?

**Comment by m4tu5** [comment]
no entiendo bien la pregunta. es que si el monto actualizado, que se guarda en la factura, deberia recalcularse en base al mejor indice disponible en la tabla de indices, en aquellos casos en que el indice usado no sea el correcto?

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> no entiendo bien la pregunta. es que si el monto actualizado, que se
> guarda en la factura, deberia recalcularse en base al mejor indice
> disponible en la tabla de indices, en aquellos casos en que el indice
> usado no sea el correcto?

digo si Cuota.indice_actualizado calcula el indice si Cuota.indice.nil?
o siempre

## 

http://endefensadelsl.org

**Comment by m4tu5** [comment]
On 07/07/2014 03:18 PM, fauno wrote:

> digo si Cuota.indice_actualizado calcula el indice si Cuota.indice.nil?
> o siempre
> 
> creo que ni una ni la otra ... algo en el medio

si solo lo calculas cuando es nil, entonces si tenes un valor
desactualizado, como lo sabes?

si lo recalculas todo el tiempo, entonces estas recualculando muchas
veces cosas innecesarias.

no tenemos un campo o maquina de estados para diferenciar entre unas y
otras?

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> no tenemos un campo o maquina de estados para diferenciar entre unas y
> otras?

instalo la gema máquina del tiempo

## 

:>

**Comment by mauriciopasquier** [comment]
https://rubygems.org/gems/timecop

> A gem providing "time travel" and "time freezing" capabilities

(más allá del chiste, es re útil :P)

**Comment by fauno** [comment]
la respuesta era: mientras el indice sea nil o temporal usar el mejor que haya, a partir de ahi usar el indice indicado. les va?

**Comment by m4tu5** [comment]
me va, pero si el indice es temporal, como se usa el mejor que hay ... revisando la lista de indices para ver si hay uno mejor al momento de acceder a la factura, y en caso de haberlo, actualizar el valor indice temporal, y del monto de la factura?

**Comment by fauno** [comment]
con una máquina de estados!
