### ISSUE TITLE
Reportes

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#232]
- [x] Unidad Funcional: disponibles vs. vendidas, pudiendo diferenciar entre los diferentes tipos
- [x] Contrato de Venta: al día vs. con retrasos, dependiendo de que todas las cuotas vencidas esten cobradas o pendientes de cobro
- [x] Cuotas: cobradas vs. pendientes, tanto en montos como en nro de cuotas
- [x] Cuotas: montos originales vs montos acutalizados, pudiendo listar los Montos Actualizados a la fecha en que se acceda al reporte

**Comment by fauno** [comment]
arranco con los scopes

**Comment by fauno** [comment]
lo de montos actualizados es parte de la vista asi que no hago scope

**Comment by fauno** [comment]
el de contrato de venta sería algo así como cv.cuotas.vencidas.pendientes :D

**Comment by fauno** [comment]
como irian los reportes en el menu? un item reportes y que se aplique por obra?

**Comment by m4tu5** [comment]
esa es una opción

en un momento había pensado ponerlos a continuación de las acciones, dentro de la misma pestaña con las operaciones ... o sea, necesitamos un menu de Ventas (aza hizo algo) con 2 secciones, la primera de Operaciones y la segunda de Reportes

al principio de todo había algo así ... en el dropdown se puede poner un separador y un texto a forma de Titulo de Sección que diga 'Reportes' o algo asi

**Comment by fauno** [comment]
lo estoy poniendo en el indice de cuotas y contratos asi no hay que ir a una vista totalmente especial para ver un estado de la obra...
