### ISSUE TITLE
Hay indices

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#233]
Me parece que los indices son uno de los lados por los que empezar porque no tienen dependencias, pero nos falta documentación de cómo se verían

**Comment by fauno** [comment]
http://www.camarco.org.ar/indicadores creo que es esto pero la descarga necesita una cuenta

**Comment by fauno** [comment]
@sudoaza encontró esto http://www.camconstrucciones.com.ar/documentos/indice-cac.pdf

**Comment by m4tu5** [comment]
esto de @sudoaza es exactamente lo que buscamos.

la table muestra 3 indices diferentes, a saber:
1. CAC -Costo de Construcción
2. CAC - Materiales
3. CAC - Mano de Obra

para las cuotas se usa en general el 1 ... los indices 2 y 3 los vamos a usar en el modulo de gestión de contratos

**Comment by fauno** [comment]
(pensando en voz alta) lo que no me queda claro de esto todavía es cómo se calculan, porque en el pdf se ven montos en base $100 a diciembre de 2001 y despues valores fijos, pero de mes a mes hay un diferencial porcentual (por ejemplo de enero a febrero un 0.2%)

entonces si en enero hago un contrato, la cuota de diciembre cómo se calcula? el valor de esa cuota \* el indice de ese mes o todos los que pasaron desde enero a diciembre acumulados?

me imagino que el indice esta hecho para que se aplique sobre ese mes, pero cuál sería la formula? una regla de tres simple? con que elementos? ahaahahhahah

**Comment by fauno** [comment]
por ahora hay un indice base en el contrato de venta que se usa para actualizar los montos en las cuotas, hay que confirmar si hacen falta en las unidades (ver #245) pero me parece que no, porque el valor final de la unidad funcional es la suma de todos los montos actualizados de las cuotas por lo que no habría que indexar el precio de referencia.

@m4tu5 confirmá!

faltaría implementar en gui

**Comment by m4tu5** [comment]
escribi sobre los valores de las UF en #253 

con respecto a los indices, no se usa el cambio porcentual de un mes a otro que te da la tabla, sino que se usa el valor numerico y se hace la formula que hablamos

I-Actual/I-Base \* Monto Original = Monto Actual
