### ISSUE TITLE
Factura calcula mal el saldo

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#241]
Pague una factura con unos cheques y el saldo parece que no da.

![screenshot from 2014-06-03 17 39 20](https://cloud.githubusercontent.com/assets/555365/3166315/70438104-eb5f-11e3-9fe1-ee57e02df7d5.png)

**Comment by m4tu5** [comment]
sospechoso que tengas 2 recibos con valor 0 ... eso es raro ... creo que no se puede hacer un recibo sin pagos, o si? .... en fin, investigaria a ver que onda eso ...

**Comment by sudoaza** [comment]
@m4tu5 si, esos son recibos sin causa que cree mientras probaba otro issue

**Comment by fauno** [comment]
alguno lo reprodujo? me fijo en el de prueba

**Comment by fauno** [comment]
aca probé y me anduvo bien

**Comment by sudoaza** [comment]
trata agregando cheques y usandolos para pagar cosas

2014-07-15 18:25 GMT-03:00 fauno notifications@github.com:

**Comment by fauno** [comment]
cree una factura de cobro, le agregue un cheque de terceros, agregue una factura de pago y la pagué con ese cheque de terceros y anduvo bien

**Comment by fauno** [comment]
el saldo no está cacheado asi que si no se calcula bien es porque algun recibo se generó mal

**Comment by sudoaza** [comment]
anda todo joya
