### ISSUE TITLE
Cheques no se pueden pagar

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#242]
Cuando voy a cheques propios o vencidos y quiero "pagar" uno muere.

![screenshot from 2014-06-03 17 45 00](https://cloud.githubusercontent.com/assets/555365/3166372/08e21ccc-eb60-11e3-9c7b-41ab4b8d1d8e.png)

**Comment by m4tu5** [comment]
On 06/03/2014 05:45 PM, aza wrote:

> Cuando voy a cheques propios o vencidos y quiero "pagar" uno muere.
> 
> screenshot from 2014-06-03 17 45 00
> https://cloud.githubusercontent.com/assets/555365/3166372/08e21ccc-eb60-11e3-9c7b-41ab4b8d1d8e.png

fijate que el cheque tenga una cuenta (no sea que se haya borrado con el
error que había hasta hace poco.

por otro lado, fijate que la cuenta desde la que vas a pagar tenga
saldo, sino ese podría ser otro error.

**Comment by sudoaza** [comment]
Esto es con los datos de prueba, puede ser que esos datos esten mal, chequeo!

**Comment by sudoaza** [comment]
Cree 3 cheques para pagar parte de una factura, todo joya.

Intento pagar los cheques y me lleva a editar con todos los campos en readonly.

cuando le doy guardar me tira un error que le faltan datos... 

como deberia comportarse cuando le doy pagar cheque @m4tu5 ? En algun momento estaba y dejo de funcionar?

**Comment by fauno** [comment]
mmm está bien, el controlador para pagar dice que si no se pudo pagar el cheque te mande a editar pero no se están mostrando los errores, ahi lo veo

**Comment by fauno** [comment]
@sudoaza si queres saber quien programó algo usá `git blame $archivo`

**Comment by fauno** [comment]
ahi le puse que avise, falta decir por qué

**Comment by fauno** [comment]
me pasa lo mismo cuando quiero usar un cheque de terceros para pagar otra factura, no sé por qué no tengo el debugger fancy como uds

![cheque-terceros-pagar-factura](https://cloud.githubusercontent.com/assets/468204/3665200/b056c274-11e3-11e4-86a0-29b4847c788c.png)

**Comment by fauno** [comment]
el error original es un tema que no se está haciendo nada con la excepción de Caja.depositar y Caja.extraer salvo rollbackear la transacción, si le saco los true a la llamada a esos metodos en Cheque.pagar el cheque se paga porque los metodos devuelven un movimiento invalido de valor $0

**Comment by fauno** [comment]
se supone que sin true se devuelve un movimiento con un error que indica que no hubo fondos pero no se muestra en ningun lado

**Comment by mauriciopasquier** [comment]
en vez de redirigir probaste agregando un error en el cheque? Cuando usás `render action: 'sarasa'` se usa la vista de sarasa con las variables que tenés ya cargadas (o sea el `@cheque` con los errores).

También se pueden agregar errores específicos en vez de esos `return nil if pagado?` y `return nil if terceros?`

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> en vez de redirigir probaste agregando un error en el cheque? Cuando
> usás `render action: 'sarasa'` se usa la vista de sarasa con las
> variables que tenés ya cargadas (o sea el `@cheque` con los errores).

antes estaba así con un notice pero no se renderizaba

> También se pueden agregar errores específicos en vez de esos `return
> nil if pagado?` y `return nil if terceros?`

si pero el error salta más adelante cuando la extracción falla por
falta de fondos y se rollbackea la transacción sin avisar nada, no sé
cómo capturar esto aún.

## 

:D

**Comment by mauriciopasquier** [comment]
> si pero el error salta más adelante

ya se, pero además. Estaría bueno ir agregando los errores correctos (que
probablemente hagan saltar todos los tests :P).

> cuando la extracción falla por falta de fondos y se rollbackea la transacción
> sin avisar nada, no sé cómo capturar esto aún.

Sobre capturar la excepción sería algo así:

```
begin
  salida = cuenta.extraer(monto, true)
rescue ActiveRecord::Rollback => excepcion
  error.add(:cuenta, :fondos_insuficientes)
end
```

**Comment by mauriciopasquier** [comment]
Gracias al #307 ahora sí se pueden capturar las excepciones de caja

**Comment by sudoaza** [comment]
yasta solo falta mergear
