### ISSUE TITLE
moneda de los cv, uf y cuotas?

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#245]
van todas en la misma moneda?

**Comment by m4tu5** [comment]
sip, todas iguales ... no se si fijar moneda en la UF y que el resto lo tome de ahi, o si hacerlo en el contrato ... lo que seguro hereda moneda, son las cuotas

**Comment by mauriciopasquier** [comment]
La UF tiene precio? Para mí se define en el contrato eso.

**Comment by m4tu5** [comment]
La UF tiene un precio de referencia desde su creación. Y creo que estaría bien que pueda elegir su propia moneda.

Después, a la hora de venderla el precio se puede ver modificado/actualizado y venderse por un monto/moneda diferente.

Por ejemplo, tenes una unidad funcional de 40m2, vendes a US$ 1.000 el m2 ... entonces, la UF tiene un precio de referencia de US$ 40.000

A la hora de la venta, se acuerda el plan de pagos en AR$, indexados por CAC

No hay que hacer ningún cálculo o modificación a la UF ni a su precio de referencia. Casi mejor conservarlo para después poder comprar los precios de referencia con los realmente obtenidos.

**Comment by fauno** [comment]
o sea que al momento de hacer el contrato de venta el precio de la unidad funcional se indexa? no había un issue de eso eh

**Comment by fauno** [comment]
no convendría que la obra tengo una moneda de referencia?
