### ISSUE TITLE
Paths para recibos

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#25]
1) Al listar los recibos pertenecientes a una factura con una URL como este:
http://localhost:3000/facturas/55777060/recibos
Se muestran todos los recibos existentes para todas las facturas.
No funciona el filtro del controlador?

2) Cual es el path para listar todos los recibos existentes de un cierto tipo (cobro/pago) independientemente de la factura a la que pertenecen?

**Comment by fauno** [comment]
duplica #33
