### ISSUE TITLE
Valores de referencia y de venta de las UF y los totales de los CV

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#253]
siguiendo un comentario de @fauno en #245 

las UF tienen un precio de referencia cuando se crean. este precio de referencia puede ser en cualquier moneda. este valor es el que se estima como precio de venta al hacer el planeamiento inicial de la obra (antes de hacer el pozo, meter hormigón, etc.)

después, al crear un CV, el precio de cada UF seguro es diferente al valor de referencia, ya que depende de la negociación con el comprador, de las necesidades de la empresa en ese momento, de cuanto tiempo haya pasado entre el planeamiento y la venta, etc.

me parece piola que al momento de agregar una UF al CV se pida el valor de venta de esa UF

o sea, que el total del CV va a ser la suma de los valores de venta de las UFs, y la suma de las cuotas debe ser igual a ese valor.

creo que como una vez creado el CV no se puede modificar, pediría una confirmación antes de guardar el CV

**Comment by fauno** [comment]
mmm entonces agregamos el valor de referencia como atributo de la unidad funcional o se actualiza el valor de la uf cuando se crea el cv?

**Comment by sudoaza** [comment]
estamos agregandolo en otro campo, ya esta hecho. money precio_venta precio_venta_final
