### ISSUE TITLE
revisar que ruby arranque con el sistema

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#257]
no estoy seguro que al reiniciarse el sistema arranque el servidor.

cual es la mejor forma de lograr esto?
- armar un servicio
- ponerlo en un script o cron?

**Comment by mauriciopasquier** [comment]
On Mon, Jul 07, 2014 at 12:34:10PM -0700, m4tu5 wrote:

> no estoy seguro que al reiniciarse el sistema arranque el servidor.
> 
> cual es la mejor forma de lograr esto?
> - armar un servicio

yo diría servicio + monit, pero no se bien cómo tenés armado el server ni cómo
hacer servicios para centos

##

**Comment by m4tu5** [comment]
plantilla para el servicio de sistema

http://tech.superhappykittymeow.com/?p=326
@mauriciopasquier  podes preparar el script?

hago otro usuario lainventoria con sudo?

**Comment by m4tu5** [comment]
la otra opcion es usar `rc.local`

**Comment by m4tu5** [comment]
puse esto en rc.local
`su -c "cd /home/gestion/cp && /home/gestion/.rbenv/shims/rails s" gestion`

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> puse esto en rc.local
> `su -c "cd /home/gestion/cp && /home/gestion/.rbenv/shims/rails s" gestion`

inittab o monit, pero no tiene passenger ese server?

## 

:>

**Comment by mauriciopasquier** [comment]
> hago otro usuario lainventoria con sudo?

otro o el mismo, como quieras

**Comment by mauriciopasquier** [comment]
> inittab o monit, pero no tiene passenger ese server?

Sí, tiene. @m4tu5: con passenger no hace falta levantar el server de rails porque se encargan passenger + apache

**Comment by m4tu5** [comment]
On 07/09/2014 09:01 PM, Mauricio Pasquier Juan wrote:

> ```
> inittab o monit, pero no tiene passenger ese server?
> ```
> 
> Sí, tiene. @m4tu5 https://github.com/m4tu5: con passenger no hace
> falta levantar el server de rails porque se encargan passenger + apache

uhm ... ok, entonces voy a ver si passenger esta configurado para
arrancar al inicio, porque me dio la impresion que no estaba levantando
GestionAr cuando el server reiniciaba

**Comment by m4tu5** [comment]
ok, tenian razon ... saque la linea de `rc.local` y reinicie el server y la aplicacion esta corriendo
:)
