### ISSUE TITLE
Desarrollar con la misma db que en producción

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#258]
En producción estamos con mysql. Personalmente creo que postgresql es mucho mejor, y propondría migrar. Pero elijamos la que elijamos estaría bueno que desarrollemos en la misma db.

@m4tu5: usás para algo más ese mysql en el server o podemos cambiar si pinta?

**Comment by m4tu5** [comment]
no se esta usando para nada mas ... se puede instalar PostgreSQL y migrar la data de GestionAr

ahora, se que fauno esta haciendo cosas con mariadb para otras cosas y me pregunto si no es mas conveniente seguir con mysql/mariadb para no diversificar demais

a mi personalmente me da igual cualquiera de las 2.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> no se esta usando para nada mas ... se puede instalar PostgreSQL y migrar la data de GestionAr
> 
> ahora, se que fauno esta haciendo cosas con mariadb para otras cosas y
> me pregunto si no es mas conveniente seguir con mysql/mariadb para no
> diversificar demais
> 
> a mi personalmente me da igual cualquiera de las 2.

estaba por probar clusterizar multimaestro con mariadb, no se como
funcionaria en postgresql

## 

http://selfdandi.com.ar

**Comment by mauriciopasquier** [comment]
> estaba por probar clusterizar multimaestro con mariadb, no se como funcionaria en postgresql

y qué tiene que ver? Digo, lo vamos a usar en este server de intranet? Para qué lo querés hacer?

> me pregunto si no es mas conveniente seguir con mysql/mariadb para no diversificar demais

en ese caso (si el tema es no diversificar) elijamos postgresql que es mucho mejor

**Comment by m4tu5** [comment]
ok, te gusta postgres ... lo captamos
si queres migrarlo, adelante, aunque tal vez mejor enfocarse en otras cosas mas visibles/urgenetes?

**Comment by mauriciopasquier** [comment]
ahora no tengo más ganas porque resulta que estoy imponiendo..

**Comment by mauriciopasquier** [comment]
Ah, y cuando misteriosamente ande todo en desarrollo pero no en producción, vamos a ver si es visible o urgente este issue.

**Comment by m4tu5** [comment]
si te animas con el centos, adelante con postgres ... tiene sus vueltas el sistema porque es una distro no del todo estandar (ClearOS) pero seguro que en los foros hay cosas de esto

yo me inclino a dejar el server de produccion como esta y a migrar develop a mysql

**Comment by m4tu5** [comment]
para evitar quilombos, mas que otra cosa ...

**Comment by mauriciopasquier** [comment]
queda mysql entonces. Vayan configurandolo localmente
