### ISSUE TITLE
no se puede acceder a ver los cheques desde el listado de cheques

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#261]
el problema es por el renderizado del parcial con el listado de recibos

los cheques que estan asociados a un recibo interno no se renderizan bien en el parcial y hay que corregirlo

ver arreglo en #146

**Comment by fauno** [comment]
estabas vos con esto?

**Comment by m4tu5** [comment]
sip, estoy, lo puse aca porque lo estaba dejando para mas adelante y para no olvidarme. ahora estoy haciendo las cosas pequeñas y esta requiere algo mas de cabeza.

**Comment by fauno** [comment]
esto ya está resuelto entonces?

**Comment by m4tu5** [comment]
yo aun no lo toque

**Comment by fauno** [comment]
bueno lo agarro yo

**Comment by fauno** [comment]
debo confesar que nunca entiendo los issues de @m4tu5

**Comment by m4tu5** [comment]
la vista de cheques renderiza un parcial que muestra los recibos a los que está asociado.

este parcial estaba preparado para los recibos de cobro/pago, pero no para los recibos internos, y esto hacía que se rompiese la vista de los cheques

**Comment by fauno** [comment]
ni una capturita o url?

**Comment by fauno** [comment]
en que casos hay cheques asociados a recibos internos?

**Comment by fauno** [comment]
cuando se paga un cheque propio, pero no me esta funcionando pagar un cheque :P

**Comment by m4tu5** [comment]
es que esto depende de tus datos ... la url no ayuda.

los cheques se asocian a recibos internos segun su tipo
- cheques propios, se asocian a un recibo interno cuando se paga el cheque
- cheques de 3ros, se asocian a un recibo interno cuando se cobran (despues de ser depositados)
- cheques de 3ros que pasan de manos, no se asocian a ningun recibo interno

por eso que no te funciona pagar un cheque es que este punto quedo a la espera de que eso se solucione :)

**Comment by fauno** [comment]
yo lo veo bien

![cheque-con-recibos](https://cloud.githubusercontent.com/assets/468204/3971282/2fda35d6-27d2-11e4-94e5-eb7eca016ee4.png)

**Comment by m4tu5** [comment]
sip, me parece que se arreglo en algun PR anterior donde se toco el parcial ... por ese lado podemos cerrar el issue.

no me gusta lo de agregar 'Chequera' a la vista ... es redundante y confunde.

**Comment by fauno** [comment]
eso ya estaba lo que agregué es la cuenta

**Comment by mauriciopasquier** [comment]
+1, lo sacaría
