### ISSUE TITLE
stacktrace con ruby 2.0.0 y spring

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#268]
no se que onda, rake me anda bien

http://pastie.org/pastes/9394793/text?key=j0gxow0h1m1ia0uvswfw

**Comment by mauriciopasquier** [comment]
esto es en tu notebook o en ponape? Probá sin `bundle exec` y usando `bin/rails`, o metiendo bin en el path

**Comment by fauno** [comment]
ahora me andó rails s y no toqué naranjas
