### ISSUE TITLE
Error al ingresar montos con . en lugar de ,

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#27]
Si se ingresa una cantidad usando el '.' como separador decimal, da un error, y cambia el '.' por una ',' en el formulario, pero no graba la transaccion.

Estaria mejor que corrigiese el error automaticamente, sin avisar al usuario, y que grabase el formulario.

**Comment by mauriciopasquier** [comment]
> Si se ingresa una cantidad usando el '.' como separador decimal

en dónde?

> , da un error,

qué error?

> y cambia el '.' por una ',' en el formulario, pero no graba la transaccion.

automáticamente? te corrije la entrada de, por ejemplo, 10.0 a 10,0?

> Estaria mejor que corrigiese el error automaticamente, sin avisar al usuario, y que grabase el formulario.

y si tenés que poner miles con centavos?

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> > Si se ingresa una cantidad usando el '.' como separador decimal
> 
> en dónde?

si no recuerdo mal @m4tu5 cuando me estaban mostrando las vistas te vi
escribir un monto con , y se guardó bien

## 

http://partidopirata.com.ar

**Comment by m4tu5** [comment]
On 02/28/2014 01:23 PM, Mauricio Pasquier Juan wrote:

> en dónde?
> 
> en cualquiera de los formularios existentes, o sea, editar/nueva
> factura/recibo
> 
> ```
> , da un error,
> ```
> 
> qué error?
> 
> este, por ejemplo, es de ingresar el iva con '.' en lugar de ','
- Iva translation missing: es.errors.messages.invalid_currency

> ```
> y cambia el '.' por una ',' en el formulario, pero no graba la
> transaccion.
> ```
> 
> automáticamente? te corrije la entrada de, por ejemplo, 10.0 a 10,0?
> 
> el formulario al recargarse mostrando el error (despues de hacer click
> en Guardar Cambios) ya modifico el '.' por ',' con lo que si apreto
> Guardar Cambios otra vez sin hacer nada, esta segunda vuelta, los
> cambios se guardan sin error
> 
> ```
> Estaria mejor que corrigiese el error automaticamente, sin avisar
> al usuario, y que grabase el formulario.
> ```
> 
> y si tenés que poner miles con centavos?
> 
> los que cargan facturas no van a usar nunca separador de miles al
> digirar, solo de decimales.

esta bien que nosotros mostremos los numeros con separador de miles,
aunque yo preferiria algo que no pueda confundirse, como un espacio ( )
o una comilla simple (')

**Comment by fauno** [comment]
me parece que esto puede servir: http://blog.firmhouse.com/fancy-money-entry-for-your-rails-app-with-autonumeric-and-moneyrails

**Comment by m4tu5** [comment]
corregido con autoNumeric que se incorporo en feature/mas-cambios
