### ISSUE TITLE
estandarizar nombres y tipos de fecha

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#270]
ayer estabamos viendo que el vencimiento de las facturas se llama fecha_pago, tambien hay campos de fecha que no se prefijan "fecha_", algunos que solo necesitan fecha son de tipo fecha y hora y se les implementaron unos hacks en la interfaz para quitarles la hora...

**Comment by sudoaza** [comment]
toque el formato de los datepicker xq en español se complicaba parsearlos
desde js. Ahora es dd/mm/yyyy

en indice toque algo de lo qu habias hecho, esperemos a que mergee
contrato-view

aza

**Comment by mauriciopasquier** [comment]
esperando #274

**Comment by m4tu5** [comment]
#274 ya esta mergeado, ya se puede retomar este issue
