### ISSUE TITLE
documentar la api?

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#271]
se puede hacer algo onda rubydoc.info?

**Comment by mauriciopasquier** [comment]
Podríamos como mínimo adoptar esto: http://tomdoc.org/

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> Podríamos como mínimo adoptar esto: http://tomdoc.org/

ta lindo, a mi me gustaba rocco pero es mas para leer el texto después
(por eso los comentarios verborrágicos)

## 

http://librevpn.org.ar

**Comment by mauriciopasquier** [comment]
> a mi me gustaba rocco

sí, claro.. a escribir cuentitos en los comentarios. Es horrible!!

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> > a mi me gustaba rocco
> 
> sí, claro.. a escribir cuentitos en los comentarios. Es horrible!!

qué código le estarás dejando a tus hijos

## 

}(:=
