### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#272]
iba a actualizar cp.lainventoria.com.ar y me acordé que se iba a deployear con capistrano, configuro un usuario de ssh entonces

**Comment by fauno** [comment]
necesita shell ese usuario?

**Comment by fauno** [comment]
bueh quedó gestionar.lainventoria.com.ar pero no sé por qué perdí los colores y el sqlite de produccion (!)

**Comment by mauriciopasquier** [comment]
On Tue, Jul 15, 2014 at 03:14:07PM -0700, fauno wrote:

> necesita shell ese usuario?

creería que sí, un usuario normal. Pero acá hay más detalles y sutilezas que se
me escapan:

  http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/

##

**Comment by mauriciopasquier** [comment]
@fauno pasó algo con esto? Cuando lo hagas tenés que crear un archivo de deploy y definir un nombre. El "standard" para el server de demo o test-previo-a-producción es **staging**, asique sería `config/deploy/staging.rb`. Creo que toma el nombre a partir del archivo.

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> @fauno pasó algo con esto? Cuando lo hagas tenés que crear un archivo
> de deploy y definir un nombre. El "standard" para el server de demo o
> test-previo-a-producción es **staging**, asique sería
> `config/deploy/staging.rb`. Creo que toma el nombre a partir del
> archivo.

no, lo miro hoy

## 

:D

**Comment by fauno** [comment]
que dia mas largo!
