### ISSUE TITLE
movimientos sin causa / problema con creacion de cheques propios

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#276]
al ingresar un pago con cheque propio en un recibo de pago, si no se selecciona la cuenta bancaria desde la que se emite el cheque pasa lo siguiente
- no se crea el cheque
- se registra el movimiento en el recibo

con lo que nos queda un recibo con un movimiento por el importe del cheque, pero sin causa porque el cheque no se crea ... o sea, un recibo con un movimiento que no existe en ningún lado.

deberíamos ver que primero se cree el cheque y que en caso de no poder, no se registre el movimiento en el recibo

**Comment by m4tu5** [comment]
@mauriciopasquier vos habías desarrollado estos formularios, podrás mirar esto?

**Comment by mauriciopasquier** [comment]
On Thu, Jul 17, 2014 at 12:55:21PM -0700, m4tu5 wrote:

> @mauriciopasquier vos habías desarrollado estos formularios, podrás mirar esto?

ok

##

**Comment by sudoaza** [comment]
@mauriciopasquier te saco este!

**Comment by mauriciopasquier** [comment]
On Mon, Aug 04, 2014 at 05:29:45PM -0700, aza wrote:

> @mauriciopasquier te saco este! 

ok

##

**Comment by m4tu5** [comment]
tambien pasa en cheques de 3ros
