### ISSUE TITLE
edicion de recibos / no funcionan los botones para borrar movimientos

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#277]
esto creo que es porque estamos dibujando los botones pero no hay ningún método atrás ... necesitamos crearlo

**Comment by mauriciopasquier** [comment]
Qué implica financieramente borrar movimientos? O es sólo cuestión de corregir errores de carga?

**Comment by sudoaza** [comment]
no vamos a borrar los moviientos, vamos a borrar el recibo de una y sus child
