### ISSUE TITLE
edicion de recibos / no se pueden borrar los recibos

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#278]
creo que esto es porque al tener movimientos asociados no pueden borrarse

habria que solucionar primero #277 y despues ver que funcione esto

**Comment by fauno** [comment]
creo que esto lo habiamos charlado pero no me acuerdo en que quedamos, deberian borrarse los movimientos cuando se borra el recibo? o solo cuando se borraron todos los movimientos a mano?

**Comment by fauno** [comment]
esta relacionado con lo que pregunta @mauriciopasquier en #277

**Comment by mauriciopasquier** [comment]
según los comentarios esto estaría resuelto. Reabran con un test de integración :P

**Comment by sudoaza** [comment]
esto todavia no esta implementado

**Comment by fauno** [comment]
matanga!

**Comment by fauno** [comment]
che pero si borro el recibo con todos sus movimientos que pasa con los movimientos de cambio? resolvimos eso al final?

**Comment by fauno** [comment]
@mauriciopasquier ya habia programado el borrado de recibos pero no se mostraba un mensaje de error cuando no se podía borrar, se lo agregué en feature/borrar-recibos

**Comment by sudoaza** [comment]
solo falta mergear los tests cierro
