### ISSUE TITLE
selector de cuentas en medios de pago no muestra banco

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#279]
esto hace que al tener dos cuentas del mismo tipo (ej. cajas de ahorro) no se sepa cual se está seleccionando al ingresar un cheque nuevo o transferencia

el selector debería o bien mostrar el tipo + banco + ultimos 4 nros, o algo similar que permita diferenciar entre una cuenta y otra

**Comment by fauno** [comment]
ni una capturita?

**Comment by fauno** [comment]
ahi lo vi ya lo arreglo, para reproducir era
- crear dos cajas del mismo tipo
- crear un recibo de pago y pagar con cheque propio
- el selector muestra dos veces el tipo

**Comment by fauno** [comment]
y es el mismo problema que el de #292
