### ISSUE TITLE
retenciones / borrado de retenciones

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#281]
al borrar una retención, si ya estaba aplicada en un recibo de pago, se borra la retencion del recibo de pago.

si el recibo solo tenía a la retención, entonces el recibo queda vacío. en este caso, debería borrarse el recibo también.

no se recalcula el saldo de la factura automaticamente y hay que hacerlo de forma manual (editando un recibo y guardarlo sin hacer cambios) para obtener el nuevo saldo. debería automatizarse esto.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> al borrar una retención, si ya estaba aplicada en un recibo de pago,
> se borra la retencion del recibo de pago.
> 
> si el recibo solo tenía a la retención, entonces el recibo queda
> vacío. en este caso, debería borrarse el recibo también.
> 
> no se recalcula el saldo de la factura automaticamente y hay que
> hacerlo de forma manual (editando un recibo y guardarlo sin hacer
> cambios) para obtener el nuevo saldo. debería automatizarse esto.

galponeo, grabar un videito de lo que estás viendo :P

## 

http://vqfe4xmhxzi7w2uv.onion

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> On 07/21/2014 03:41 PM, fauno wrote:
> 
> > galponeo, grabar un videito de lo que estás viendo :P
> > 
> > -1

vinagre!

## 

.oÓ)

**Comment by fauno** [comment]
che pero el saldo de la factura se calcula cada vez que se llama, con Factura.saldo

**Comment by fauno** [comment]
lo de borrar los recibos vacios no entraria en conflicto con crear el recibo y despues asociarle movimientos? se podria poner un filtro por defecto en la vista de factura que traiga los recibos con movimientos

**Comment by mauriciopasquier** [comment]
solución: no dejar borrar una retención que esté asociada a un recibo (o sea que haya sido usada)

**Comment by fauno** [comment]
empece esto pero no entiendo nada de retenciones y no se como testearlo, lo estoy jodiendo a @mauriciopasquier por irc

**Comment by fauno** [comment]
me parece que este commit que hice está relacionado con lo que estuvo testeando @sudoaza

**Comment by fauno** [comment]
y ahora se pueden borrar retenciones o no?

**Comment by mauriciopasquier** [comment]
no se cómo está implementado pero debería ser así:
1. no podés borrar una retención si está asociada a un recibo
2. no podés borrar un recibo si tiene una retención (esto ya estaba creo)
3. hay que hacer una forma de desasociar la retención del recibo

@m4tu5 confirmás esto?
