### ISSUE TITLE
retenciones / pago de retenciones

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#282]
no veo como se pueden pagar las retenciones, ni recuerdo que se había acordado a este respecto.

en la vista de retenciones (caja y bancos -> retenciones) no hay botones que permitan pagar las retenciones aún no pagadas

es importante no dormirse con esto y estar al dia con la AFIP, con lo que habíamos hablado de incluir las retenciones pendientes de pago dentro del listado de facturas por pagar ... ya sea creando una factura asociada, o listando directamente la retención, pero de alguna forma se tiene que saber que se adeuda ese dinero y ahora mismo no esta claro

@mauriciopasquier, te acordas algo de esto? puede ser que haya cosas programadas que no se hayan implementado en el front-end?

**Comment by fauno** [comment]
como es? cuando se paga una retencion se genera una factura de pago por su valor?

**Comment by m4tu5** [comment]
la historia completa es así,
1. Se recibe una factura de un proveedor, y se registra en el sistema.  
2. Se accede a la web de la AFIP, se ingresan los datos de la factura, la AFIP emite un certificado de retención que nos entrega en formato PDF -- todo esto por fuera del sistema.  
   La Retención tiene un monto, una fecha de emisión y una fecha de vencimiento.  
   La sola emisión de la Retención por la AFIP genera la obligación de pago por parte de CP una vez llegada la fecha de vencimiento, sin importar si la Retención se aplicó o no a la factura original.  
3. Se registra la retención en el sistema. Se registran ambas fechas, el monto, la factura que le da origen, y se adjunta el PDF que nos entrega la AFIP.  
   Acá hay algo importante. La Retención tiene 2 caminos paralelos. Por un lado, el camino en el cual se aplica la retención a un pago, a través de un Recibo de Pago. Por otro, el pago de la retención a la AFIP, a través de una transferencia bancaria.

El pago que se adeuda a la AFIP, desde el momento en que se carga la retención al sistema, y que tiene la fecha de vencimiento que la Retención Indique, no lo veo por ningún lado.

No creo que haga falta listarlo con las facturas (ese comentario es viejo y ya no vale). Lo que si es que hay que informar al usuario que tiene retenciones por vencer ese mismo día (o en los próximos 2/3 días habiles)

Este aviso de que se vence una retención creo que no esta implementado

No me queda claro que esté implementado el pago de la retención tampoco, que no sería más que una transferencia de fondos entre una cuenta bancaria/caja y la chequera retenciones

Espero haber sido claro, sino, chifla

**Comment by sudoaza** [comment]
el modelo de retenciones tiene un metodo pagar! copiado de cheques que no tiene pinta de andar. Hay un listado de retenciones deberia aparecer un boton ahi a la  derecha como en los cheques.

**Comment by mauriciopasquier** [comment]
@sudoaza no hiciste esta parte?

**Comment by sudoaza** [comment]
no, @fauno  y @m4tu5  dijeron que lo terminaban...

**Comment by fauno** [comment]
aza notifications@github.com writes:

> no, fauno y matus dijeron que lo terminaban... 

https://www.youtube.com/watch?v=ST_MKIc5D04

## 

http://librevpn.org.ar

**Comment by fauno** [comment]
bueno me pongo con esto...

**Comment by fauno** [comment]
>  Acá hay algo importante. La Retención tiene 2 caminos paralelos. Por un lado, el camino en el cual se aplica la retención a un pago, a través de un Recibo de Pago. Por otro, el pago de la retención a la AFIP, a través de una transferencia bancaria.

pero nosotros generamos la retención en el sistema en el momento de pagar una factura, no hay una lista de retenciones pre-cargadas (onda indices) y despues al pagar una factura le aplicas una.

o sea asi como esta en el sistema y lo que entiendo de todas las vueltas que diste ;)
- vas a una factura de pago
- le cargás una retención
- cuando vence, vas al listado de retenciones
- el boton pagar transfiere el monto de una cuenta bancaria a una caja de retenciones
- la retencion queda pagada

**Comment by mauriciopasquier** [comment]
en los dos últimos pasos está (o debería estar) el pago a la AFIP

**Comment by fauno** [comment]
/me se pregunta por qué no lo hace @m4tu5 que ya lo tiene claro...

**Comment by fauno** [comment]
en que momento se decidiría la caja de donde se van a extraer los fondos? al pagar o al cargar la retención?

**Comment by fauno** [comment]
que diferencia hay entre una retencion aplicada a la factura y una aplicada al recibo? el estado no varía

**Comment by fauno** [comment]
se podría, por ejemplo, agregar la cuenta desde la que se va a pagar a la afip en el formulario de retenciones, y el metodo pagar transfiere de esa caja a la caja de retenciones?

**Comment by fauno** [comment]
a ver en ese commit...

**Comment by mauriciopasquier** [comment]
> en que momento se decidiría la caja de donde se van a extraer los fondos? al
> pagar o al cargar la retención?

supuestamente cuando la cargás, nunca cambia

> se podría, por ejemplo, agregar la cuenta desde la que se va a pagar a la
> afip en el formulario de retenciones, y el metodo pagar transfiere de esa
> caja a la caja de retenciones?

supuestamente es así

> que diferencia hay entre una retencion aplicada a la factura y una aplicada
> al recibo? el estado no varía

aplicada a un recibo es que se usó como pago. Asociada a una factura es que se
le va a retener a X proveedor por Y compra (determinados por la factura) y que
sólo se puede aplicar en recibos para pagar esa factura

**Comment by fauno** [comment]
fijense ahi, en todo caso habría que agregar la caja en el form de retenciones y sacarlo de la lista

llegamos a los 400 issue+pr!
