### ISSUE TITLE
retenciones / no se aplican automaticamente

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#283]
el objetivo era que al crear una nueva retención, esta quede pre-aplicada al próximo recibo que se emita sobre la factura que da origen a la retención, o sea, que se apliquen automáticamente.

esto no está pasando.

ahora mismo, se crea la retención, y a menos que se aplique a mano, no se tiene en cuenta en los recibos que se creen sobre la factura.

**Comment by m4tu5** [comment]
el objetivo de que la retención se aplique automaticamente al próximo recibo es que de esta forma recuerde al usuario que tiene una retención hecha sobre la factura que aún no ha sido aplicada (entregada al proveedor), pero si ha sido descontada de la deuda de la factura (desde el momento de creación de la retención)

**Comment by sudoaza** [comment]
Esto esta en el pr que hay ahi, cuando creas la retencion se aplica de una
