### ISSUE TITLE
pago en otra moneda / al cancelar recibo se cancela el pago, pero no el cambio de moneda

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#286]
esto sucede cuando se hace un pago en una moneda diferente a la del recibo.

si se crea el recibo, el sistema registra un pago en la misma moneda del recibo, y un cambio de moneda en la caja para justificar el ingreso en una moneda diferente.

si se cancela la creación del recibo, una vez ingresado el pago en moneda diferente, se borra de la caja el movimiento de entrada/salida del monto equivalente, pero queda el cambio de moneda

el cambio de moneda debería también eliminarse ya que de no cobrar el dinero, no se cambia la moneda tampoco.

**Comment by fauno** [comment]
tampoco avisa si no habia disponible de esa moneda

**Comment by fauno** [comment]
a ver como era esta logica (mirando la base de datos)
- cuando se **cobra** en efectivo con un cambio de moneda
- se hace un recibo interno que une la extracción de la moneda que se aceptó ($1000 ARS) por la adición de la moneda que se cambió ($100 USD)
- son dos movimientos unidos por un recibo de importe $0
- se crea un movimiento en la caja donde se deposita el efectivo por la moneda que se aceptó ($1000 ARS)
- el recibo interno no queda asociado a la factura que se estaba cobrando

dudas:
- la caja no debería recibir $100 USD en realidad?
- la operacion de cambio no debería quedar asociada a la factura donde se generó el cambio?
- así como está la cosa no habría forma de deshacer el cambio si se cancela el recibo porque no hay relación entre los dos (interno y de cobro)

**Comment by fauno** [comment]
efecto mariposa:
- agregué en Caja.cambiar que se pueda especificar el recibo o se cree un recibo interno si no
- agregué en Efectivo.cambiar y Transferencia.cambiar que se especifique el recibo actual
- salta la verificacion de Recibo.todos_los_montos_son_monotonos
- si se esquiva la verificacion, el saldo de la factura no toma en cuenta la moneda y resta 100 en lugar de 1000 (obviamente porque 1000 - 1000 + 100 = 100)

**Comment by fauno** [comment]
cambie el recibo por factura para que cree un recibo interno asociado a la factura, en teoría anda bien pero todavia no toma en cuenta la otra moneda y una de las partes del movimiento no queda asociada por lo que el saldo se calcula mal...

me parece que es lo mas simple de agregar pero habria que ver para donde arreglamos asi le pongo esfuerzo :P

**Comment by sudoaza** [comment]
Esto es una bizarreada no me quiero imaginar lo q es el codigo

**Comment by mauriciopasquier** [comment]
yo tampoco, y creo que @fauno está rehaciendo cosas que yo deshice:

```
agregué en Caja.cambiar que se pueda especificar el recibo o se cree un recibo interno si no
agregué en Efectivo.cambiar y Transferencia.cambiar que se especifique el recibo actual
```

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> yo tampoco, y creo que fauno está rehaciendo cosas que yo deshice:
> 
> ```
> agregué en Caja.cambiar que se pueda especificar el recibo o se cree un recibo interno si no
> agregué en Efectivo.cambiar y Transferencia.cambiar que se especifique el recibo actual
> ```

por qué? el recibo de cambio no tendría que quedar relacionado con la factura?

## 

http://vqfe4xmhxzi7w2uv.onion

**Comment by fauno** [comment]
Caja.cambiar siempre se manejó con recibos internos, lo que no se hace es pasar ese recibo a extraer y depositar sino que agregan los movimientos a la coleccion de movimientos del recibo

**Comment by fauno** [comment]
la pregunta es cómo cancelamos operaciones de cambio de una factura si esas operaciones no se registran como asociadas a ella

**Comment by fauno** [comment]
ahi pushee la rama con el codigo que asumen bizarro

**Comment by mauriciopasquier** [comment]
> la pregunta es cómo cancelamos operaciones de cambio de una factura si esas operaciones no se registran como asociadas a ella

depende.. qué es "cancelar"? Si ya hiciste el cambio me parece que no queda otra que hacer el cambio a la inversa. Lo pregunté en algún issue por ahí.. estoy un poco perdido

**Comment by m4tu5** [comment]
en realidad la operación de cambio esta asociada a un recibo, no a una factura

**Comment by fauno** [comment]
bueno el primer intento fue agregar los movimientos de cambio al recibo de la factura, pero se rompe todo porque de golpe aparece un movimiento en otra moneda, todos_los_montos_son_monotonos y no estaba claro por donde agarrar

**Comment by mauriciopasquier** [comment]
estoy con esto

**Comment by m4tu5** [comment]
pobre issue ... q.e.p.d.
