### ISSUE TITLE
cheques de terceros / el cheque genera un movimiento pero no cambia de estado

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#289]
Al depositar un cheque de terceros se crea un movimiento en la chequera que resta el monto del cheque.

Lo que deberia suceder es que el cheque cambia de estado de 'chequera' a 'depositado' y no se afecta ningún saldo de ninguna caja.

Luego, desde la vista de cheques depositados se puede 'cobrar' el cheque o 'rebotarlo'

Si se cobra, entonces se resta el monto del cheque de la 'chequera' y se suma en la cuenta bancaria asociada.

Si se rebota, entonces se cambia el estado del cheque a 'rebotado' y los saldos quedan como estaban.

**Comment by fauno** [comment]
el codigo hace el cambio pero hay un FIXME que dejó @mauriciopasquier que dice "update"

**Comment by fauno** [comment]
aaah no entendi, ahi reviso entonces

**Comment by fauno** [comment]
en los comentarios (salve!) del codigo dice que es una "transferencia en dos pasos" donde el deposito extrae el monto de la chequera y el cobro lo deposita en la caja correspondiente, lo que crea los movimientos desfasados que decís, esto ya no es así?

**Comment by m4tu5** [comment]
mas o menos :p 

en realidad no se extrae el monto de la chequera hasta que no se cobre, sino tendríamos al cheque en un limbo.

el cambio de estado lo deja de sumar en algún reporte de saldo, porque deja de estar en cartera. también hay que ver que la vista de cheques de terceros nos permita diferenciar entre 'chequera', 'depositados', 'rebotados', 'cobrados'

el recibo interno recién se emite cuando el cheque se cobra, y en caso de que se rebote, cambia de estado pero no se toca ninguna caja/chequera

**Comment by fauno** [comment]
entonces para confirmar

Cheque.depositar solo cambia el estado y la caja donde se hará el depósito
Cheque.cobrar hace la transferencia de la chequera a la caja destino

**Comment by m4tu5** [comment]
+1
