### ISSUE TITLE
listado de movimientos / ajustar campos visibles al controlador que lo renderice

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#291]
por ejemplo, para recibos internos estaría bien que se muestre la moneda (especialmente en cambios de moneda)

para las transferencias entre cajas, estaría bien poder listar los movimientos con signos, para entender que caja emite y cual recibe

etc.

**Comment by fauno** [comment]
no está esto ya?

**Comment by fauno** [comment]
@sudoaza lo estamos viendo ahora, la onda es que en el listado de movimientos los movimientos negativos no tienen signo, y cuando ves los movimientos del cheque solo se ven las causas y no las cajas

**Comment by mauriciopasquier** [comment]
huele a test de integración!

**Comment by sudoaza** [comment]
voy a ver si no hago los test :P
