### ISSUE TITLE
Al borrar un contrato no borra las cuotas

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#295]
y la unidad no queda disponible para otro contrato. 
seguro es una pavada en rails

**Comment by mauriciopasquier** [comment]
On Mon, Jul 21, 2014 at 08:36:36PM -0700, aza wrote:

> y la unidad no queda disponible para otro contrato. 
> seguro es una pavada en rails

algo como

```
has_many :cuotas, dependent: :destroy
```

?

##

**Comment by fauno** [comment]
aza notifications@github.com writes:

> y la unidad no queda disponible para otro contrato. 
> seguro es una pavada en rails

hay que agregarle before_destroy como hiciste en unidades_funcionales

## 

http://hackcoop.com.ar

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> On Mon, Jul 21, 2014 at 08:36:36PM -0700, aza wrote:
> 
> > y la unidad no queda disponible para otro contrato. 
> > seguro es una pavada en rails
> 
> algo como
> 
> ```
> has_many :cuotas, dependent: :destroy
> ```

+1 no me acordaba como era, y el before_destroy para desvincular las
unidades funcionales

## 

http://vqfe4xmhxzi7w2uv.onion

**Comment by sudoaza** [comment]
lo toy haciendo

**Comment by mauriciopasquier** [comment]
> y el before_destroy para desvincular las unidades funcionales

probaron `dependent: :nullify` en vez de agregar callbacks custom?

**Comment by sudoaza** [comment]
hecho lo de nullify
