### ISSUE TITLE
Cache de parciales renderizados

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#30]
Problema con la renderizacion de views/recibos/_list.html.erb
El mismo parcial se renderiza en facturas/# y en recibos/
Se ajusta el CSS entre las vistas usando nested-layouts.

Los ajustes se aplican bien al CSS, pero no se renderizan. Pareciera que hay un cahce del partial hecho en algun lado y no se actualiza la vista.

Al refrescar la pagina si se actualiza.

**Comment by mauriciopasquier** [comment]
???

no hay caché en modo development, no entiendo el bug report..

**Comment by m4tu5** [comment]
Tal vez no lo explique bien (seguramente).

En los ultimos dias vi que el error sucede en Chromium, pero no en Firefox.
1) La vista recibos/index renderiza un parcial (_list) con 5 columnas
2) La vista factura/show renderiza el mismo parcial (recibos/list) con 2 columnas y oculta las otras 3

Al cargra factura/show, muchas veces aparecen las 5 columnas de recibos/list y hay que refrezcar la pagina (F5) para que se vean solo las 2 columnas

Al cargar recibo/index, si se viene de ver una factura, se ven solo 2 columnas, en lugar de las 5 que deberían mostrarse

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> Tal vez no lo explique bien (seguramente).
> 
> En los ultimos dias vi que el error sucede en Chromium, pero no en Firefox.
> 1) La vista recibos/index renderiza un parcial (_list) con 5 columnas
> 2) La vista factura/show renderiza el mismo parcial (recibos/list) con 2 columnas y oculta las otras 3
> 
> Al cargra factura/show, muchas veces aparecen las 5 columnas de
> recibos/list y hay que refrezcar la pagina (F5) para que se vean solo
> las 2 columnas
> 
> Al cargar recibo/index, si se viene de ver una factura, se ven solo 2
> columnas, en lugar de las 5 que deberían mostrarse

ya te dije para mi es que el navegador cachea el css

## 

:>

**Comment by m4tu5** [comment]
seguramente, la pregunta es si hay algo que podamos ponerle al css o html para que no cachee estas paginas

como mpj ya tiene experiencia con rails e imagino que usar nested-partials no es tan raro, imagine que tal vez ya sabia cual era el truco para que esto no pase

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> seguramente, la pregunta es si hay algo que podamos ponerle al css o
> html para que no cachee estas paginas

si va a cambiar con el renderizado mandale un estilo inline o una clase que
sólo haga eso y que venga con todo el css, eso no hay forma de
cachearlo.

i <3 dirty hacking

## 

:>

**Comment by mauriciopasquier** [comment]
posta no entiendo de qué hablan... rails no hace cache en develop a menos que hayan tocado cosas muy raras. Y el navegador no debería cachear el css porque rails le dice que ha sido modificado.

**Comment by m4tu5** [comment]
probaste a ver si podes replicar el error?
yo ya te digo, me pasa con Chromium y no con Firefox.

**Comment by m4tu5** [comment]
algo paso con los ultimos commits o con una actualizacion de FireFox que sacaron en estos días, que los parciales tiene ahora los mismos problemas para renderizarse que en Chromium.

O sea, si vamos a la vista de Cajas y Cuentas, que renderiza 2 veces el mismo parcial con diferentes columnas para Cajas y para Cuentas, ahora muestra todas las columnas en las 2 secciones.

Voy a probar de tirar para atras develop en mi compu para ver si es un tema de algo comiteado y se arregla, o si por el contrario, es un tema de los navegadores y tendremos que buscar una solucion diferente.

**Comment by m4tu5** [comment]
El problema no tiene que ver con los cambios mergeados. Fauno, con Icedove, ve bien mi app y yo veo mal la de el que no tienen los ultimos commits.

El problema es que no se esta actualizando la seccion <style> dentro del <header> de la pagina cuando esta se carga. Al cargar la pagina por primera vez, si ya hay info existente en <style> se conserva y no se actualiza. Hay que refrescar la pagina a mano <F5> para que se carge la info correcta en <style>.

O sea, hay que ver que se puede hacer para que esta sección se actualice al cargar la pagina y que no haya que refrescarla a manopla

**Comment by m4tu5** [comment]
lo que esta hecho y no funciona es lo que se explica en 
http://guides.rubyonrails.org/layouts_and_rendering.html
en la ultima seccion, Nested Layout

**Comment by m4tu5** [comment]
bueno, ya tengo una rama armada pasando parametros al partial para elegir que se renderiza.

**Comment by m4tu5** [comment]
Cerrado en #73.
Las vistas se renderizan bien en chromium

**Comment by mauriciopasquier** [comment]
> El problema es que no se esta actualizando la seccion dentro del <header> de la pagina cuando esta se carga.

Esto es algo que hace turbolinks para que ande todo más rápido

**Comment by m4tu5** [comment]
Más rápido y mal. Igual esto ya está solucionado. 

El problema ahora es con los .js, que dejaron de cargarse

**Comment by mauriciopasquier** [comment]
On Sat, Mar 22, 2014 at 09:27:07AM -0700, m4tu5 wrote:

> Más rápido y mal. Igual esto ya está solucionado. 

más rápido y bien, si no le jugás en contra.

##
