### ISSUE TITLE
Poda

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#308]
Ramas del repo no asociadas con ningún pull request:
- feature/cambio-asociado-a-factura
- feature/cheques_path
- feature/demo-cambia-color-barra-navegacion
- feature/pagar-cheques-242
- feature/unidad-tercero
- feature/unidades-funcionales-view
- feature/vencimiento-de-cuotas

**Comment by m4tu5** [comment]
On 08/01/2014 04:16 AM, Mauricio Pasquier Juan wrote:

> Ramas del repo no asociadas con ningún pull request:
> - feature/demo-cambia-color-barra-navegacion

esta hace lo que dice, y como la idea es solo que este asi en la versión
que demos a los clientes para que jueguen y aprendan, no veo que valga
la pena hacer PR

**Comment by mauriciopasquier** [comment]
On Fri, Aug 01, 2014 at 02:41:07PM -0700, m4tu5 wrote:

> On 08/01/2014 04:16 AM, Mauricio Pasquier Juan wrote:
> 
> > Ramas del repo no asociadas con ningún pull request:
> > - feature/demo-cambia-color-barra-navegacion
> 
> esta hace lo que dice, y como la idea es solo que este asi en la versión
> que demos a los clientes para que jueguen y aprendan, no veo que valga
> la pena hacer PR

ok

##

**Comment by mauriciopasquier** [comment]
qué hacemos con estas ramas?

```
remotes/origin/feature/cambio-asociado-a-factura
remotes/origin/feature/cerrar-290
remotes/origin/feature/generar-facturas
remotes/origin/feature/pagar-cheques-242
remotes/origin/feature/unidad-tercero
remotes/origin/feature/vencimiento-de-cuotas
```

**Comment by m4tu5** [comment]
ninguna es mia, o sea ... arrojadlas por la borda !!!

**Comment by mauriciopasquier** [comment]
@fauno @sudoaza ?

**Comment by sudoaza** [comment]
yo mis branches las borre todas son de @fauno

2014-09-03 17:59 GMT-03:00 Mauricio Pasquier Juan notifications@github.com
:

**Comment by fauno** [comment]
ahi borro las mias

**Comment by fauno** [comment]
ahi esta solo deje las que tienen soluciones en discusio
