### ISSUE TITLE
Factura Tipo hacer un dropdown

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#312]
Ahroa hay que poner la letra y si no es valido no aparecen todas las opciones de pago, podriamos tener un dropdown con ABCX no ?

**Comment by fauno** [comment]
aza notifications@github.com writes:

> Ahroa hay que poner la letra y si no es valido no aparecen todas las
> opciones de pago, podriamos tener un dropdown con ABCX no ?

+1

## 

.oÓ)

**Comment by sudoaza** [comment]
Cuales son los Tipos que deberian aparecer ?  @m4tu5

**Comment by sudoaza** [comment]
sino podemos hacer que transforme todo a uppercase y que lo muestre asi y listo, asi no hay problema con la validacion

**Comment by m4tu5** [comment]
Es más bien para acotar un poco. La total falta de estructura puede confundir. Podría letras, como ser A B C R(etencion) T(icket) X(marca el tesoro) Y Z también para lado oscuro.

**Comment by fauno** [comment]
me pongo con esta

**Comment by fauno** [comment]
fijense si con el pr #331 es suficiente

**Comment by fauno** [comment]
a todo esto cuando se genera la factura de una cuota no se le pone ningun tipo, que hacemos?

**Comment by m4tu5** [comment]
el contrato lleva un tipo (o tipo de factura) que es el que se usa despues para la emisión de facturas
tiene que tener los mismos valores posible que las facturas

**Comment by fauno** [comment]
no sería mejor que el tipo de factura lo tenga el tercero?

**Comment by m4tu5** [comment]
se puede tener un tipo predeterminado (A o C), pero no se puede imponer porque mucha gente trabaja a 2 colores, digamos

**Comment by fauno** [comment]
ok sale con tipo_factura en contratos

**Comment by fauno** [comment]
se cierra o se hace select?
