### ISSUE TITLE
Cuenta debe ser de moneda única

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#317]
Las cuentas bancarias no deben permitir depósitos en varias monedas. Extraído de #172

**Comment by fauno** [comment]
esto es urgente o lo podemos dejar para 1.1?

**Comment by m4tu5** [comment]
el unico riesgo que se me ocurre es que alguien haga un cambio de moneda incorrecto, o algo así.
creo que por otro lado no es posible hacer un movimiento con moneda incorrecta

en cualquier caso, creo que podemos dejarlo para 1.1 porque no creo que sea un error común, y si salta, lo podemos ver en su momento
