### ISSUE TITLE
Hay tests fallando en develop

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#319]
```
234 runs, 560 assertions, 4 failures, 2 errors, 0 skips
```

**Comment by fauno** [comment]
hay unos tests fallando que están relacionados con commits "arreglando tests" de @sudoaza  :P

**Comment by fauno** [comment]
y otros fallan porque hay 5 cuotas en lugar de 13 como antes

**Comment by fauno** [comment]
bueh son un poco delicados y mis gemas andaban medio raro.  al final como habiamos quedado con los indices? el mejor indice posible o el mejor indice posible cuando no hay un indice para la cuota? la primera opcion hace que siempre aparezca el mejor indice, claro, pero si estabas esperando uno y te apareció otro en el medio te cagó la vida

**Comment by m4tu5** [comment]
ya no me acuerdo de esto de los indices, pero siento que lo hablamos muchas veces.
si mal no recuerdo, decías de crear el indice que necesitas para la couta y asignarle un valor con estado 'preliminar' y que eso hacia saltar las alarmas, y que cuando se actualizaba el indice, se cambiaba el estado a 'definitivo'
creo que tambien habia un estado en la couta, avisando de si la factura era 'temporal' o 'final'

iba por aca tu duda?

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> ya no me acuerdo de esto de los indices, pero siento que lo hablamos
> muchas veces.  si mal no recuerdo, decías de crear el indice que
> necesitas para la couta y asignarle un valor con estado 'preliminar' y
> que eso hacia saltar las alarmas, y que cuando se actualizaba el
> indice, se cambiaba el estado a 'definitivo' creo que tambien habia un
> estado en la couta, avisando de si la factura era 'temporal' o 'final'
> 
> iba por aca tu duda?

no, eso está más que claro, la pregunta es si una vez que se encuentra
un indice para una cuota se para de buscar o cada vez se busca el mejor
que haya.  en este pr me decidí por dejar de buscar.

## 

.oÓ)
