### ISSUE TITLE
los recibos generan movimientos

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#32]
:O recien veo el link automatico a CONTRIBUTING

voy a hacer la relacion recibo has_many movimientos

**Comment by fauno** [comment]
mmm será que al guardar un recibo con sus movimientos hay que correr caja.depositar? se me rompieron todos los tests de caja :P

**Comment by fauno** [comment]
o capaz asocio recibos a cajas!

**Comment by fauno** [comment]
@mauriciopasquier che ayer estuvimos viendo esto con @m4tu5 , la onda es la siguiente:
- los movimientos, aunque sean de caja tenían que generar recibos por la asociación que estaba haciendo
- charlando nos dimos cuenta que estaría bueno que los movimientos de caja (cambio, deposito, etc.) generen recibos internos, para llevar un registro de todos los movimientos.
- cambié el modelo de Recibos para que no valide la factura si la situacion es "interno"
- no llegué a tiempo para hacer que Caja.cambio genere un recibo interno antes de generar los movimientos

durante el dia te pusheo las cosas

**Comment by mauriciopasquier** [comment]
los recibos no deberían ser reflejos de un papel? El movimiento es el reflejo virtual de un cambio de plata..

**Comment by m4tu5** [comment]
digamos que si vos sacas dinero de una caja, hay un recibo asociado ... o sea, sale dinero, entra papel ... con lo que para un movimiento interno de fondos, hay un recibo interno asociado

**Comment by mauriciopasquier** [comment]
entonces cuál es la diferencia entre recibo y movimiento?

**Comment by m4tu5** [comment]
Un recibo puede tener mas de un movimiento. Esto es algo que es más usual en el pago/cobro de facturas que en los movimientos entre cajas/cuentas

**Comment by fauno** [comment]
ver pr #43
