### ISSUE TITLE
manejar contratos con unidades funcionales en varias monedas

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#320]
ContratoDeVenta.total_de_unidades_funcionales falla cuando se mezclan unidades con distintas monedas porque intenta sumarlas como si fuera una sola.  Cómo deberíamos manejarlo?
- Impedir que se agreguen unidades funcionales con distintas monedas
- Convertir el precio de venta a la moneda del contrato (la de la primera unidad? elegir una para el contrato?)
- Tener un monto en cada moneda? (se hacen contratos con partes en distintas monedas?)

**Comment by fauno** [comment]
relacionado con #319

**Comment by m4tu5** [comment]
Dudo que se hagan contratos en 2 monedas. 

Si no es complicado contemplarlo, no resta tenerlo, pero imagino que el contrato se hace un una moneda unica. Despues, los pagos se hacen como quieran.

**Comment by fauno** [comment]
el consejo de san telmo resuelve que el contrato valide que todas sus unidades estén en la misma moneda

**Comment by fauno** [comment]
esa validacion ya existia pero se dispara despues de calcular_monto_total :P
