### ISSUE TITLE
unicidad de índices

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#332]
1. se pueden repetir los índices en un mismo período?
2. si 1 es sí, se pueden repetir los índices y la denominación?

**Comment by m4tu5** [comment]
a que te referís por _repetir_ los indices?
a que un indice pueda tener 2 valores diferentes en un mismo período? ... no, tiene uno solo.
a que el valor de un indice pueda ser el mismo en varios períodos? ... si
a otra cosa? ... bueno, no sería la primera vez que no entiendo las preguntas ;p

**Comment by mauriciopasquier** [comment]
O sea el índice es único para una combinación de período y denominación (el "tipo" de índice?)

**Comment by m4tu5** [comment]
corrrrrrrrecto!
