### ISSUE TITLE
No mostrar el botoncito de agregar retenciones si ya cree todas?

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#334]
Sino puedo ir a crear retnciones pero ya cree de todos los tipos y no puedo crear mas.

**Comment by m4tu5** [comment]
+1, si no te complica mucho la logica de la vista ... sino, que el botoncito quede ahi, pero que no deje ir a la vista de crear retenciones si ya existe una de cada tipo posible, falla con mensaje de error y queda en donde estaba (o listado de facturas o vista de factura detallada)
