### ISSUE TITLE
el cheque no muestra la cuenta desde la que se emite

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#338]
es confuso saber donde tiene que haber fondos para pagar un cheque

**Comment by fauno** [comment]
faltaría mostrar el estado tambien

**Comment by m4tu5** [comment]
los cheques propios, que son los unicos que se pagan, se asocian a una cuenta bancaria cuando se crean ... no veo por donde salta la confusión?

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> los cheques propios, que son los unicos que se pagan, se asocian a una
> cuenta bancaria cuando se crean ... no veo por donde salta la
> confusión?

que despues no la encontrás por ningun lado, ejemplo cuando queres pagar
un cheque y te dice que no tiene fondos, pero no tenes puta idea de a
que cuenta se refiere

## 

http://selfdandi.com.ar

**Comment by mauriciopasquier** [comment]
se puede agregar el nombre de la cuenta en el mensaje de error
