### ISSUE TITLE
diferenciacion / descriptivo en recibos [internos|cobros|pagos]

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#34]
El descriptivo del recibo es una cadena con la causa que genera el movimiento de dineros
- Pago Factura # 
- Transferencia Banco-Caja
- Transferencia Caja-Caja
- Pago por Transferencia Bancaria
- Pago de Cheque Propio
- Pago de Retencion
- etc.

**Comment by fauno** [comment]
lo estabas pensando como un campo extra?

**Comment by m4tu5** [comment]
no lo tengo claro ... a un campo extra, o tal vez helpers que nos den la verba que queremos para los reportes por pantalla.

**Comment by mauriciopasquier** [comment]
En #83 los movimientos tienen `causa`
