### ISSUE TITLE
alerta alerta faltan los indices

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#340]
Necesitamos el alerta que putee al usuario si falta alguno de los indices actuales

**Comment by fauno** [comment]
aza notifications@github.com writes:

> Necesitamos el alerta que putee al usuario si falta alguno de los indices actuales

hasta ahora veniamos adivinandolo :P

## 

http://librevpn.org.ar

**Comment by mauriciopasquier** [comment]
Esto sería si no están cargados los seeds? No entendí me parece :(

**Comment by sudoaza** [comment]
aunque esten los seeds si no esta el indice actual que putee

2014-08-29 22:43 GMT-03:00 Mauricio Pasquier Juan notifications@github.com
:

**Comment by mauriciopasquier** [comment]
> aunque esten los seeds si no esta el indice actual que putee

pero no era que con los seeds todo andaba? Esto sería sólo si seleccionás que use el índice actual, o algo así?

**Comment by sudoaza** [comment]
si anda pero tiene que mostrar el alerta para recordarle al
usuario que tiene que cargar los indices de este mes, x mas
que ande.

**Comment by fauno** [comment]
vos decis un alerta que se vea siempre?

**Comment by sudoaza** [comment]
si,  joder al usuario hasta que cargue los 3 indices cada mes

**Comment by fauno** [comment]
me pongo con esto
