### ISSUE TITLE
unidades funcionales/facilitar la carga en bloque

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#349]
ahora, una vez se crea una uf, nos redirige a la vista en detalle de la UF, de ahí hay que volver al listado y desde ahí hacer click en el boton para crear una unidad nueva.

como esta carga se hace en bloque al inicio de una obra, estaria bueno buscar una forma de hacer esto mas simple (menos pantallas y clicks) ... tal vez un botón 'Agregar Otra Unidad' que sea condicional a mostrarse en la vista de UF cuando haya sido recién creada?

**Comment by sudoaza** [comment]
puede haber un boton de guardar y agregar otra o redirigir al listado de una

**Comment by fauno** [comment]
aza notifications@github.com writes:

> puede haber un boton de guardar y agregar otra o redirigir al listado de una

o un campo multiplicador que te cargue X unidades iguales

## 

:O

**Comment by m4tu5** [comment]
On 09/10/2014 05:28 PM, fauno wrote:

> o un campo multiplicador que te cargue X unidades iguales

creo que esto es menos util. en general va a ser un mix de lo que este
disponible y no necesariamente se repiten cosas iguales
