### ISSUE TITLE
unidades funcionales/boton 'listar unidades' es demasiado angosto

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#351]
el texto es mas ancho que el boton. hacer ancho variable o acortar el texto

/obras/#/unidades_funcionales/#

**Comment by mauriciopasquier** [comment]
acá no pongo "tests!" porque está jodido testear eso :P

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> acá no pongo "tests!" porque está jodido testear eso :P

tests de subjetividad!

## 

:O

**Comment by fauno** [comment]
este boton? yo lo veo bien...

![listar-unidades](https://cloud.githubusercontent.com/assets/468204/4338328/238a04a6-4018-11e4-9562-34297703cb0d.png)

**Comment by m4tu5** [comment]
no, este otro

![screenshot from 2014-09-19 14 01 58](https://cloud.githubusercontent.com/assets/5273876/4338992/b5a8036e-401e-11e4-9e3e-fbfdb1ebe52a.png)
