### ISSUE TITLE
indices/parado en la vista de indices, no me deja seleccionar una obra en el dropdown

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#352]

**Comment by mauriciopasquier** [comment]
tests!

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> tests!

etiquetas!

## 

:O

**Comment by fauno** [comment]
ahi esta la solucion, falta un test del menu segun el contexto, estoy en eso y hago pr
