### ISSUE TITLE
contrato de venta/ordenar cuotas por fecha a medida que se ingresan

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#353]
ingrese primero las coutas y desues un pago anticipado que quedo abajo y sucedia primero
![screenshot from 2014-09-10 17 25 21](https://cloud.githubusercontent.com/assets/5273876/4224821/a9c9c084-3928-11e4-8c16-e9f937b4b79b.png)

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> ingrese primero las coutas y desues un pago anticipado que quedo abajo y sucedia primero

me parece que va a ser mejor cuando lo rescribamos todo en rails

## 

http://librevpn.org.ar

**Comment by fauno** [comment]
aunque hay algunos js que permiten ordenar tablas por columna, que hacemos?

**Comment by fauno** [comment]
estoy probando con tablesorter pero no hace nada

http://tablesorter.com/docs/

pueden probar aca... http://naven.local:3000/obras/1/contratos_de_venta/new
