### ISSUE TITLE
contrato de venta/los montos de las coutas ingresadas no estan formateados

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#358]
no tienen separador de miles ni decimales, como las otras cantidades en el resto del formulario de nuevo contrato

![screenshot from 2014-09-17 18 46 10](https://cloud.githubusercontent.com/assets/5273876/4311940/39e9c336-3eb4-11e4-911d-8d901d48f54a.png)

**Comment by fauno** [comment]
coutas!
