### ISSUE TITLE
contrato de venta/un contrato creado en ARS se lista en USD

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#360]
- los valores de referencia de la UF y Cochera estaban en USD
- al crear el contrato, pase los selectores de moneda a ARS y se ven asi en la vista detallada del contrato (primera imagen)
- en el listado de contratos, se lista el monto total correcto, pero en USD (segunda imagen)

![screenshot from 2014-09-17 18 49 01](https://cloud.githubusercontent.com/assets/5273876/4312009/245b2dba-3eb5-11e4-8bf8-51dc59c045d2.png)

![screenshot from 2014-09-17 18 52 21](https://cloud.githubusercontent.com/assets/5273876/4312010/29269b54-3eb5-11e4-831c-ee59c2431a36.png)

**Comment by fauno** [comment]
se lo asigno a @sudoaza
