### ISSUE TITLE
unidades funcionales/mostrar valor de venta real para unidades vendidas

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#361]
en lugar del valor de referencia como se hace ahora

entonces, una UF que no se vendió se lista con precio de referencia, la que se vendió se muestra con el valor de venta real.

![screenshot from 2014-09-17 18 56 55](https://cloud.githubusercontent.com/assets/5273876/4312041/905b2c9a-3eb5-11e4-94c0-2181429c31cf.png)

**Comment by fauno** [comment]
este se cierra con #365
