### ISSUE TITLE
el contrato siempre se crea con la fecha actual

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#367]
``` ruby
@contrato.indice = @contrato.indice_para(Date.today)
```

con eso aunque estés cargando contratos atrasados se le asigna un indice que no es.  debería crearse con una fecha seleccionable o la fecha de la primera cuota, no?

ping @sudoaza @m4tu5

**Comment by fauno** [comment]
esto es en app/controllers/contratos_de_venta_controller.rb

**Comment by m4tu5** [comment]
me parece que hay 2 caminos.

1) poner la fecha del indice base como flotante, para que se elija de forma independiente al crear el contrato

2) poder elegir manualmente la fecha del contrato y deribar de ahí la fecha del indice base.

o hasta hacer las 2 cosas ... tener una fecha para el contrato (que creo que no viene mal) y por otro lado, tener la fecha para el indice base

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> me parece que hay 2 caminos.
> 
> 1) poner la fecha del indice base como flotante, para que se elija de
> forma independiente al crear el contrato
> 
> 2) poder elegir manualmente la fecha del contrato y deribar de ahí la
> fecha del indice base.
> 
> o hasta hacer las 2 cosas ... tener una fecha para el contrato (que
> creo que no viene mal) y por otro lado, tener la fecha para el indice
> base

eso implicaría tener un selector de fecha en contratos y un select de
indices con todos los indices disponibles (o que se filtre por el año
del contrato... o te sugiera el indice adecuado a la fecha del
contrato... y qué pasa con los índices que todavía no existen?)

## 

http://partidopirata.com.ar

**Comment by fauno** [comment]
digo, era más simple cambiarlo por 

``` ruby
@contrato.indice = @contrato.indice_para(@contrato.cuotas.first.vencimiento)
```

**Comment by m4tu5** [comment]
eso solo funcionaría en contratos en que la primera cuota es siempre un adelanto y se paga al momento de la firma.

para una venta sin adelanto y la primera cuota la pagas a los 90 días, la primera cuota hay que indexarla vs. la base del contrato ... no tienen el mismo indice

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> eso solo funcionaría en contratos en que la primera cuota es siempre
> un adelanto y se paga al momento de la firma.
> 
> para una venta sin adelanto y la primera cuota la pagas a los 90 días,
> la primera cuota hay que indexarla vs. la base del contrato ... no
> tienen el mismo indice

entonces por ahora lo mas simple es que el contrato tenga fecha y ya

## 

:{
