### ISSUE TITLE
retenciones se pueden aplicar a mas de un recibo

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#375]
dice @m4tu5 en #370:

muy bien. ya que estamos con las verificaciones de facturas-recibos-retenciones, creo que por ahí supo haber un issue que hablaba de que las retenciones se podían aplicar a la misma factura más de una vez

o sea, una factura que se paga con 2 recibos, se podía agregar la misma retención a cada recibo ... lo que es claramente incorrecto. solo se puede aplicar una retención una vez y despues se quema y sale del juego

lo querés verificar? :p

**Comment by fauno** [comment]
tiene relacion con lo que está haciendo @sudoaza ?

**Comment by sudoaza** [comment]
esto hay que testearlo nomas, pero cuando la retencion esta aplicada ya no te deja aplicarla asi q no es un bug sino covertura de testeo :P

aza

**Comment by sudoaza** [comment]
Esto no pasa
