### ISSUE TITLE
rutas - cajas

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#38]
`rake routes CONTROLLER=cajas`:

```
    obra_cajas GET    /obras/:obra_id/cajas(.:format)          cajas#index
               POST   /obras/:obra_id/cajas(.:format)          cajas#create
 new_obra_caja GET    /obras/:obra_id/cajas/new(.:format)      cajas#new
edit_obra_caja GET    /obras/:obra_id/cajas/:id/edit(.:format) cajas#edit
     obra_caja GET    /obras/:obra_id/cajas/:id(.:format)      cajas#show
               PATCH  /obras/:obra_id/cajas/:id(.:format)      cajas#update
               PUT    /obras/:obra_id/cajas/:id(.:format)      cajas#update
               DELETE /obras/:obra_id/cajas/:id(.:format)      cajas#destroy
```

Acá cajas se accede **siempre** a través de una obra. Es así?

**Comment by m4tu5** [comment]
las cajas siempre estan asociadas a las obras, pero no siempre se acceden a traves de la obra

por ejemplo, al listar todas las cajas de un cierto tipo, como las de Of.Central (o como lo hayamos llamado) o listar todas las cajas de Of.Obra, sin importar a que obra pertenecen.

**Comment by mauriciopasquier** [comment]
entonces las desanido y ya, quedarían igual que en cuentas (#42)

**Comment by fauno** [comment]
che quise desanidar esto pero hay obra_cajas_path por todos lados :3
