### ISSUE TITLE
Agregar tilde al link de Retencion

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#380]
En el listado de movimientos de los recibos el link a la retencion no tiene tilde, agregarselo y arreglar el test de integracion correspondiente. 

Dice @mauriciopasquier que existe un link en algun PR de @m4tu5 que dice como arreglarlo.

**Comment by m4tu5** [comment]
es el #348 ... no encuentro el comentario de mpj con los links que me pasó donde explicaba el tema, pero mira el archivo config/locales/cp.yml ... ahí está la posta ... podés cambiar el nombre con que se muestra un campo de una tabla, sin tener que tocar la tabla

**Comment by m4tu5** [comment]
alguien tiene un cheat sheet de ActiveRecord y localizacion ... voy 20 intentos y no lo saco
