### ISSUE TITLE
factura nueva / en error, se pierde la situación

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#381]
Al querer guardar una factura nueva que contenga un error, se pierde la situación de la URI (ej: 
`/new?situacion=cobro`) y ya no se puede guardar la factura incluso después de corregir el error inicial

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> Al querer guardar una factura nueva que contenga un error, se pierde
> la situación de la URI (ej: `/new?situacion=cobro`) y ya no se puede
> guardar la factura incluso después de corregir el error inicial

no se ponía como un input oculto?

## 

:>
