### ISSUE TITLE
rutas - facturas

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#39]
`rake routes CONTROLLER=facturas`:

```
cobros_facturas GET    /facturas/cobros(.:format)   facturas#cobros
 pagos_facturas GET    /facturas/pagos(.:format)    facturas#pagos
       facturas GET    /facturas(.:format)          facturas#index
                POST   /facturas(.:format)          facturas#create
    new_factura GET    /facturas/new(.:format)      facturas#new
   edit_factura GET    /facturas/:id/edit(.:format) facturas#edit
        factura GET    /facturas/:id(.:format)      facturas#show
                PATCH  /facturas/:id(.:format)      facturas#update
                PUT    /facturas/:id(.:format)      facturas#update
                DELETE /facturas/:id(.:format)      facturas#destroy
```

Ya lo dije antes, pero para mí, `facturas/cobros` y `facturas/pagos` se resuelve
mejor con un filtro por parámetros (`facturas` y `facturas?tipo=pagos` van al
index y se filtran ahí mismo, es una boludez y no tenemos que andar haciendo
acciones de más y renderizando otras). Además es más REST.. si es sólo un
filtro de las facturas.

Otra cosa: las facturas se ven agrupadas bajo la obra en algún momento?
O sea interesa ver las facturas relacionadas con una obra, o sólo se manejan
así como objetos independientes?

**Comment by m4tu5** [comment]
Me parece bien cambiar el path por los filtros si es mas ordenado ... puede traer algo de quilombo en la navegacion de formularios a recibos y viceversa, pero nada muy grave a esta altura.

Si esta bien que podamos ver las facturas por obra, sta vista será más útil para entender la situación financiera de la obra.

El dia-a-dia se manejan las facturas como objetos independientes, ya que identificando al proveedor y el numero de facutura (!= id) alcanza para saber que estas pagando o cobrando correctamente.

**Comment by mauriciopasquier** [comment]
Y **Nueva factura**? Dónde va? Desde la obra, o seleccionás la obra en la creación?

**Comment by m4tu5** [comment]
De momento no lo habia pensado, y me da lo mismo, porque el dropdown de obras no tendría mas que 4 a 5 renglones.

Creo que si hay una obra seleccionada en las vistas, la tomaría como valor por defecto para el dropdown, y de no haber nada, dejaría esto en blanco para forzar a que elijan una.

Esto no me parece hacerlo para los recibos (pagos/cobros) porque pueden haber cientos de facturas, lo de da lugar a error humano al seleccionar.

**Comment by mauriciopasquier** [comment]
Entonces mejor que la obra siempre sea un valor a seleccionar en donde haga falta asociar. Llegado el caso de que esto sea incómodo, se puede hacer lo de la sesión (**Trabajar con esta obra**) y usarla como valor por default en los drops.

**Comment by fauno** [comment]
hay un commit revertido con las rutas prolijas pero se rompian casi todas las vistas, lo deje para mas adelante

**Comment by m4tu5** [comment]
ok, pasa el issue a un nuevo milestone, asi no nos olvidamos
