### ISSUE TITLE
Revisar ortografía (tildes) de Índices

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#397]
Revisar que las vistas muestrén Índice con tilde en links y menciones.

Hay ejemplos de como localizar los nombre de tablas en #396

**Comment by fauno** [comment]
no era que en mayúscula no hace falta la tilde?

pd: se acuerdan cuando la ch estaba en el alfabeto?

**Comment by m4tu5** [comment]
On 10/02/2014 01:20 PM, fauno wrote:

> no era que en mayúscula no hace falta la tilde?

no hace falta, pero tampoco está mal ... es optativo y
me da la impresión que la mayoría opta por no usarlo

**Comment by fauno** [comment]
ya lo arregle

**Comment by mauriciopasquier** [comment]
yo uso
