### ISSUE TITLE
rutas - recibos

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#40]
`rake routes CONTROLLER=recibos`:

```
    factura_recibos GET    /facturas/:factura_id/recibos(.:format)          recibos#index
                    POST   /facturas/:factura_id/recibos(.:format)          recibos#create
 new_factura_recibo GET    /facturas/:factura_id/recibos/new(.:format)      recibos#new
edit_factura_recibo GET    /facturas/:factura_id/recibos/:id/edit(.:format) recibos#edit
     factura_recibo GET    /facturas/:factura_id/recibos/:id(.:format)      recibos#show
                    PATCH  /facturas/:factura_id/recibos/:id(.:format)      recibos#update
                    PUT    /facturas/:factura_id/recibos/:id(.:format)      recibos#update
                    DELETE /facturas/:factura_id/recibos/:id(.:format)      recibos#destroy
     cobros_recibos GET    /recibos/cobros(.:format)                        recibos#cobros
      pagos_recibos GET    /recibos/pagos(.:format)                         recibos#pagos
            recibos GET    /recibos(.:format)                               recibos#index
                    POST   /recibos(.:format)                               recibos#create
         new_recibo GET    /recibos/new(.:format)                           recibos#new
        edit_recibo GET    /recibos/:id/edit(.:format)                      recibos#edit
             recibo GET    /recibos/:id(.:format)                           recibos#show
                    PATCH  /recibos/:id(.:format)                           recibos#update
                    PUT    /recibos/:id(.:format)                           recibos#update
                    DELETE /recibos/:id(.:format)                           recibos#destroy
```

este sale en el pull #33, pero seguro que no hay ninguna otra extra?

```
         new_recibo GET    /recibos/new(.:format)                           recibos#new
```

por ejemplo, me da la impresión de que no quieren usar las rutas anidadas.
Entonces, las sacamos o las aplanamos?

Con shallow (aplanar) en facturas queda así:

```
   factura_recibos GET    /facturas/:factura_id/recibos(.:format)     recibos#index
                   POST   /facturas/:factura_id/recibos(.:format)     recibos#create
new_factura_recibo GET    /facturas/:factura_id/recibos/new(.:format) recibos#new
       edit_recibo GET    /recibos/:id/edit(.:format)                 recibos#edit
            recibo GET    /recibos/:id(.:format)                      recibos#show
                   PATCH  /recibos/:id(.:format)                      recibos#update
                   PUT    /recibos/:id(.:format)                      recibos#update
                   DELETE /recibos/:id(.:format)                      recibos#destroy
```

Pero ustedes quieren listas de recibos generales (un index de todos los
recibos, no?) asique las desanidaría y ya.

Acá también sacaría pagos y cobros.

**Comment by mauriciopasquier** [comment]
Pregunto sobre recibos que por lo que estoy viendo deberían ser solamente internos. No creás un nuevo recibo desde la interfáz, pagás una factura (por ejemplo). O ustedes ven a la gente yendo a **Recibos** -> **Nuevo**, **Editar**, **Borrar**, etc? ?

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> por ejemplo, me da la impresión de que no quieren usar las rutas anidadas.
> Entonces, las sacamos o las aplanamos?

tienen que estar anidadas para listar y crear recibos de una factura,
desanidadas para ver listados generales de recibos (pagos, cobros e
internos)

> Pero ustedes quieren listas de recibos generales (un index de todos los
> recibos, no?) asique las desanidaría y ya.

ok

> Acá también sacaría pagos y cobros.

no sep

## 

.oÓ)

**Comment by mauriciopasquier** [comment]
Es una cuestión de interfaz más que de funcionalidad. La única ventaja funcional es que podés cargar el modelo padre con el id. Además, de nuevo.. me parece que es más claro un **Pagar factura** que un **Nuevo recibo**, o algo así. Sea como sea, necesitamos interfaces que nos hagan entender :P

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> Pregunto sobre recibos que por lo que estoy viendo deberían ser
> solamente internos. No creás un nuevo recibo desde la interfáz, pagás
> una factura (por ejemplo). O ustedes ven a la gente yendo a
> **Recibos** -> **Nuevo**, **Editar**, **Borrar**, etc? ?

las facturas se cancelan con recibos que generan movimientos en
distintos medios (caja, cheque, transferencia, etc).  lo que vino
haciendo ahora @m4tu5 es que para cancelar la factura le creás un recibo
con un monto determinado, ahora le faltaba que a ese recibo le asocies
los movimientos que te genera internamente.

por eso te decia ayer que veiamos movimientos como las flechas del
diagrama pero vos decias que habias hecho un auxiliar de cajas nada mas.

## 

.oÓ)

**Comment by m4tu5** [comment]
lo de las rutas me parece que es indiferente ... si se ve o no el id de la factura al acceder al recibo.

lo de la navegacion es lo mas critico, creo.
por ejemplo "recibo -> nuevo" no existe, podes ver los recibos directamente, pero para crear uno nuevo, primero tenes que ubicar la factura y desde dentro de la factura crear el nuevo recibo, de esta forma minimizamos el error de asiciar pagos a facturas equivocadas.

me parece bien cambiar nuevo recibo por nuevo cobro/pago, la verdad es que cuando empecé con al gui no hubiese sabido como hacerlo ... pero ahora si :)

**Comment by mauriciopasquier** [comment]
Yo creo que tenemos que simplificar y resimplificar las vistas, si no hay razón para crear un recibo a mano (siempre se asocia a algún movimiento, factura, etc) es un artefacto que genera el sistema, el sistema sabe cómo generarlo y no el usuario.

**Comment by m4tu5** [comment]
totalmente de acuerdo. el registro es algo que genera el sistema en base a operaciones más básicas.

Lo único que si debe poder elegir el usuario, es la fecha del recibo, que tiene que ser igual a la de los movimientos que lo componen (o sea, o se elije una o la otra) y listo.

Yo pensaba que al generar un nuevo pago/cobro (lo que hoy se llama Nuevo Recibo), se elije la fecha ahí una sola vez, y de ahí, se le transfiere a todos los movimientos que lo compongan (que pudiendo ser varios, ahora trabajo).

**Comment by mauriciopasquier** [comment]
es realista algo como esto?
1. **Nuevo pago**
2. checks para los tipos de pago
   - check para efectivo, con su textbox por el monto
   - check para transferencia, con su monto y su cuenta destino (ponele)
   - otros tipos de pago
3. **Pagar**

El punto 2 también podría ser "Pago parcial" y ahí elegir, serviría también para hacer pagos en diferentes momentos sobre la misma factura

**Comment by m4tu5** [comment]
Lo de tener los medios de pago listados con checks me parece bien.

Lo de otros tipo de pago puede ser algo mas complejo. Si fuese por Cheque, hay que poner info adicional que solo se usa para esa categoria (ej: banco, numero de cheque, fecha emision, fecha vencimiento, etc.). Es similar para las retenciones.

Yo lo que había pensado es en un popup que se vea al hacer click en 'Nuevo Movimiento' de un Recibo, que muestre diferentes pestañas. Que solo permita completar una pestaña (movimiento) a la vez (creo que varias a la vez es para quilombo). Se llama tantas veces como sea necesario para completar el monto pagado/cobrado

La mayoría de los pagos/cobros van a ser parciales, así que veamos que el gestionar esto sea igual de simple que un pago total.

**Comment by mauriciopasquier** [comment]
Un popup?? Te quitamos ya mismo la licencia de front end developer.
