### ISSUE TITLE
verificar que las migraciones del modulo de ventas no afecten los datos en producción

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#404]
ultima migración aplicada:
`20140407045034_add_importe_cache_to_recibos.rb`

**Comment by fauno** [comment]
ya deployeé la demo, fijate ahí

**Comment by m4tu5** [comment]
no me parece la forma de hacerlo, el fijarse a mano.

lo suyo sería revisar las nuevas migraciones, y ver que todas tengan valores por default, o que creen valores a los registros ya existentes en las tablas, no?

**Comment by fauno** [comment]
como cuando le cambiaste los nombres por defecto a todas las cajas sin migrar las que existían? :P

**Comment by m4tu5** [comment]
claro, ese es el ejemplo de lo que NO hay que hacer

**Comment by mauriciopasquier** [comment]
"lo suyo"? De quién?
