### ISSUE TITLE
js y css ordenados

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#41]
> Lo intente asi para el js del selector de fechas (date-picker) y no funciono.
> Primero intente en facturas.js, despues en application.js (porque el mismo
> script vale también para los recibos). No funciono en ninguno de los dos
> lugares. Por eso ahora estos scripts estan en los .erb de las vistas

**Comment by fauno** [comment]
a donde era que habia que moverlos?

**Comment by m4tu5** [comment]
a app/assets/{javascript|stylesheets}

pero no a application.{js|css} sino dentro de la vista que corresponda. si es algo general, entonces armar un layout.{js.coffee|css}

**Comment by fauno** [comment]
siempre la asignacion es unipersonal... estoy con esto

**Comment by fauno** [comment]
uh, tengo que aprender coffee script?

**Comment by m4tu5** [comment]
Mira la página coffee2js, traduce de ida y vuelta y a mi me ayudó para los scripts que hay ahora. 

Lo otro es que en su momento no me funciono poner los scripts en assets, espero tengas mejor suerte. 

Que Java este contigo

**Comment by fauno** [comment]
jaja ahi esta, ahora muevo el resto

**Comment by fauno** [comment]
como hago con los js que llaman a elementos con nombres dinamicos?  por ejemplo en facturas/edit.html.erb

**Comment by mauriciopasquier** [comment]
Por ahí la pregunta es "por qué usar un botón fuera del formulario?". Si hay una buena respuesta, en ese caso podrías cambiar el id o clase usado. No tiene mucha razón de ser elegir por id si va a haber un sólo form (o un sólo form con clase `.editar` en esa vista).

PD: ya que estás sacás todo eso de los campos ocultos? Código limpio ftw

**Comment by mauriciopasquier** [comment]
> uh, tengo que aprender coffee script?

sí

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> Por ahí la pregunta es "por qué usar un botón fuera del
> formulario?". Si hay una buena respuesta, en ese caso podrías cambiar

ask @m4tu5

> el id o clase usado. No tiene mucha razón de ser elegir por id si va a
> haber un sólo form (o un sólo form con clase `.editar` en esa vista).

clah

> PD: ya que estás sacás todo eso de los campos ocultos? Código limpio ftw

lo del debug?

## 

http://utopia.partidopirata.com.ar/

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> > uh, tengo que aprender coffee script?
> 
> sí

si borro los .js.coffee puedo usar .js normal, después si hace falta lo
mudamos a coffee :\

## 

http://utopia.partidopirata.com.ar/

**Comment by mauriciopasquier** [comment]
On Mon, Mar 03, 2014 at 05:52:45PM -0800, fauno wrote:

> Mauricio Pasquier Juan notifications@github.com writes:
> 
> > > uh, tengo que aprender coffee script?
> > 
> > sí
> 
> si borro los .js.coffee puedo usar .js normal, después si hace falta lo
> mudamos a coffee :\

I </3 dirty hacks

##

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> On Mon, Mar 03, 2014 at 05:52:45PM -0800, fauno wrote:
> 
> > Mauricio Pasquier Juan notifications@github.com writes:
> > 
> > > > uh, tengo que aprender coffee script?
> > > 
> > > sí
> > 
> > si borro los .js.coffee puedo usar .js normal, después si hace falta lo
> > mudamos a coffee :\
> 
> I </3 dirty hacks

te dije que me voy a hacer una remera?

## 

http://selfdandi.com.ar

**Comment by mauriciopasquier** [comment]
On Mon, Mar 03, 2014 at 06:02:45PM -0800, fauno wrote:

> Mauricio Pasquier Juan notifications@github.com writes:
> 
> > On Mon, Mar 03, 2014 at 05:52:45PM -0800, fauno wrote:
> > 
> > > Mauricio Pasquier Juan notifications@github.com writes:
> > > 
> > > > > uh, tengo que aprender coffee script?
> > > > 
> > > > sí
> > > 
> > > si borro los .js.coffee puedo usar .js normal, después si hace falta lo
> > > mudamos a coffee :\
> > 
> > I </3 dirty hacks
> 
> te dije que me voy a hacer una remera?

notaste que es un corazón roto? posta.. quién está boludeando a quién?

##

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> > > I </3 dirty hacks
> > 
> > te dije que me voy a hacer una remera?
> 
> notaste que es un corazón roto?

si

> posta.. quién está boludeando a quién?
- no veo qué tiene de dirty usar js en lugar de coffee cuando no tengo
  tiempo de aprenderlo
- si no te gusta nada de lo que hago es la única opción que me das
  (vease http://es.wikipedia.org/wiki/Doble_v%C3%ADnculo )

## 

http://selfdandi.com.ar

**Comment by fauno** [comment]
@m4tu5 creo que ahi ya esta, te fijas si no rompi nada?

**Comment by mauriciopasquier** [comment]
Pedirme que te diga si estás haciendo cosas mal (o chapuceramente) para después ignorarlo diciendo que no te dejo hacer nada es un doble vínculo también.

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> Pedirme que te diga si estás haciendo cosas mal (o chapuceramente)
> para después ignorarlo diciendo que no te dejo hacer nada es un doble
> vínculo también.

probemos otra cosa entonces \o/

## 

.oÓ)
