### ISSUE TITLE
Mostrar balances mensuales

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#413]
Poder filtrar los listados de facturas y recibos por mes y año.  También mostrar los balances por mes y año.

**Comment by m4tu5** [comment]
A que le llamas balance mensual? Se me confunde con un balance contable e imagino que te referís a otra cosa.

**Comment by fauno** [comment]
la pantalla principal de la obra, no me acuerdo como le pusimos.  ahora muestra totales por obra, habria que hacerlo por obra y mes

**Comment by m4tu5** [comment]
creo que lo podemos hacer sin plazo temporal, y que al hacer click ahí, nos lleve a una pantalla con el detalle.

pensá que mes a mes se hace un depósito en la afip para compensar esa cuenta, y que de alguna manera tendríamos que tener en cuenta para el balance.

**Comment by m4tu5** [comment]
ah. me confundi de issue,  y mande fruta.

uhm, esa pantalla no esta pensada para verse por mes y no estoy seguro de que haga sentido. Tal vez si la parte de las facturzas, pero no así la parte de las cuentas bancarias ... pero podemos pensar en algo, seguro.
