### ISSUE TITLE
Mostrar el IVA de compras y ventas en los balances

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#414]
Para subir a la AFIP es necesario tener una suma mensual del IVA

**Comment by m4tu5** [comment]
Esta suma la podemos poner en el vistado de resumen de la empresa, como con las cajas/cuentas o como con las factuas de cobro/pago

Creo que conviene tener diferenciado el IVA Compras del IVA Ventas y luego la suma de ambos.

**Comment by fauno** [comment]
eso mismo pero dicho en tus palabras :P
