### ISSUE TITLE
Implementar retiros

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#415]
Los retiros son lo que cobran las socias de una coop y hay que verlo por separado.  Por ahora lo resolvimos con facturas de pago tipo P, por lo que al implementarlo hay que hacer una migración que las convierta a retiros.

Además deben generar un recibo imprimible para firmar.

**Comment by m4tu5** [comment]
Un retiro es una factura de pago, y una socia es un tercero.

Si quieren, podríamos programar un boton para hacer un retiro que genere la factura (de tipo P o lo que sea) necesaria y que solo permita asociarse a terceras de tipo socias.

No tocaría el flujo de dineros que tenemos en el core. Eso funciona bien como está y no es necesario hacer exepciones para esto, me parece.
