### ISSUE TITLE
Licencia?

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#417]
usemos AGPLv3 :P
- [ ] Agregar el texto de la licencia en el archivo LICENSE
- [ ] Agregar el header de copyright en todos los archivos
- [ ] Para cumplir con los términos de la AGPL hay que poner un link a la descarga del código fuente que se está sirviendo.  Voy a buscar a ver si hay algo para capistrano/rails, una vez vi un plugin de django que creaba un tar.gz del deploy y te permitía descargarlo.

**Comment by sudoaza** [comment]
bueno  :P

**Comment by fauno** [comment]
pongo los cambios que habría que hacer

**Comment by fauno** [comment]
o sino un link configurable al git
