### ISSUE TITLE
Registrar horas por proyecto

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#419]
La onda sería ir registrando el tiempo proyectado y dedicado por proyecto, para tener un balance interno.  También podría sacar un promedio de cuánto se cobró por hora.

Esto requeriría que haya un modelo Proyecto (no Obra) al que se le asocien Facturas.

**Comment by m4tu5** [comment]
Y las horas las reportas cuando cargas la factura?
O cargas facturas contra proyecto y horas contra proyecto, pero en otro lado?

Tengo una buena idea de una interfase de carga de horas para proyectos.

**Comment by fauno** [comment]
se cargarían en el proyecto supongo, por cada socia de la coop ponele.  aza dijo que tenia algo en mente pero nunca contó qué :P

**Comment by fauno** [comment]
@sudoaza

**Comment by sudoaza** [comment]
yo toy haciendo lo de cargar horas en proyectos y tareas, no lo toy haciendo integrado a cp pero si en rails... puede servir. Mi interfaz es mejor q la de matus :P y viene con calendario biodinamico q te dice cuando te estresaste xD

**Comment by fauno** [comment]
si hacés que le pueda importar los dumps de hamster te lo uso :P

**Comment by sudoaza** [comment]
sisi se va a tenre q poder parece :P
