### ISSUE TITLE
Precargar el numero de factura

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#422]
cuando cargo el tipo de factura (A,B,C...) que me cargue el siguiente numero de factura posible, pero q me deje cambialo si quiero

**Comment by m4tu5** [comment]
en los ERP lo que hacen es tener autonumeradores configurables para los diferentes documentos (recibos, facturas, etc)

cada tipo tiene una numeración independiente, y desde una vista de configuración podés configurar cuál es el próximo valor a utilizar (siempre que no sobreescriba los que ya existen)

lo que tenemos que ver, es de diferenciar las facturas que emitimos, de las que recibimos. Las que emitimos está bien que las autonumeremos, pero las que recibimos, llevan el número del cliente. Podríamos poner autonumerador en facturas de ciertos tipos que recibimos (como las de las extracciones que hacemos nosotros, que no son facturas reales).

Ideas para considerar cuando nos pongamos con esto.
