### ISSUE TITLE
generar datos de relleno piolas

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#44]
dummy data no funcionó, vamos a probar con factory girl así @m4tu5 tiene algo lindo para mostrar a $cliente

**Comment by mauriciopasquier** [comment]
On Mon, Mar 03, 2014 at 08:11:59PM -0800, fauno wrote:

> dummy data no funcionó, vamos a probar con factory girl así @m4tu5 tiene algo lindo para mostrar a $cliente

arreglen los yml de dummy data y listo! factory girl hace datos correctos si
las factories están correctas pero no hace magia, hay que hacer la tarea de
dummy data a mano y combinarlo con otra gema que guarde en yml. Como ya dije el
viernes, ya avanzaron por este lado.. sólo tienen que dejar lindos los yml que
ya se generaron

/me siempre habla al pedo

##

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> viernes, ya avanzaron por este lado.. sólo tienen que dejar lindos los
> yml que ya se generaron
> 
> /me siempre habla al pedo

@m4tu5 vos te acordabas de esto?

## 

http://hackcoop.com.ar

**Comment by m4tu5** [comment]
Si, pero no estoy de acuerdo con mpj (que también hablamos el viernes)

No es más fácil corregir la data a mano. Es mucha data y es mucho tiempo en una actividad de edición manual sin aprender nada que nos sirva a futuro

Además, corregir lo que hizo dummy sólo nos da facturas, recibos, obras y poco más.

Lo mejor es aprender a generar buenos datos así después los podemos usar con los nuevos módulos y las nuevas cosas que vayamos creando.

**Comment by sudoaza** [comment]
Ahi los edite fijense el commit 49c2fe9

**Comment by sudoaza** [comment]
Si luego tenemos que generar mas data creo que modificando este archivo de Dummy podemos autogenerarlo mas piola https://github.com/goncalossilva/dummy/blob/master/lib/dummy.rb

**Comment by fauno** [comment]
aza notifications@github.com writes:

> Ahi los edite fijense el commit 49c2fe9 

joya en un rato reviso, pero no comitees en develop!  hacete una rama
(mira el CONTRIBUTING.md, igual estoy hablando sin saber, ayer vi que
habias comiteado una linea a develop)

si pones #numero_del_issue en el titulo de un commit se referencia solo
cuando pusheas ;)

## 

http://wiki.hackcoop.com.ar

**Comment by sudoaza** [comment]
Si ya se, los #encoding si los mande de una xq eran una boludez, de este
me di cuenta cuando ya habia comiteado

**Comment by fauno** [comment]
no se puede guardar la base de datos que generan el rake test?
