### ISSUE TITLE
monedas?

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#49]
las vistas no están tomando en cuenta la moneda de los importes no?

**Comment by fauno** [comment]
http://stackoverflow.com/questions/7988882/setting-currency-with-form-select-with-money-gem

medio viejardo pero tal vez sirve

**Comment by fauno** [comment]
o que una caja acepte un solo tipo de moneda, dijimos con @m4tu5 revisarlo cuando refactoricemos cajas y cuentas (otra vez)

**Comment by m4tu5** [comment]
ya esta la parte grafica de esto en feature/mas-correcciones que ahora subo

falta agregar un selector de moneda en los formularios. creo que solo en facturas/_form, ya que el resto deriva de ahi. tambien en el formulario para transferencias/cambios-de-moneda cuando se haga.
