### ISSUE TITLE
Balances

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#50]
Los balances tendrían que incluir según situación
- Todos los saldos de facturas
- Todos los montos de recibos
- Todos los montos de cheques en chequera
- Todos los montos de movimientos en distintas monedas, por caja

Los movimientos deberían tener situación también...

**Comment by m4tu5** [comment]
Si, lo que decis es correcto, aunque no creo que vayamos a usar todos en el mismo reporte.

Pero si, siempre nos interesa poder ver en forma agregada y detallada listados de elementos similares aunque pertenezcan a diferentes situaciones (facturas, recibos, movimientos, cheques)

Tambien nos interesa poder agregar a diferentes niveles. Por ejemplo, para un tercero en particular, poder ver todas las facturas, cuanto se le debe (saldo), listar todos los recibos, los cheques que tiene nuestros que aun no se hayan pagado, etc.

**Comment by fauno** [comment]
en feature/saldo-general estoy laburando en esto (hay alguna sintaxis para vincular a la rama?)

**Comment by fauno** [comment]
aca se ve como quedó por ahora http://siafa.hackcoop.com.ar/obras/1

**Comment by m4tu5** [comment]
lo que veo no muestra nada ... cambiaste de rama en naven.local?

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> lo que veo no muestra nada ... cambiaste de rama en naven.local?

ah si, ahora tiene que andar

## 

http://hackcoop.com.ar

**Comment by m4tu5** [comment]
Va tomando forma.
No veo las cuentas ni las chequeras, que no deben mezclarse con las cajas de efectivo. Las estas sumando a todas o no las estas calculando de momento?

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> Va tomando forma.  No veo las cuentas ni las chequeras, que no deben
> mezclarse con las cajas de efectivo. Las estas sumando a todas o no
> las estas calculando de momento?

me dijiste un total de todas las cajas ¬¬

## 

http://hackcoop.com.ar

**Comment by m4tu5** [comment]
aun no se que significan estos ¬¬

pero te dije total de todas las cajas, total de cuentas, chequera propia, de 3ros y retenciones ... mira el log ;p

mpj tenia razon en que tarde o temprano llamar Caja a la clase y a uno de los objetos hijos nos iba a complicar la vida

**Comment by mauriciopasquier** [comment]
On Tue, Mar 25, 2014 at 09:36:22PM -0700, m4tu5 wrote:

> aun no se que significan estos ¬¬
> 
> pero te dije total de todas las cajas, total de cuentas, chequera propia, de 3ros y retenciones ... mira el log ;p
> 
> mpj tenia razon en que tarde o temprano llamar Caja a la clase y a uno de los objetos hijos nos iba a complicar la vida

mpj tiene razón, hay clases entre la gente ♬

##

**Comment by m4tu5** [comment]
me falla la vista del home page, por un tema de calculo de saldos cuando hay facturas en USD.

@fauno, fijate de empezar a tomar en cuenta las monedas en todos los calculos.

**Comment by fauno** [comment]
¬¬ cara de sospecha o me estás cargando

**Comment by fauno** [comment]
entonces total de cajas por tipo

**Comment by fauno** [comment]
ahi pushee el total de facturas por moneda

**Comment by m4tu5** [comment]
me acorde de otros saldos que estan faltando ... por un lado, el de IVA ... ahí necesitamos saber el total del IVA que cobramos (fac.cobro) menos el IVA que pagamos (fac.pago) ... este monto, aunque este en nuestas cajas, en realidad pertenece a la AFIP.

no se bien como hacer con las facturas que estan pagadas/cobradas a medias, pero creo que una vez emitidas, las hayas cobrado o no, le debes el dinero al estado, asi que sumemoslas completas.

la idea es que cuando se haga un pago al estado por el IVA que se le debe, se haga una factura de tipo I(mpuesto) donde solo se pague IVA, ajustando el saldo a cero (esta factura se ingresará manualmente).

el otro saldo que no estamos viendo es el de lo que hay por cobrar y pagar, neto de IVA (sin IVA). o sea, la suma de los importes netos, no los totales.

**Comment by fauno** [comment]
sigo con esto

**Comment by fauno** [comment]
en feature/balanceo-de-tu-vieja
