### ISSUE TITLE
js @ assets no funcionan en Chromium

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#51]
Los scripts en assets no funcionan cuando se usa Chrome/Chromium (si funcionan en FireFox).

Los mismos scripts funcionaban en ambos navegadores cuando estaban incluidos en la vista.

relacionado con #41 y probablemente con el problema que teniamos al renderizar nested-partials (que también se veían bien en FireFox y no en Chrome)

@mauriciopasquier , nos podras dar una mano con esto que ya venimos dando muchas vueltas y no logramos solucionarlo

**Comment by mauriciopasquier** [comment]
On Sun, Mar 09, 2014 at 07:56:24AM -0700, m4tu5 wrote:

> Los scripts en assets no funcionan cuando se usa Chrome/Chromium (si funcionan en FireFox).
> 
> Los mismos scripts funcionaban en ambos navegadores cuando estaban incluidos en la vista.
> 
> relacionado con #41 y probablemente con el problema que teniamos al renderizar nested-partials (que también se veían bien en FireFox y no en Chrome)
> 
> @mauriciopasquier , nos podras dar una mano con esto que ya venimos dando muchas vueltas y no logramos solucionarlo

qué tan prioritario es que se puedan clickear las filas de la tabla en
cualquier lado en vez de poner como link el texto de las celdas?

##

**Comment by m4tu5** [comment]
On 03/09/2014 12:26 PM, Mauricio Pasquier Juan wrote:

> > @mauriciopasquier , nos podras dar una mano con esto que ya venimos
> > dando muchas vueltas y no logramos solucionarlo
> 
> qué tan prioritario es que se puedan clickear las filas de la tabla en
> cualquier lado en vez de poner como link el texto de las celdas?

es menos prioritario que terminar las retenciones.

el problema de fondo no es que no se pueda clickear en el renglon, sino
que lo que hacemos no es compatible en los diferentes navegadores.

dado que chrome es un navegador que tiene una base amplia de usuarios,
me gustaría que la app lo soporte. Imagino que habras desarrollado para
gente que usa chrome en el pasado y tal vez sepas como solucionar estas
cosas. pero bueno, si no sabes por donde puede estar el problema y ves
que te va a llevar horas solucionarlo, dejalos y vemos de que los
usuarios arranquen usando firefox exclusivamente.

**Comment by mauriciopasquier** [comment]
On Sun, Mar 09, 2014 at 09:03:31AM -0700, m4tu5 wrote:

> On 03/09/2014 12:26 PM, Mauricio Pasquier Juan wrote:
> 
> > > @mauriciopasquier , nos podras dar una mano con esto que ya venimos
> > > dando muchas vueltas y no logramos solucionarlo
> > 
> > qué tan prioritario es que se puedan clickear las filas de la tabla en
> > cualquier lado en vez de poner como link el texto de las celdas?
> 
> es menos prioritario que terminar las retenciones.
> 
> el problema de fondo no es que no se pueda clickear en el renglon, sino
> que lo que hacemos no es compatible en los diferentes navegadores.
> 
> dado que chrome es un navegador que tiene una base amplia de usuarios,
> me gustaría que la app lo soporte. Imagino que habras desarrollado para
> gente que usa chrome en el pasado y tal vez sepas como solucionar estas
> cosas. pero bueno, si no sabes por donde puede estar el problema y ves
> que te va a llevar horas solucionarlo, dejalos y vemos de que los
> usuarios arranquen usando firefox exclusivamente.

el problema no es que soportemos chrome o no, es que hicimos algo explícito
(que no sabemos qué es) para excluir a chrome. Saquemos lo que está dejando
chrome afuera y después vemos cómo agregar de manera estándar (estándar tanto
para los navegadores como para el framework) esta clase de facilidades de uso.

##

**Comment by m4tu5** [comment]
uhm, no solo habria que sacar el hacer click en los renglones, sino tambien el datepicker y armar nuevos parciales repitiendo existentes, con pequenas  modificaciones (tampoco funciona lo de los stylesheets en chrome)

esto ultimo vos lo habias solucionado cuando nos vimos @fauno, no? donde este ese cambio?

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> uhm, no solo habria que sacar el hacer click en los renglones, sino
> tambien el datepicker y armar nuevos parciales repitiendo existentes,
> con pequenas modificaciones (tampoco funciona lo de los stylesheets en
> chrome)
> 
> esto ultimo vos lo habias solucionado cuando nos vimos @fauno, no?
> donde este ese cambio?

estaba en la rama de los assets ordenados, que mergeamos no?  o de cual
hablas?

## 

:D

**Comment by sudoaza** [comment]
@m4tu5 dejo de andar en algun momento especifico o no sabemos?
donde tira el error de js?

**Comment by m4tu5** [comment]
a mi nunca me anduvieron los scripts en los assest en chromium, por eso los puse en los archivos. el primero que use fue el de datepicker, despues el boton fuera del formulario y finalmente los renglones.

el unico stylesheet que use fue el de recibos para usar un mismo parcial en 2 vistas mostrando diferentes columnas (y esto no funciona tampoco, aunque yo no programe nada de js en este caso).

no tira error de js ... simplemente no hace nada :p

**Comment by m4tu5** [comment]
Ahora mismo no se estan cargando el selector de fechas (igual que anteriormente en chromium, que tambien habia dejado de mostrar bien los parciales usando :stylesheets).

Creo que estos dos problemas son uno solo, aunque ahora el de los partials ya esta solucionado via una alternativa.

**Comment by sudoaza** [comment]
@m4tu5 me pasas la url y el branch donde reproducirlo?

**Comment by mauriciopasquier** [comment]
Mergeen #73 y después ven si sigue pasando

**Comment by m4tu5** [comment]
Estoy sin Internet en casa. Si alguien puede mergee #73 o sino lo hago más tarde

**Comment by m4tu5** [comment]
Por ejemplo, ya no maestra los date pickers, en la edición o creación de facturas y recibos. 

Hay que ver si esta calculando el total de la factura al ir digitando los valores. 

Esto me pasa en develop, pero a @fauno no le pasa. Parece relacionada al navegador de alguna forma.

Creo recordar que si movemos los scripts de assets a las vistas si funciona. Es un parche y no una solución pero nos puede sacar del apuro momentáneamente. 

Habria que armar un partial rn views/layout que contenga todos los scripts y llamarlo desde la plantilla principal

**Comment by m4tu5** [comment]
solucionado en PR #74
