### ISSUE TITLE
los recibos y las facturas de pago generan movimientos negativos

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#52]
hay que multiplicar los montos por -1 cuando la situacion sea "pago"

**Comment by m4tu5** [comment]
por que movimientos negativos ... no tenes ya los metodos de caja depositar y extraer que se ocupan de eso?

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> por que movimientos negativos ... no tenes ya los metodos de caja
> depositar y extraer que se ocupan de eso?

porque cuando sacas se resta y cuando pones se suma? :P

extraer ya guarda movimientos en negativo, entonces habría que hacer que
el pago de movimientos use ese metodo siempre

## 

http://partidopirata.com.ar

**Comment by m4tu5** [comment]
claro, mejor asi ...
recibos de pago -- movimientos de extraccion
recibos de cobro -- movimientos de deposito

y nos ahorramos los (-1) que siempre confunden

en referencia al titulo, las facturas no pueden generar movimientos ;p

**Comment by fauno** [comment]
listo, ver 2deea50

**Comment by mauriciopasquier** [comment]
cierro!
