### ISSUE TITLE
recibos y cajas o facturas y cajas o las dos cosas

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#54]
che no hay relacion entre cajas y recibos/facturas, como seria? (capaz me estoy olvidando de algo que ya charlamos...)

**Comment by m4tu5** [comment]
On 03/10/2014 07:30 PM, fauno wrote:

> che no hay relacion entre cajas y recibos/facturas, como seria? (capaz
> me estoy olvidando de algo que ya charlamos...)
> 
> no hay relación directa. todo se hace a través de
> movimientos/cheques/retenciones -> recibos -> facturas

lo que si tienen todos en común es que todos pertenecen a una obra y los
elementos de una obra solo pueden interactuar entre si, y no con los de
las otras obras.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> On 03/10/2014 07:30 PM, fauno wrote:
> 
> > che no hay relacion entre cajas y recibos/facturas, como seria? (capaz
> > me estoy olvidando de algo que ya charlamos...)
> > 
> > no hay relación directa. todo se hace a través de
> > movimientos/cheques/retenciones -> recibos -> facturas
> 
> lo que si tienen todos en común es que todos pertenecen a una obra y los
> elementos de una obra solo pueden interactuar entre si, y no con los de
> las otras obras.

y como harias por ejemplo factura.recibo.movimientos.create(caja_id:
...) de donde saldria la caja?

## 

 D

**Comment by m4tu5** [comment]
en ese caso, la caja la tiene que elegir el usuario de entre las que esten disponibles para esa obra y para ese tipo de factura (negro/blanco).

el user tiene que elegir la caja y el monto del movimiento a manopla.

**Comment by m4tu5** [comment]
esta interfase (creo) que es la que dice @mauriciopasquier  que va a hacer cuando termine con retenciones (o al menos una parte).

tenemos un problema de nombres. en la GUI llamamos movimientos a los componentes del recibo, y en la programacion, los movimientos son sólo los que interactuan con las cajas/cuentas.

entonces, al crear un recibo, se agregan 'movimientos' que pueden ser de varios tipos
- caja (efectivo)
- cuenta (transferencia o depositos)
- cheque (propio o de 3ros)
- retencion (ganancias y cargas sociales)

en el caso de la cajas/cuentas, el usuario tiene que elegir que caja o cuenta es la que paga/cobra e ingresar el monto para crear el 'movimiento'

en el caso de cheques propios, el usuario tiene que ingresar todos los datos del cheque

en el caso de cheques de 3ros, si los recibe, tiene que ingresar todos los datos del cheque; y si los entrega, sólo tiene que seleccionarlo de entre los cheques de 3ros disponibles ('en cartera')

en el caso de las retenciones, estas se cargan a mano con anterioridad al recibo. las retenciones se cargan cuando el contador las informa y quedan en el sistema, ya asociadas a la factura que les dio lugar. al crear el próximo recibo de la factura en cuestión, la retención debe cargarse automáticamente al recibo (tal vez, dando la posibilidad de borrarla del recibo, si el usuario prefiere aplicarla al siguiente recibo).

**Comment by mauriciopasquier** [comment]
On Mon, Mar 10, 2014 at 08:03:31PM -0700, m4tu5 wrote:

> esta interfase (creo) que es la que dice @mauriciopasquier  que va a hacer
> cuando termine con retenciones (o al menos una parte).

sep

> tenemos un problema de nombres. en la GUI llamamos movimientos a los
> componentes del recibo, y en la programacion, los movimientos son sólo los
> que interactuan con las cajas/cuentas.

se los dije cuando empezaron a hablar de movimientos

##

**Comment by m4tu5** [comment]
On 03/11/2014 12:10 AM, Mauricio Pasquier Juan wrote:

> On Mon, Mar 10, 2014 at 08:03:31PM -0700, m4tu5 wrote:
> 
> > tenemos un problema de nombres. en la GUI llamamos movimientos a los
> > componentes del recibo, y en la programacion, los movimientos son sólo
> > los
> > que interactuan con las cajas/cuentas.
> 
> se los dije cuando empezaron a hablar de movimientos

la verdad es que no es ideal, pero tampoco un gran problema.
estuve pensando nombre diferentes y no me salen.

de todas formas, al usuario, que no va a ver la programación, no lo va a
confundir ... si nos arreglamos para no confundirnos nosotros, lo
podemos dejar asi.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> On 03/11/2014 12:10 AM, Mauricio Pasquier Juan wrote:
> 
> > On Mon, Mar 10, 2014 at 08:03:31PM -0700, m4tu5 wrote:
> > 
> > > tenemos un problema de nombres. en la GUI llamamos movimientos a los
> > > componentes del recibo, y en la programacion, los movimientos son sólo
> > > los
> > > que interactuan con las cajas/cuentas.
> > 
> > se los dije cuando empezaron a hablar de movimientos
> 
> la verdad es que no es ideal, pero tampoco un gran problema.
> estuve pensando nombre diferentes y no me salen.
> 
> de todas formas, al usuario, que no va a ver la programación, no lo va a
> confundir ... si nos arreglamos para no confundirnos nosotros, lo
> podemos dejar asi.

para mi movimientos son todas las entradas y salidas de dineros, sean de
efectivo o bancarios, segun el tipo de caja.  para mi no hay
contradiccion ni confusion de nombres en lo que veniamos laburando, solo
que no encuentro cómo asociar varios movimientos a un recibo de pago o
de cobro de un saque.  para los movimientos de caja se genera un recibo
interno (adhoc).

## 

http://selfdandi.com.ar

**Comment by m4tu5** [comment]
bueno, hay una pequena confusion en que al crear un recibo en la GUI, el boton dice '+ Nuevo Movimiento' y podrias estar agregando un cheque o una retencion. En cualquier caso, si se nos ocurre un nombre mejor, cambiamos el boton y listo.

La asociación de movimientos con un recibo de cobro/pago es la interfase que va a encarar @mauriciopasquier
