### ISSUE TITLE
pasamanos de cheques

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#55]
estoy laburando en esto:
- los cheques tienen un padre_id que es otro cheque
- cuando se hace un pasamanos, se genera un cheque nuevo con el padre_id seteado al cheque que se pasó
- se marca el cheque original como pasado de mano

no me queda claro si generan movimientos y si los cheques van a tener un tercero asociado

**Comment by fauno** [comment]
hice que el tercero pasado cambie situacion a "pasamanos" pero no me decido si el pasado de manos tiene una situacion especial, o mantiene terceros y cambia de estado a "pasado". que tiene mas logica?

**Comment by m4tu5** [comment]
On 03/10/2014 08:15 PM, fauno wrote:

> hice que el tercero pasado cambie situacion a "pasamanos" pero no me
> decido si el pasado de manos tiene una situacion especial, o mantiene
> terceros y cambia de estado a "pasado". que tiene mas logica?
> 
> espero no llegar muy tarde con la respuesta.

me parece que lo de tener 2 cheques relacionados sobrecomplica la cosa.
me parece que con un solo cheque alcanza y utilizando los campos que
tenemos ahora en la base o alguno menos.

1) eliminaría situacion de los cheques y la triangularía por el estado
(es simplemente ajustar los metodos propio? y tercero?), usar los dos
campos me parece redundante. los estados de los cheques propios son
diferentes de los de 3ros, con lo que esto seria facil.

estados posibles
- cheques propios: emitido -> pagado
- cheques terceros (variante cobrado): recibido -> depositado ->
  cobradoo rechazado
- cheques terceros (variante pasamanos): recibido -> entregado

2) renombraría los campos 'recibo_id' y 'cuenta_id' a 'origen_id' y
'destino_id'
lo que busco es estandarizar donde se guarda la data. siempre que un
cheque se cree en el sistema, se registra 'origen_id' y, dependiendo del
tipo de cheque, en el mismo u otro momento se registra 'destino_id'

cheque propio:
  evento: creacion para pagar factura de pago
    origen_id = cuenta_iddesde la que se emite el cheque
    destino_id = recibo_de_pago_id
    estado = emitido
  evento: descontado de la cuenta bancaria
    estado = pagado

cheque 3ros:
  evento: recepcion como forma de cobro
    origen_id = recibo_de_cobro_id -- se registra al recibir el cheque
    estado = recibido
  evento: depositado en el banco
    destino_id = cuenta_id donde se haya depositado
    estado = depositado
  evento: banco acredita el monto del cheque en la cuenta
    estado = cobrado
  evento (variante): banco rechaza el cheque
    estado = rechazado
  evento (variante): el cheque se entrega como parte de pago -- 'pasamanos'
    destino_id = recibo_de_pago
    estado = entregado

que te parece?

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> que te parece?

no entendi un carajo pero capaz es la hora.  vos decis que los
destino_id, etc. a veces son cajas, otras cheques, etc.?  no digo que
este mal pero no le veo el sentido

fijate los parches que subi ya estan funcionando

## 

http://selfdandi.com.ar

**Comment by m4tu5** [comment]
lo que propongo (a ver si sale mas claro ahora) es que, en todos los casos, usamos un solo cheque (el modelo actual tiene 2 cheques para los pasamanos, que en realidad es uno solo, lo que me parece confuso).

en la vida real, de cada cheque nos interesa conocer dos relaciones, su origen (como se genera) y su destino (donde termina su corta vida). 

lo que cambia, según el tipo de cheque y como se use, es a que tabla (recibo o caja) corresponde el origen_id y el destino_id.

si lo hacemos así, logramos tener una logica de almacenamiento de la info paralela para todos los cheques, independientemente del tipo y como hayan terminado (pagados, depositados o pasamanos)

en el modelo actual, primero hay que conocer el tipo de cheque para saber si el origen del cheque esta en cuenta_id, o en recibo_id, o en otro cheque, lo que me parece mas engorroso.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> lo que propongo (a ver si sale mas claro ahora) es que, en todos los
> casos, usamos un solo cheque (el modelo actual tiene 2 cheques para
> los pasamanos, que en realidad es uno solo, lo que me parece confuso).
> 
> en la vida real, de cada cheque nos interesa conocer dos relaciones,
> su origen (como se genera) y su destino (donde termina su corta vida).
> 
> lo que cambia, según el tipo de cheque y como se use, es a que tabla
> (recibo o caja) corresponde el origen_id y el destino_id.

por qué los recibos no tienen caja asociada?  la id de qué modelo va en
origen y destino?

> si lo hacemos así, logramos tener una logica de almacenamiento de la
> info paralela para todos los cheques, independientemente del tipo y
> como hayan terminado (pagados, depositados o pasamanos)
> 
> en el modelo actual, primero hay que conocer el tipo de cheque para
> saber si el origen del cheque esta en cuenta_id, o en recibo_id, o en
> otro cheque, lo que me parece mas engorroso.

??

en lo que hice hay un solo campo extra, relacionado_id.  cuando se pasa
de manos un cheque, se marca con situacion pasamanos y se crea otro
igual con estado pasado de manos (no estoy convencido de la mezcla
situacion/estado aun).  cuando el segundo cheque esta creado se
relacionan los dos, entonces el cheque con situacion pasamanos tiene un
metodo pasado_a que devuelve el cheque nuevo, y el cheque nuevo tiene un
metodo pasado_de que devuelve el cheque original.

si queres ver todos los cheques pasados de manos,
Cheques.where(situacion: pasamanos).

ahora me estoy dando cuenta si hay que cambiar algo más en el cheque
original, para guardar a quién fue pasado, si hace falta.  eso es lo que
vos queres decir con cuenta_id y recibo_id?

## 

P)

**Comment by m4tu5** [comment]
On 03/11/2014 09:28 AM, fauno wrote:

> por qué los recibos no tienen caja asociada? 

no entiendo esta pregunta. los recibos no tienen asociación directa con
las cajas. se asocian a través de los movimientos.

> la id de qué modelo va en origen y destino?

mira el post largo de mas arriba que explica las posibilidades para
origen_id y destino_id

> ahora me estoy dando cuenta si hay que cambiar algo más en el cheque
> original, para guardar a quién fue pasado, si hace falta. eso es lo que
> vos queres decir con cuenta_id y recibo_id?
> 
> claro, se trata de poder ver facilmente quien nos dio el cheque (o desde
> cual de nuestras cuentas bancarias lo emitimos) y a quien fue dado (o
> donde fue depositado).

usando origen_id y destino_id, siempre voy a buscar esta info en los
mismos campos.

si origen o destino es un recibo, entonces

  de donde vino = cheque.origen.factura.tercero  <-- 3ros
  a donde fue = cheque.destino.factura.tercero  <-- prop. + pasamanos

si, por el contrario, son cajas

  donde se emitio = cheque.origen.banco + cheque.origen.numero  <-- prop
  donde se deposito = cheque.destino.banco + cheque.origen.numero  <--
3ro depositado/cobrado/rechazado

**Comment by m4tu5** [comment]
repito esto porque el post anterior lo reconocio como una cita y lo oculta

si origen o destino es un recibo, entonces
  de donde vino = cheque.origen.factura.tercero <-- para 3ros
  a donde fue =   cheque.destino.factura.tercero <-- para prop. + pasamanos 

si, por el contrario, son cajas
  donde se emitio = cheque.origen.banco + cheque.origen.numero <-- para prop 
  donde se deposito = cheque.destino.banco + cheque.origen.numero <-- para 3ro depositado/cobrado/rechazado

**Comment by fauno** [comment]
en este momento los cheques tiene un recibo_id y una caja_id, vos propones que cuando se pase un chque en origen_id se guarde el recibo_id y recibo_id sea el nuevo?  lo mismo para caja_id y destino_id?

**Comment by m4tu5** [comment]
Lo hablamos mañana, por acá no estamos avanzando

**Comment by fauno** [comment]
entonces segun lo que hablamos ayer:
- Los cheques tienen dos recibos, uno de origen y otro de destino
- Los cheques se asocian a una caja de tipo chequera
- Cuando se deposita o paga un cheque, se transfiere dinero de la caja Chequera a la caja correspondiente (efectivo o banco)

**Comment by m4tu5** [comment]
On 03/13/2014 08:09 PM, fauno wrote:

> entonces segun lo que hablamos ayer:
> - Los cheques tienen dos recibos, uno de origen y otro de destino
> - Los cheques se asocian a una caja de tipo chequera
> - Cuando se deposita o paga un cheque, se transfiere dinero de la caja
>   Chequera a la caja correspondiente (efectivo o banco)
> 
> es lo que yo entiendo. tengo alguna duda con los cheques propios y la
> caja a la que se asocian.

repaso terceros, que creo es donde estamos de acuerdo. los cheques de
3ros los asocias a un recibo de cobro cuando los recibis y a la caja
'cheques en cartera'. Dependiendo de como terminen, en una segunda
instancia los asocias a un recibo interno (si se cobran) que registra el
movimiento desde 'cheques en cartera' al 'banco' donde se depositen; o a
un recibo externo (si pasa de manos) que registra la factura que se haya
pagado con ese cheque.

mi interpretacion de cheques proprios, se asocian a un recibo de pago
cuando se emiten y a la caja 'cheques propios' desde la cual se emite el
cheque. Al momento del pago, se asocia el cheque al recibo interno que
registra la transferencia de fondos de la caja 'banco' a la caja
'cheques propios'

creo que @mauriciopasquier hablo el miercoles de no usar una caja
'cheques propios' y usar directamente 'banco', pero no se bien como
funcionaria el pago del cheque en ese caso.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> On 03/13/2014 08:09 PM, fauno wrote:
> 
> > entonces segun lo que hablamos ayer:
> > - Los cheques tienen dos recibos, uno de origen y otro de destino
> > - Los cheques se asocian a una caja de tipo chequera
> > - Cuando se deposita o paga un cheque, se transfiere dinero de la caja
> >   Chequera a la caja correspondiente (efectivo o banco)
> > 
> > es lo que yo entiendo. tengo alguna duda con los cheques propios y la
> > caja a la que se asocian.
> 
> repaso terceros, que creo es donde estamos de acuerdo. los cheques de
> 3ros los asocias a un recibo de cobro cuando los recibis y a la caja
> 'cheques en cartera'. Dependiendo de como terminen, en una segunda
> instancia los asocias a un recibo interno (si se cobran) que registra el
> movimiento desde 'cheques en cartera' al 'banco' donde se depositen; o a
> un recibo externo (si pasa de manos) que registra la factura que se haya
> pagado con ese cheque.

esto ya lo hice ayer esta en el commit asociado

> mi interpretacion de cheques proprios, se asocian a un recibo de pago
> cuando se emiten y a la caja 'cheques propios' desde la cual se emite el
> cheque. Al momento del pago, se asocia el cheque al recibo interno que
> registra la transferencia de fondos de la caja 'banco' a la caja
> 'cheques propios'

hasta ahora vienen asociados a la caja de donde se van a debitar cuando
se paguen.

> creo que @mauriciopasquier hablo el miercoles de no usar una caja
> 'cheques propios' y usar directamente 'banco', pero no se bien como
> funcionaria el pago del cheque en ese caso.

ya esta codeado, es algo así:

cheque.caja = caja.new(situacion: "banco")
cheque.pagar() { cheque.caja.extraer(cheque.monto); cheque.estado = "pagado" }

## 

:{

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> bien, y este movimiento de pago en "banco" se asocia a que recibo? al
> original de pago por el que se emite el cheque? porque en este caso,
> recibo interno no existe. es asi?

claro

## 

:{

**Comment by mauriciopasquier** [comment]
no sería más así? (en el modelo de cheques):

```
# cheque.caja siempre es una chequera
def pagar(caja_donde_pagar)
  destino = caja_donde_pagar.depositar caja.extraer(cheque.monto)
end
```

asumiendo que:
1. destino es el recibo de destino
2. caja.depositar devuelve un recibo

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> no sería más así? (en el modelo de cheques):
> 
> ```
> # cheque.caja siempre es una chequera
> def pagar(caja_donde_pagar)
>   destino = caja_donde_pagar.depositar caja.extraer(cheque.monto)
> end
> ```

seria mas bien

  def pagar(caja_donde_pagar)
      self.caja.transferir(self.monto, caja_donde_pagar)
  end

ahora es 

  def pagar
      self.caja.extraer(self.monto)
  end

> asumiendo que:
> 1. destino es el recibo de destino
> 2. caja.depositar devuelve un recibo

caja.transferir devuelve un recibo interno

no me convence lo de a veces guardar un recibo y otras una caja, en el
siguiente comentario explico

## 

http://endefensadelsl.org

**Comment by mauriciopasquier** [comment]
On Fri, Mar 14, 2014 at 01:26:58PM -0700, fauno wrote:

> Mauricio Pasquier Juan notifications@github.com writes:
> 
> > no sería más así? (en el modelo de cheques):
> > 
> > ```
> > # cheque.caja siempre es una chequera
> > def pagar(caja_donde_pagar)
> >   destino = caja_donde_pagar.depositar caja.extraer(cheque.monto)
> > end
> > ```
> 
> seria mas bien
> 
>   def pagar(caja_donde_pagar)
>       self.caja.transferir(self.monto, caja_donde_pagar)
>   end

eh, me había olvidado de mi método!

> ahora es 
> 
>   def pagar
>       self.caja.extraer(self.monto)
>   end
> 
> > asumiendo que:
> > 1. destino es el recibo de destino
> > 2. caja.depositar devuelve un recibo
> 
> caja.transferir devuelve un recibo interno

entonces

```
def depositar(caja_donde_pagar)
  self.destino = caja.transferir(monto, caja_donde_pagar)
end
```

> no me convence lo de a veces guardar un recibo y otras una caja, en el
> siguiente comentario explico

no entiendo de dónde viene lo de "a veces".. la caja está para saber en qué
chequera tenés el cheque, nada más. Cuando el cheque es depositado (transferido
a otra caja) o usado para pagar, desaparece de la chequera, no?

##

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> On Fri, Mar 14, 2014 at 01:26:58PM -0700, fauno wrote:
> 
> > Mauricio Pasquier Juan notifications@github.com writes:
> > 
> > > no sería más así? (en el modelo de cheques):
> > > 
> > > ```
> > > # cheque.caja siempre es una chequera
> > > def pagar(caja_donde_pagar)
> > >   destino = caja_donde_pagar.depositar caja.extraer(cheque.monto)
> > > end
> > > ```
> > 
> > seria mas bien
> > 
> >   def pagar(caja_donde_pagar)
> >       self.caja.transferir(self.monto, caja_donde_pagar)
> >   end
> 
> eh, me había olvidado de mi método!

lo hice yo ese

> entonces
> 
> ```
> def depositar(caja_donde_pagar)
>   self.destino = caja.transferir(monto, caja_donde_pagar)
> end
> ```

si, ya esta en feature/caja-chequera esto

> > no me convence lo de a veces guardar un recibo y otras una caja, en el
> > siguiente comentario explico
> 
> no entiendo de dónde viene lo de "a veces".. la caja está para saber
> en qué chequera tenés el cheque, nada más. Cuando el cheque es
> depositado (transferido a otra caja) o usado para pagar, desaparece de
> la chequera, no?

es lo que dice matus 200 comentarios mas arriba

dejame terminar de escribir!!

## 

http://selfdandi.com.ar

**Comment by mauriciopasquier** [comment]
On Fri, Mar 14, 2014 at 01:37:44PM -0700, fauno wrote:

> Mauricio Pasquier Juan notifications@github.com writes:
> 
> > On Fri, Mar 14, 2014 at 01:26:58PM -0700, fauno wrote:
> > 
> > > Mauricio Pasquier Juan notifications@github.com writes:
> > > 
> > > > no sería más así? (en el modelo de cheques):
> > > > 
> > > > ```
> > > > # cheque.caja siempre es una chequera
> > > > def pagar(caja_donde_pagar)
> > > >   destino = caja_donde_pagar.depositar caja.extraer(cheque.monto)
> > > > end
> > > > ```
> > > 
> > > seria mas bien
> > > 
> > >   def pagar(caja_donde_pagar)
> > >       self.caja.transferir(self.monto, caja_donde_pagar)
> > >   end
> > 
> > eh, me había olvidado de mi método!
> 
> lo hice yo ese

bueno, es igual que el cambio de moneda

> > entonces
> > 
> > ```
> > def depositar(caja_donde_pagar)
> >   self.destino = caja.transferir(monto, caja_donde_pagar)
> > end
> > ```
> 
> si, ya esta en feature/caja-chequera esto
> 
> > > no me convence lo de a veces guardar un recibo y otras una caja, en el
> > > siguiente comentario explico
> > 
> > no entiendo de dónde viene lo de "a veces".. la caja está para saber
> > en qué chequera tenés el cheque, nada más. Cuando el cheque es
> > depositado (transferido a otra caja) o usado para pagar, desaparece de
> > la chequera, no?
> 
> es lo que dice matus 200 comentarios mas arriba

entonces estamos todos de acuerdo?

> dejame terminar de escribir!!

y bueno, no me pidas que mire entonces. Vos me estás trayendo acá.

##

**Comment by fauno** [comment]
recibo es el origen, destino es otro recibo, la caja va variando. ahora me meto con pasamanos usando esta logica.

**Comment by fauno** [comment]
ahi pushee los pasamanos

## 

http://wiki.hackcoop.com.ar

**Comment by fauno** [comment]
ver #62
