### ISSUE TITLE
error en la validación de recibos/facturas (de nuevo)

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#57]
corré los tests así: `rake TESTOPTS="--seed 60985"`

```
± feature/rutas mauricio@turing cp$ rake test TESTOPTS="--seed 60985"
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
Run options: --seed 60985

# Running tests:

................................................................E.............

Finished tests in 2.153736s, 36.2161 tests/s, 81.7185 assertions/s.

  1) Error:
RecibosControllerTest#test_accede_a_editar:
ActiveRecord::RecordInvalid: La validación falló: La factura ya fue cancelada, El importe es mayor al saldo -0,01
    test/controllers/recibos_controller_test.rb:6:in `block in <class:RecibosControllerTest>'

78 tests, 176 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by m4tu5** [comment]
si estas usando data creada con dummy o manualmente, lo mas probable es que no se haya generado correctamente el importe total y saldo de la factura. Tenes que recalcularlo a mano.

desde la consola podes mandar:
Factura.all.each {|factura| factura.calcular_importe_total; factura.calcular_saldo; factura.save}

esto deberia solucionarlo.

**Comment by mauriciopasquier** [comment]
On Wed, Mar 12, 2014 at 06:31:32PM -0700, m4tu5 wrote:

> si estas usando data creada con dummy o manualmente, lo mas probable es que no se haya generado correctamente el importe total y saldo de la factura. Tenes que recalcularlo a mano.
> 
> desde la consola podes mandar:
> Factura.all.each {|factura| factura.calcular_importe_total; factura.calcular_saldo; factura.save}
> 
> esto deberia solucionarlo.

no, es un test.. los datos se generan automáticamente. Por eso pasé el seed
(para que genere los mismos datos aleatorios.. si no a veces pasan y a veces
no)

##

**Comment by m4tu5** [comment]
no me esta fallando en develop @ 47e9f8e, pero veo que hay un nuevo commit

a ver despues de hacer pull que onda

ahora estoy en develop @ 378ed52, instalo la gema yaml_db, y los tests con el seed que enviaste sigue sin fallar

no sera algo de la rama en la que estas vos?
sera algo de la rama en la que estas laburando?

**Comment by m4tu5** [comment]
fer@susa ~/proyectos/cp $ rake TESTOPS="-seed 60985"
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
Run options: --seed 24845

# Running tests:

..............................................................................

Finished tests in 6.974232s, 11.1840 tests/s, 25.2358 assertions/s.

78 tests, 176 assertions, 0 failures, 0 errors, 0 skips

**Comment by m4tu5** [comment]
ah, ya veo que uso un seed diferente a pesar de TESTOPS ... que onda?

**Comment by mauriciopasquier** [comment]
On Wed, Mar 12, 2014 at 06:44:26PM -0700, m4tu5 wrote:

> no me esta fallando en develop @ 47e9f8e, pero veo que hay un nuevo commit
> 
> a ver despues de hacer pull que onda
> 
> ahora estoy en develop @ 378ed52, instalo la gema yaml_db, y los tests con el seed que enviaste sigue sin fallar
> 
> no sera algo de la rama en la que estas vos?
> sera algo de la rama en la que estas laburando?

no creo, no toqué nada de eso y rebaseé desde develop.. después lo veo mejor

##

**Comment by m4tu5** [comment]
ok, todo typo mio :) logre hacer los tests con el mismo seed y si, falla

no se bien por que (no encuentro la falla) pero al crear la factura y el recibo se asignan valores erroneos al saldo

creo que tiene que ver con que se intenta crear una factura con importe_total = 3000, cuando este importe se termina calculando como resultado de importe_neto + iva (y tal vez por acá venga el descuadre?)

vi que si se cambia importe_total por importe_neto en la generacion de la factura en el test la cosa funciona ... pero sigo creyendo que el saldo calculado es erroneo y que simplemente deja de fallar.

Si vi que el saldo el correcto cuando tambien asingo un importe a mano al recibo.

Algo de esto hace sentido a alguien?

Abajo los resultados de correr los test sobre develop, con nuevos test que tirrar error, pero informan el importe total de la factura, del recibo y el saldo (no supo hacerlo mas prolijo).

  2) Failure:
RecibosControllerTest#test_chequea_importe_factura [/home/fer/proyectos/cp/test/controllers/recibos_controller_test.rb:13]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Money fractional:1136 currency:ARS>
+3630

  3) Failure:
RecibosControllerTest#test_chequea_importe_recibo [/home/fer/proyectos/cp/test/controllers/recibos_controller_test.rb:21]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Money fractional:433 currency:ARS>
+1000

  4) Failure:
RecibosControllerTest#test_chequea_saldo_factura [/home/fer/proyectos/cp/test/controllers/recibos_controller_test.rb:17]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Money fractional:90 currency:ARS>
+2630

**Comment by m4tu5** [comment]
Vaya quilbo que arme con mis comentarios. 

Resumen: revisar valores de saldo e importe de factura y recibo. 

Creo que el saldo se calcula mal en estos tests

**Comment by fauno** [comment]
estoy con esto

**Comment by mauriciopasquier** [comment]
ya lo arreglé acá en una rama, pero si querés aportar a este issue poné las validaciones de factura en factura, no en recibo, y hacé tests que prueben bien los casos frontera (cuando el importe del recibo es igual al de la factura, por ejemplo) y casos de datos inválidos

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> ya lo arreglé acá en una rama, pero si querés aportar a este issue
> poné las validaciones de factura en factura, n

en cual?

## 

http://hackcoop.com.ar

**Comment by fauno** [comment]
me parece que saldo vuelve a ser una consulta :P

**Comment by fauno** [comment]
eh no me dio bola con el closes #57

**Comment by m4tu5** [comment]
Creo que es close, sin s final
