### ISSUE TITLE
auto-completar 3ros en nuevas facturas

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#59]
el objetivo es que al ingresar factura se pueda comenzar a tipear el nombre del tercero y nos aparezca un listado de aquellos con nombres coincidentes en la tabla

encontre esto, https://github.com/crowdint/rails3-jquery-autocomplete-app

@mauriciopasquier lo conoces? que recomendas?

**Comment by mauriciopasquier** [comment]
On Fri, Mar 14, 2014 at 05:33:33PM -0700, m4tu5 wrote:

> el objetivo es que al ingresar factura se pueda comenzar a tipear el nombre del tercero y nos aparezca un listado de aquellos con nombres coincidentes en la tabla
> 
> encontre esto, https://github.com/crowdint/rails3-jquery-autocomplete-app

ese es el repositorio de la aplicación de ejemplo de la librería que uso

> @mauriciopasquier lo conoces? que recomendas?

pero sí, estoy usando esa

```
gem 'rails3-jquery-autocomplete'
```

##

**Comment by m4tu5** [comment]
Y se podra hacer algo mixto, como que si el tercero existe, que lo use, y si no existe, que lo cree?

Es que hay terceros de un solo uso (facturas esporadicas) y lo practico sería poder cargarlo desde el mismo formulario de la factura solo cuando es necesario.

**Comment by mauriciopasquier** [comment]
On Fri, Mar 14, 2014 at 05:53:12PM -0700, m4tu5 wrote:

> Y se podra hacer algo mixto, como que si el tercero existe, que lo use, y si
> no existe, que lo cree?

eso se hace en el modelo, lo tengo hecho en otro proyecto

> Es que hay terceros de un solo uso (facturas esporadicas) y lo practico sería
> poder cargarlo desde el mismo formulario de la factura solo cuando es
> necesario.

##

**Comment by m4tu5** [comment]
recien lo pongo a funcionar en feature/mas-correcciones, pero se ve muy feo. se jode la vista y aparecen unos links muy chotos para las opciones.

hay otra alternativa que se puede probar
esto y el #59 se pueden solucionar con autocompletes. el que esta ahora es feo, voy a probar
http://stackoverflow.com/questions/3188157/how-to-set-up-jquery-ui-autocomplete-in-rails

**Comment by m4tu5** [comment]
sigue en #61
