### ISSUE TITLE
validaciones de recibo y factura

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#6]
@fauno 

Las validaciones de recibo están mal. Primero, me parece que deberían ir en factura (al agregar el recibo). Segundo, hace al recibo inválido en algunos casos incorrectamente, por ejemplo si es el único recibo y tiene un importe de más de la mitad ~~más~~ del importe total de la factura

**Comment by mauriciopasquier** [comment]
Dejé una rama con algunos cambios al respecto y un test que muestra esta falla

**Comment by fauno** [comment]
en la validación de saldo se chequea el valor del mismo recibo que se está insertando :B

**Comment by mauriciopasquier** [comment]
El test muestra que el recibo es inválido aunque al insertarlo sea válido. O sea, tu validación no corre sólo al insertar _guiño, guiño_

**Comment by fauno** [comment]
lo sé pero Factura.saldo está tomando los datos que están en la base o no?

**Comment by fauno** [comment]
fijate ese commit hace una hora que estoy tratando de triggerearlo y no pasa naranjas

**Comment by fauno** [comment]
Ya está mergeado esto :B
