### ISSUE TITLE
filtro por obras en todas las vistas

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#60]
- dropdown en barra navegacion para seleccionar una obra o todas
- metodos/scripts para actualizar la vista cuando cambie la obra seleccionada
- columna 'obra' en todos los listados (ocultar cuando haya una obra selecionada usando stylesheets?)

**Comment by fauno** [comment]
#66 empezó a resolver algo de esto, al menos desde la vista de obras.  el tema es que si usamos con_obra? para generar un select de todas las obras + url actual, como hacemos con las vistas de una factura especifica?  por ejemplo /obras/1/facturas/1 existe pero /obras/2/facturas/1 no.  mandamos a la vista principal? si estamos en /obras/1/facturas/1, el select muestra /obras/*/facturas/:situacion

**Comment by m4tu5** [comment]
vos decis cuando una persona ingresa una URL que no existe ... sino, como llegas hasta ahi?

**Comment by fauno** [comment]
digo un caso así:
- estoy viendo las facturas de la obra 1
- el select me muestra que estoy en la obra 1, pero que puedo saltar a 2 y 3
- como estoy en /obras/1/facturas lo lógico es que el select me deje saltar a /obras/2/facturas, etc.
- pero si estoy en una factura especifica, pertenece a una obra, por lo que saltar de /obras/1/facturas/1 a /obras/2/facturas/1 no tiene sentido porque no factura 1 no está asociada a la obra 2, en ese caso vamos a /obras/2/facturas?

**Comment by fauno** [comment]
armo un partial de muestra y lo vemos

**Comment by m4tu5** [comment]
On 03/20/2014 07:28 PM, fauno wrote:

> digo un caso así:
> - estoy viendo las facturas de la obra 1
> - el select me muestra que estoy en la obra 1, pero que puedo saltar a
>   2 y 3
> - como estoy en /obras/1/facturas lo lógico es que el select me deje
>   saltar a /obras/2/facturas, etc.
> - pero si estoy en una factura especifica, pertenece a una obra, por
>   lo que saltar de /obras/1/facturas/1 a /obras/2/facturas/1 no tiene
>   sentido porque no factura 1 no está asociada a la obra 2, en ese
>   caso vamos a /obras/2/facturas?

vamos a obras/2/facturas/{cobro,pago} segun sea la situacion de la
factura que se esta viendo (el helper se usa en el boton de volver al
listado de la vista show ... es ese mismo).

**Comment by fauno** [comment]
ahi puse algo intermedio...
