### ISSUE TITLE
actualizar dropdowns despues de seleccionar un valor

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#61]
en la vista de crear/editar factura, hay en el formulario 2 dropdowns, uno para seleccionar el 3ro y otro para el CUIT.

se busca que al seleccionar un valor en uno de los campos (cualquiera sea), se actualice el otro con el valor correspondiente.

los dropdowns los vinculé ambos a tercero_id y esto hace que los rails los renderize con el mismo id, lo que entiendo no esta bien.

deje unas lineas de js en app/assets/javascripts/facturas.js que son mi primer intento, pero de momento no funcionan.

**Comment by sudoaza** [comment]
Capaz que lo que conviene aca estener el tercero_id como un campo hidden y que se actualice cuando cambia el cuit o tercero, pero que esos dropdowns no esten asociados al tercero_ud

**Comment by mauriciopasquier** [comment]
yo uso esto en otro proyecto (en el .coffee correspondiente):

```
$(document)
  .on 'railsAutocomplete.select', '.ac-codigo', (evento, data) ->
    $(this).parent().next()
      .children('.ac-participante')
        .val(data.item.participante)

$(document)
  .on 'railsAutocomplete.select', '.ac-participante', (evento, data) ->
    $(this).parent().prev()
      .children('.ac-codigo')
        .val(data.item.codigo)
```

`railsAutocomplete.select` es el evento que larga la gema que encontró @m4tu5
cuando elegís un ítem. Estos dos bindings son complementarios.. cuando se elige
un código se llena el participante y viceversa. Este es el partial relacionado:

```
= f.autocomplete_field :codigo, valores_inscripcion_codigo_path,
  class: 'ac-codigo'

= f.autocomplete_field :participante,
  valores_inscripcion_participante_path,
  class: 'ac-participante'
```

Lo que falta son las acciónes en el controlador
(`valores_inscripcion_participante_path` y `valores_inscripcion_codigo_path`),
que en mi código son custom pero se pueden generar parecidas con la misma gema.

**Comment by m4tu5** [comment]
esto y el #59 se pueden solucionar con autocompletes

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> esto y el #59 se pueden solucionar con autocompletes. el que esta
> ahora es feo, voy a probar
> http://stackoverflow.com/questions/3188157/how-to-set-up-jquery-ui-autocomplete-in-rails

había una lib de twitter... 

http://twitter.github.io/typeahead.js/

## 

http://partidopirata.com.ar

**Comment by m4tu5** [comment]
intente con typeahead.js, y le meti varias horas y no logre hacerlo andar, pero se ve como una muy buen solucion. muy prolija.
me gusta mas como presenta las opciones y como las podes elegir que en la otra alternativa

**Comment by sudoaza** [comment]
Esto esta hecho en #86 cierro
