### ISSUE TITLE
agregar saldo a cajas?

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#63]
si tenemos un campo saldo en las facturas, no deberiamos tener otro en las cajas?

o vamos a calcular el saldo de cada caja con caja.total(es) cada vez que carge una vista? 
no se volverá pesado con muchos movimientos?

@mauriciopasquier , vos como te manejas en estos casos?

**Comment by mauriciopasquier** [comment]
depende cuántos movimientos :P 

se puede usar una columna para guardar el total actualizado, igual que en factura.. de todas maneras no me convence mucho la preoptimización y no va a ser taaan diferente de usar eager load con los movimientos (a menos que el server tenga muy poca ram).

**Comment by m4tu5** [comment]
el server va a tener 2 o 4 Gb (no me acuerdo), pero no diría que es poca RAM, no?

Igual probemos así y si no va lo cambiamos. De momento, cierro esto.
