### ISSUE TITLE
implementar modelo recibo-movimiento(causa)-caja

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#70]
la idea es que cada movimiento tenga un recibo y una caja asociadas, en todas las posibles situaciones.

el movimiento, ademas, tiene asociado una causa, que lo justifica/respalda. 
por causa nos referimos a:
- en el caso de efectivo, a los billetes que cambian de manos identificados por si nro. de serie
- en el caso de transferencias, al certificado del banco que la respalda (id de transferencia)
- en el caso de cheque propio o de terceros, el id del cheque y la informacion que este contiene
- en el caso de una retención, al PDF emitido por el contador que se le entrega al cliente al pagar

dado que no nos interesa registrar los nros. de serie del efectivo, así como tampoco el id de la transferencia bancaria, los modelos de efectivo y banco no tendrán asociadas tablas. Si
lo harán los modelos de chequera y retención.

TODO hacer un diagrama para que se entienda mejor.

**Comment by fauno** [comment]
@mauriciopasquier pusheaste lo que venias haciendo?
