### ISSUE TITLE
vistas faltantes

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#71]
cambios de moneda / transferencias
cheques
retenciones (con selector de adjunto)

**Comment by fauno** [comment]
quien esta con estas?

**Comment by mauriciopasquier** [comment]
sobre cheques y retenciones yo hago lo relacionado a los pagos apenas termine el backend

**Comment by fauno** [comment]
falta cheques vencidos y por vencer

**Comment by m4tu5** [comment]
ya estan hechas las vistas de retenciones en feature/gui-retenciones

**Comment by m4tu5** [comment]
ya estan las vistas de chequeras en feature/gui-chequeras
