### ISSUE TITLE
la monetizacion de factura no funca

### ISSUE THREAD

**Issue by fauno** [lainventoria/tesoro#76]
@m4tu5 estaba probando crear una factura con moneda USD y por mas que se cargue la moneda correcta en los campos *_moneda, los atributos monetizados siempre se crean como ARS.  factura.saldo da un error al calcular el importe porque intenta restar ars a usd

**Comment by fauno** [comment]
ahi esta :D

**Comment by m4tu5** [comment]
corregido en feature/gui-varios-2
