### ISSUE TITLE
filtro para obras -- error al cambiar de obra

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#78]
al cambiar la obra desde la vista de una factura, intenta acceder al listado de facturas de esa obra, sin tomar en cuenta la situacion (cobro/pago) lo que resulta en error

ej:
- desde facturas/2, cambiar el selector de obra en la barra superior.
- el error que presenta es que no existe la ruta obras/x/facturas ... debería ser obras/x/facturas/situacion

**Comment by m4tu5** [comment]
lo mismo pasa con recibos, con la diferencia de que la ruta /recibos aún existe (aunque no deberia).

se tiene que ir a recibos/situacion

**Comment by m4tu5** [comment]
revisar todas las redirecciones similares

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> al cambiar la obra desde la vista de una factura, intenta acceder al listado de facturas de esa obra, sin tomar en cuenta la situacion (cobro/pago) lo que resulta en error
> 
> ej:
> - desde facturas/2, cambiar el selector de obra en la barra superior.
> - el error que presenta es que no existe la ruta obras/x/facturas ... debería ser obras/x/facturas/situacion

en qué momento dejó de existir /obras/x/facturas?

sacar la situacion es medio jodido porque ese listado se genera en todos
lados, tendría que hacer un case por cada @modelo posible :P

## 

:D

**Comment by m4tu5** [comment]
es como en /facturas ... no tiene sentido mostras cobros y pagos todos mezclados

siempre hablamos de mostrar facturas/pagos o facturas/cobros

lo que digo, es que al cambiar la obra vayas al listado que corresponda según la factura que tengas a la vista (o el listado que estes viendo) ... en un caso situacion es un parametro y en otro esta en @factura.situacion

**Comment by fauno** [comment]
ahi va :P

**Comment by fauno** [comment]
bueno hago el pr

**Comment by fauno** [comment]
ver pr #84
