### ISSUE TITLE
no permitir crear factura si no hay obra asociada

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#79]
apagamos el boton?
hacemos una validacion?

**Comment by mauriciopasquier** [comment]
agregá un `required: true` en la GUI, y además _debería_ haber una validación
en el modelo de facturas

**Comment by mauriciopasquier** [comment]
Qué garcha, los comentarios vía mail no vienen con markdown! Me acabo de dar cuenta :|

**Comment by m4tu5** [comment]
incorpore un selector de obra en el formulario, que toma el parametro de la url si existe

**Comment by m4tu5** [comment]
corregido en feature/gui-varios-2

**Comment by m4tu5** [comment]
falta agregar la validacion en el modelo de facturas

**Comment by sudoaza** [comment]
@m4tu5 en feature/validacion-factura agregue que valide el tercero, avisa si falta algo mas.
