### ISSUE TITLE
muerte y destrucción y asociaciones

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/tesoro#82]
Hay que pensar qué pasa con las asociaciones de cada modelo cuando lo destruís. Factura debería destruir sus recibos por ejemplo? Recibo podría destruir sus movimientos a menos que tengan caja asociada? Cosas así

**Comment by m4tu5** [comment]
le estuve dando vueltas al tema
me parece, que lo que le pediría al usuario es que se tome el trabajo de borrar 1ro los movimiento, después los recibos y por ultimo la factura ... es que como afecta el saldo de caja, se puede armar mucho quilombo si alguien borra algo por error

que les parecería agregar esa validacion entonces?

despues, si los usuarios piden mas flexibilidad lo revisamos.

**Comment by mauriciopasquier** [comment]
Se puede hacer con las mismas asociaciones, por ejemplo para `has_many`:

```
:dependent

    Controls what happens to the associated objects when their owner is
    destroyed. Note that these are implemented as callbacks, and Rails
    executes callbacks in order. Therefore, other similar callbacks may
    affect the :dependent behavior, and the :dependent behavior may affect
    other callbacks.

        :destroy causes all the associated objects to also be destroyed.

        :delete_all causes all the associated objects to be deleted
        directly from the database (so callbacks will not be executed).

        :nullify causes the foreign keys to be set to NULL. Callbacks are
        not executed.

        :restrict_with_exception causes an exception to be raised if there
        are any associated records.

        :restrict_with_error causes an error to be added to the owner if
        there are any associated objects.
```

**Comment by m4tu5** [comment]
uhm, del menu de arriba, creo que iria por 
:restrict_with_error ... de esa forma, saltaría el error en la zona de 'notices', igual que cuando nos avisa de errores al crear o modificar objetos existentes, no?

estaria bien un mensaje en esa zona que diga, 'no se puede borrar la factura porque tiene recibos asociados' o algo del palo y lo mismo para recibos, etc.

una caja se puede borrar cuando tenga saldo 0, lo que significa que la vaciaron ... aunque en ese caso, en lugar de borrarla, la 'apagaría' para que no se vea en los listados, pero que no se borren los movimientos asociados ya que tienen interes historico.

**Comment by fauno** [comment]
me pongo con esto

**Comment by fauno** [comment]
entonces habria que agregar un campo 'archivado' a cajas que se pueda setear si el total es 0, luego las obras tienen cajas que no estan archivadas (con un scope)

**Comment by mauriciopasquier** [comment]
Para customizar los mensajes de error, usar esta estructura en el
`config/locales/cp.yml`:

```
es:
  activerecord:
    errors:
      models:
        <modelo>:
          base:
            restrict_dependent_destroy:
              has_many: "blablabla #{record.<metodo>} blablabla"
              has_one: "blablabla #{record.<metodo>} blablabla"
```

Obviamente reemplazar `<modelo>`, `<metodo>` y `<blablabla>`

**Comment by fauno** [comment]
che, las cajas se pueden destruir o cambio destruir por archivar?

## 

http://librevpn.org.ar

**Comment by m4tu5** [comment]
Cajas mejor archivar. Destruir movimientos viejos, para borrar una caja, puede ser un quilombo y perderíamos parte de la historia que es parte de lo que se quiere - lo otro es un pantallazo del presente y futuro próximo, para lo que de momento tenemos los saldos.

**Comment by m4tu5** [comment]
Algo así, si. Se archiva con saldo 0 y a parir de ahí no se muestra en la vistas de caja por defecto. Se accede a un listado de estas a través de un filtro que podremos en la gui.

Los movimientos no se tocan. Todo el resto de la navegación funciona igual.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> Algo así, si. Se archiva con saldo 0 y a parir de ahí no se muestra en
> la vistas de caja por defecto. Se accede a un listado de estas a
> través de un filtro que podremos en la gui.

ok

> Los movimientos no se tocan. Todo el resto de la navegación funciona
> igual.

o sea que elimino el destroy para movimientos?  aunque crees uno mal sin
querer?

## 

http://librevpn.org.ar

**Comment by m4tu5** [comment]
Borrar un movimiento mal si, sólo desde el recibo y afecta el saldo de la caja

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> Borrar un movimiento mal si, sólo desde el recibo y afecta el saldo de la caja

entonces hago que borrar un recibo borre los movimientos en cascada

pd: levantá hq que quiero ver mis mails!

## 

http://librevpn.org.ar

**Comment by m4tu5** [comment]
On 03/27/2014 10:08 PM, fauno wrote:

> m4tu5 notifications@github.com writes:
> 
> > Borrar un movimiento mal si, sólo desde el recibo y afecta el saldo de
> > la caja
> 
> entonces hago que borrar un recibo borre los movimientos en cascada

no, hace que solo se pueda borrar un recibo cuando no tenga movimientos.
o sea, manualmente se eliminan los movimientos (total no van a ser mas
de 2 o 3) y despues borras el recibo vacio.

la misma dinámica para la factura y sus recibos.

> pd: levantá hq que quiero ver mis mails!

lo levante hace rato, pero por alguna razon no te puedo pingear, ni en
navel.local ni en el ip publico.

ping a naven.local resuelve en el ip de lvpn (192.168.9.3) pero mcfly no
responde

**Comment by fauno** [comment]
bueno va quedando así:
- los movimientos se pueden borrar
- los cheques se pueden borrar
- los recibos se pueden borrar si no tienen movimientos
- las facturas se pueden borrar si no tienen recibos
- las cajas se archivan por defecto
- las cajas solo se archivan si tienen saldo 0
- las obras solo se borran si sus cajas no archivadas tienen saldo 0

que hago con terceros? nulifico las facturas? o hago que no se pueda hasta que no se borren las facturas?
