### ISSUE TITLE
Factura, creacion y validaciones

### ISSUE THREAD

**Issue by sudoaza** [lainventoria/tesoro#85]
En el branch feature/gui-autocomlete-git-fail ya asocie los campos de terceropara que se actualicen juntos y se esta guardando el Tercero_id en un campo hidden, pero falta y no se como hacer bien lo siguiente
- Cuando tercero_id este vacio y nombre_tercero y cuit_tercero llenos, crear el tercero y asociarlo
- Cuando este el tercero_id creo que funciona bien
- Validar los campos

mmm eso

**Comment by sudoaza** [comment]
También falta que al ver y editar la factura carguen los datos correspondientes, que para todo lo demas lo hace solo asi que asumo la estoy pifiando en algun lado ping @mauriciopasquier

**Comment by mauriciopasquier** [comment]
Podés hacer que el controlador cree un tercero si no existe.. en el update y
create de Factura le asociás tercero:

```
before_filter :asociar_tercero, only: [:create, :update]

...

def update
  ...
  @factura.tercero = @tercero
end

def create
  ...
  @factura.tercero = @tercero
end

private

  # Se crea un tercero sólo si no existe ya
  def asociar_tercero
    @tercero = if params[:tercero_id]
      Tercero.find(params[:tercero_id]
    else
      Tercero.new(
        nombre: params[:nombre_tercero], cuit: params[:cuit_tercero]
      )
    end
  end
```

Disclaimer: código con sueño y escrito en el issue directamente. Además, hay otros mecanismos pero sin cambiar la vista esto es lo más directo
