### ISSUE TITLE
home page (http://localhost:3000/obras) rota

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#87]
el home page (http://localhost:3000/obras) no carga por problemas de moneda. revisar los subtotales que se calculan en estas vistas

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> el home page (http://localhost:3000/obras) no carga por problemas de
> moneda. revisar los subtotales que se calculan en estas vistas

fijate en feature/saldo-general

## 

http://librevpn.org.ar
