### ISSUE TITLE
error al anidar vistas

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#91]
en este momento se puede ver dentro de una obra X una factura que corresponde a la obra Y
ej:

factura A es parte de obra Y, pero se puede acceder a ella via
/obras/X/factura/A

**Comment by mauriciopasquier** [comment]
ahí lo arreglo

**Comment by m4tu5** [comment]
mira #90 primero, que cambié alguna cosa en el selector de obras que tambien tiene que ver con rutas.

**Comment by mauriciopasquier** [comment]
ya lo había +1neado, mergealo y rebaseo (español? lo qué?)
