### ISSUE TITLE
filtros y ordenamientos

### ISSUE THREAD

**Issue by m4tu5** [lainventoria/tesoro#96]
tener botones interactivos en la cabecera de los listados que apliquen filtros o los ordenen.
- en terceros, poder listar clientes, proveedores, todos
- en cheques, poder listar cada posible estado (diferentes botones para propios/terceros)
- en retenciones, poder listar cada posible estado (creo que aun no agregamos este campo)
- en facturas, poder ordenar por fecha, monto, tercero
- en recibos, poder ordenar por fecha, monto, tercero
- en cheques, poder ordenar por fecha_vencimiento, monto
- en movimientos (cuando los haya), poder ordenar por fecha, monto

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> tener botones interactivos en la cabecera de los listados que apliquen filtros o los ordenen.
> - en terceros, poder listar clientes, proveedores, todos
> - en cheques, poder listar cada posible estado (diferentes botones para propios/terceros)
> - en retenciones, poder listar cada posible estado (creo que aun no agregamos este campo)
> - en facturas, poder ordenar por fecha, monto, tercero
> - en recibos, poder ordenar por fecha, monto, tercero
> - en cheques, poder ordenar por fecha_vencimiento, monto
> - en movimientos (cuando los haya), poder ordenar por fecha, monto

si seguimos agregando cosas no llegamos al miercoles ni en pedo :P

## 

http://partidopirata.com.ar

**Comment by m4tu5** [comment]
:) era una idea de donde enforca ezfuersos de aza que no entiende aun el modelo de datos
estoy abierto a otras opciones

**Comment by sudoaza** [comment]
hay un gem que creo lo hace relativament facil
toy probandolo
